// src/main/webapp/app/entities/detalhe-usuario/detalhe-usuario-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { JhiEventManager } from 'ng-jhipster';

import { IDetalheUsuario } from 'app/shared/model/detalhe-usuario.model';
import { DetalheUsuarioService } from './detalhe-usuario.service';

@Component({
  templateUrl: './detalhe-usuario-delete-dialog.component.html',
})
export class DetalheUsuarioDeleteDialogComponent {
  detalheUsuario?: IDetalheUsuario;

  constructor(
    protected detalheUsuarioService: DetalheUsuarioService,
    public activeModal: NgbActiveModal,
    protected eventManager: JhiEventManager
  ) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.detalheUsuarioService.delete(id).subscribe(() => {
      this.eventManager.broadcast('detalheUsuarioListModification');
      this.activeModal.close();
    });
  }
}

<form *ngIf="detalheUsuario" name="deleteForm" (ngSubmit)="confirmDelete(detalheUsuario?.id!)">
    <div class="modal-header">
        <h4 class="modal-title" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"
                (click)="cancel()">&times;</button>
    </div>

    <div class="modal-body">
        <jhi-alert-error></jhi-alert-error>

        <p id="jhi-delete-detalheUsuario-heading" jhiTranslate="escolaOnlineApp.detalheUsuario.delete.question" [translateValues]="{ id: detalheUsuario.id }">Are you sure you want to delete this Detalhe Usuario?</p>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
            <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button id="jhi-confirm-delete-detalheUsuario" type="submit" class="btn btn-danger">
            <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
        </button>
    </div>
</form>

// src/main/webapp/app/entities/detalhe-usuario/detalhe-usuario-delete-dialog.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { RouteComponentProps } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity, deleteEntity } from './detalhe-usuario.reducer';

export interface IDetalheUsuarioDeleteDialogProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const DetalheUsuarioDeleteDialog = (props: IDetalheUsuarioDeleteDialogProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const handleClose = () => {
    props.history.push('/detalhe-usuario' + props.location.search);
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const confirmDelete = () => {
    props.deleteEntity(props.detalheUsuarioEntity.id);
  };

  const { detalheUsuarioEntity } = props;
  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="detalheUsuarioDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="escolaOnlineApp.detalheUsuario.delete.question">
        <Translate contentKey="escolaOnlineApp.detalheUsuario.delete.question" interpolate={{ id: detalheUsuarioEntity.id }}>
          Are you sure you want to delete this DetalheUsuario?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-detalheUsuario" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

const mapStateToProps = ({ detalheUsuario }: IRootState) => ({
  detalheUsuarioEntity: detalheUsuario.entity,
  updateSuccess: detalheUsuario.updateSuccess,
});

const mapDispatchToProps = { getEntity, deleteEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(DetalheUsuarioDeleteDialog);
