// src/main/webapp/app/entities/tipo-solicitacao/tipo-solicitacao-delete-dialog.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { RouteComponentProps } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity, deleteEntity } from './tipo-solicitacao.reducer';

export interface ITipoSolicitacaoDeleteDialogProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const TipoSolicitacaoDeleteDialog = (props: ITipoSolicitacaoDeleteDialogProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const handleClose = () => {
    props.history.push('/tipo-solicitacao' + props.location.search);
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const confirmDelete = () => {
    props.deleteEntity(props.tipoSolicitacaoEntity.id);
  };

  const { tipoSolicitacaoEntity } = props;
  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="tipoSolicitacaoDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="escolaOnlineApp.tipoSolicitacao.delete.question">
        <Translate contentKey="escolaOnlineApp.tipoSolicitacao.delete.question" interpolate={{ id: tipoSolicitacaoEntity.id }}>
          Are you sure you want to delete this TipoSolicitacao?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-tipoSolicitacao" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

const mapStateToProps = ({ tipoSolicitacao }: IRootState) => ({
  tipoSolicitacaoEntity: tipoSolicitacao.entity,
  updateSuccess: tipoSolicitacao.updateSuccess,
});

const mapDispatchToProps = { getEntity, deleteEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(TipoSolicitacaoDeleteDialog);

// src/main/webapp/app/entities/tipo-solicitacao/delete/tipo-solicitacao-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';

import { ITipoSolicitacao } from '../tipo-solicitacao.model';
import { TipoSolicitacaoService } from '../service/tipo-solicitacao.service';

@Component({
  templateUrl: './tipo-solicitacao-delete-dialog.component.html',
})
export class TipoSolicitacaoDeleteDialogComponent {
  tipoSolicitacao?: ITipoSolicitacao;

  constructor(protected tipoSolicitacaoService: TipoSolicitacaoService, public activeModal: NgbActiveModal) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.tipoSolicitacaoService.delete(id).subscribe(() => {
      this.activeModal.close('deleted');
    });
  }
}

<form *ngIf="tipoSolicitacao" name="deleteForm" (ngSubmit)="confirmDelete(tipoSolicitacao.id!)">
  <div class="modal-header">
    <h4 class="modal-title" data-cy="tipoSolicitacaoDeleteDialogHeading" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

    <button type="button" class="close" data-dismiss="modal" aria-hidden="true" (click)="cancel()">&times;</button>
  </div>

  <div class="modal-body">
    <jhi-alert-error></jhi-alert-error>

    <p
      id="jhi-delete-tipoSolicitacao-heading"
      jhiTranslate="escolaOnlineApp.tipoSolicitacao.delete.question"
      [translateValues]="{ id: tipoSolicitacao.id }"
    >
      Are you sure you want to delete this Tipo Solicitacao?
    </p>
  </div>

  <div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
      <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
    </button>

    <button id="jhi-confirm-delete-tipoSolicitacao" data-cy="entityConfirmDeleteButton" type="submit" class="btn btn-danger">
      <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
    </button>
  </div>
</form>
