// src/main/webapp/app/entities/turma/list/turma.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ITurma } from '../turma.model';
import { TurmaService } from '../service/turma.service';
import { TurmaDeleteDialogComponent } from '../delete/turma-delete-dialog.component';

@Component({
  selector: 'jhi-turma',
  templateUrl: './turma.component.html',
})
export class TurmaComponent implements OnInit {
  turmas?: ITurma[];
  isLoading = false;

  constructor(protected turmaService: TurmaService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.turmaService.query().subscribe(
      (res: HttpResponse<ITurma[]>) => {
        this.isLoading = false;
        this.turmas = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ITurma): number {
    return item.id!;
  }

  delete(turma: ITurma): void {
    const modalRef = this.modalService.open(TurmaDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.turma = turma;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="TurmaHeading">
    <span jhiTranslate="escolaOnlineApp.turma.home.title">Turmas</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.turma.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-turma"
        [routerLink]="['/turma/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.turma.home.createLabel"> Create a new Turma </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="turmas?.length === 0">
    <span jhiTranslate="escolaOnlineApp.turma.home.notFound">No turmas found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="turmas && turmas.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.turma.nome">Nome</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.turma.serieTurma">Serie Turma</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.turma.unidadeTurma">Unidade Turma</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let turma of turmas; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/turma', turma.id, 'view']">{{ turma.id }}</a>
          </td>
          <td>{{ turma.nome }}</td>
          <td>
            <div *ngIf="turma.serieTurma">
              <a [routerLink]="['/serie', turma.serieTurma?.id, 'view']">{{ turma.serieTurma?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="turma.unidadeTurma">
              <a [routerLink]="['/unidade', turma.unidadeTurma?.id, 'view']">{{ turma.unidadeTurma?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/turma', turma.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/turma', turma.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(turma)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/turma/turma.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './turma.reducer';
import { ITurma } from 'app/shared/model/turma.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface ITurmaProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Turma = (props: ITurmaProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { turmaList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="turma-heading" data-cy="TurmaHeading">
        <Translate contentKey="escolaOnlineApp.turma.home.title">Turmas</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.turma.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.turma.home.createLabel">Create new Turma</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {turmaList && turmaList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.turma.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('nome')}>
                  <Translate contentKey="escolaOnlineApp.turma.nome">Nome</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.turma.serieTurma">Serie Turma</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.turma.unidadeTurma">Unidade Turma</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {turmaList.map((turma, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${turma.id}`} color="link" size="sm">
                      {turma.id}
                    </Button>
                  </td>
                  <td>{turma.id}</td>
                  <td>{turma.nome}</td>
                  <td>{turma.serieTurma ? <Link to={`serie/${turma.serieTurma.id}`}>{turma.serieTurma.id}</Link> : ''}</td>
                  <td>{turma.unidadeTurma ? <Link to={`unidade/${turma.unidadeTurma.id}`}>{turma.unidadeTurma.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${turma.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${turma.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${turma.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.turma.home.notFound">No Turmas found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={turmaList && turmaList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ turma }: IRootState) => ({
  turmaList: turma.entities,
  loading: turma.loading,
  totalItems: turma.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Turma);
