// src/main/webapp/app/entities/pessoa/pessoa-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IPessoa, Pessoa } from 'app/shared/model/pessoa.model';
import { PessoaService } from './pessoa.service';
import { ICidade } from 'app/shared/model/cidade.model';
import { CidadeService } from 'app/entities/cidade/cidade.service';
import { IEscola } from 'app/shared/model/escola.model';
import { EscolaService } from 'app/entities/escola/escola.service';

type SelectableEntity = ICidade | IEscola;

@Component({
  selector: 'jhi-pessoa-update',
  templateUrl: './pessoa-update.component.html',
})
export class PessoaUpdateComponent implements OnInit {
  isSaving = false;
  cidades: ICidade[] = [];
  escolas: IEscola[] = [];

  editForm = this.fb.group({
    id: [],
    nome: [],
    cpf: [],
    rg: [],
    endereco: [],
    complemento: [],
    bairro: [],
    cidade: [],
    cep: [],
    telefoneCelular: [],
    telefoneResidencial: [],
    telefoneComercial: [],
    email: [],
    observacoes: [],
    cidadePessoa: [],
    escolaPessoa: [],
  });

  constructor(
    protected pessoaService: PessoaService,
    protected cidadeService: CidadeService,
    protected escolaService: EscolaService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ pessoa }) => {
      this.updateForm(pessoa);

      this.cidadeService.query().subscribe((res: HttpResponse<ICidade[]>) => (this.cidades = res.body || []));

      this.escolaService.query().subscribe((res: HttpResponse<IEscola[]>) => (this.escolas = res.body || []));
    });
  }

  updateForm(pessoa: IPessoa): void {
    this.editForm.patchValue({
      id: pessoa.id,
      nome: pessoa.nome,
      cpf: pessoa.cpf,
      rg: pessoa.rg,
      endereco: pessoa.endereco,
      complemento: pessoa.complemento,
      bairro: pessoa.bairro,
      cidade: pessoa.cidade,
      cep: pessoa.cep,
      telefoneCelular: pessoa.telefoneCelular,
      telefoneResidencial: pessoa.telefoneResidencial,
      telefoneComercial: pessoa.telefoneComercial,
      email: pessoa.email,
      observacoes: pessoa.observacoes,
      cidadePessoa: pessoa.cidadePessoa,
      escolaPessoa: pessoa.escolaPessoa,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const pessoa = this.createFromForm();
    if (pessoa.id !== undefined) {
      this.subscribeToSaveResponse(this.pessoaService.update(pessoa));
    } else {
      this.subscribeToSaveResponse(this.pessoaService.create(pessoa));
    }
  }

  private createFromForm(): IPessoa {
    return {
      ...new Pessoa(),
      id: this.editForm.get(['id'])!.value,
      nome: this.editForm.get(['nome'])!.value,
      cpf: this.editForm.get(['cpf'])!.value,
      rg: this.editForm.get(['rg'])!.value,
      endereco: this.editForm.get(['endereco'])!.value,
      complemento: this.editForm.get(['complemento'])!.value,
      bairro: this.editForm.get(['bairro'])!.value,
      cidade: this.editForm.get(['cidade'])!.value,
      cep: this.editForm.get(['cep'])!.value,
      telefoneCelular: this.editForm.get(['telefoneCelular'])!.value,
      telefoneResidencial: this.editForm.get(['telefoneResidencial'])!.value,
      telefoneComercial: this.editForm.get(['telefoneComercial'])!.value,
      email: this.editForm.get(['email'])!.value,
      observacoes: this.editForm.get(['observacoes'])!.value,
      cidadePessoa: this.editForm.get(['cidadePessoa'])!.value,
      escolaPessoa: this.editForm.get(['escolaPessoa'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IPessoa>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: SelectableEntity): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-pessoa-heading" jhiTranslate="escolaOnlineApp.pessoa.home.createOrEditLabel">Create or edit a Pessoa</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.nome" for="field_nome">Nome</label>
                    <input type="text" class="form-control" name="nome" id="field_nome"
                           formControlName="nome"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.cpf" for="field_cpf">Cpf</label>
                    <input type="text" class="form-control" name="cpf" id="field_cpf"
                           formControlName="cpf"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.rg" for="field_rg">Rg</label>
                    <input type="text" class="form-control" name="rg" id="field_rg"
                           formControlName="rg"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.endereco" for="field_endereco">Endereco</label>
                    <input type="text" class="form-control" name="endereco" id="field_endereco"
                           formControlName="endereco"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.complemento" for="field_complemento">Complemento</label>
                    <input type="text" class="form-control" name="complemento" id="field_complemento"
                           formControlName="complemento"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.bairro" for="field_bairro">Bairro</label>
                    <input type="text" class="form-control" name="bairro" id="field_bairro"
                           formControlName="bairro"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.cidade" for="field_cidade">Cidade</label>
                    <input type="text" class="form-control" name="cidade" id="field_cidade"
                           formControlName="cidade"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.cep" for="field_cep">Cep</label>
                    <input type="text" class="form-control" name="cep" id="field_cep"
                           formControlName="cep"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.telefoneCelular" for="field_telefoneCelular">Telefone Celular</label>
                    <input type="text" class="form-control" name="telefoneCelular" id="field_telefoneCelular"
                           formControlName="telefoneCelular"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.telefoneResidencial" for="field_telefoneResidencial">Telefone Residencial</label>
                    <input type="text" class="form-control" name="telefoneResidencial" id="field_telefoneResidencial"
                           formControlName="telefoneResidencial"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.telefoneComercial" for="field_telefoneComercial">Telefone Comercial</label>
                    <input type="text" class="form-control" name="telefoneComercial" id="field_telefoneComercial"
                           formControlName="telefoneComercial"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.email" for="field_email">Email</label>
                    <input type="text" class="form-control" name="email" id="field_email"
                           formControlName="email"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.observacoes" for="field_observacoes">Observacoes</label>
                    <input type="text" class="form-control" name="observacoes" id="field_observacoes"
                           formControlName="observacoes"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.cidadePessoa" for="field_cidadePessoa">Cidade Pessoa</label>
                    <select class="form-control" id="field_cidadePessoa" name="cidadePessoa" formControlName="cidadePessoa">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="cidadeOption.id === editForm.get('cidadePessoa')!.value?.id ? editForm.get('cidadePessoa')!.value : cidadeOption" *ngFor="let cidadeOption of cidades; trackBy: trackById">{{ cidadeOption.id }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.pessoa.escolaPessoa" for="field_escolaPessoa">Escola Pessoa</label>
                    <select class="form-control" id="field_escolaPessoa" name="escolaPessoa" formControlName="escolaPessoa">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="escolaOption.id === editForm.get('escolaPessoa')!.value?.id ? editForm.get('escolaPessoa')!.value : escolaOption" *ngFor="let escolaOption of escolas; trackBy: trackById">{{ escolaOption.id }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/pessoa/pessoa-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ICidade } from 'app/shared/model/cidade.model';
import { getEntities as getCidades } from 'app/entities/cidade/cidade.reducer';
import { IEscola } from 'app/shared/model/escola.model';
import { getEntities as getEscolas } from 'app/entities/escola/escola.reducer';
import { getEntity, updateEntity, createEntity, reset } from './pessoa.reducer';
import { IPessoa } from 'app/shared/model/pessoa.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IPessoaUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const PessoaUpdate = (props: IPessoaUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { pessoaEntity, cidades, escolas, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/pessoa' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getCidades();
    props.getEscolas();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...pessoaEntity,
        ...values,
        cidadePessoa: cidades.find(it => it.id.toString() === values.cidadePessoaId.toString()),
        escolaPessoa: escolas.find(it => it.id.toString() === values.escolaPessoaId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.pessoa.home.createOrEditLabel" data-cy="PessoaCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.pessoa.home.createOrEditLabel">Create or edit a Pessoa</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : pessoaEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="pessoa-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="pessoa-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="nomeLabel" for="pessoa-nome">
                  <Translate contentKey="escolaOnlineApp.pessoa.nome">Nome</Translate>
                </Label>
                <AvField id="pessoa-nome" data-cy="nome" type="text" name="nome" />
              </AvGroup>
              <AvGroup>
                <Label id="cpfLabel" for="pessoa-cpf">
                  <Translate contentKey="escolaOnlineApp.pessoa.cpf">Cpf</Translate>
                </Label>
                <AvField id="pessoa-cpf" data-cy="cpf" type="text" name="cpf" />
              </AvGroup>
              <AvGroup>
                <Label id="rgLabel" for="pessoa-rg">
                  <Translate contentKey="escolaOnlineApp.pessoa.rg">Rg</Translate>
                </Label>
                <AvField id="pessoa-rg" data-cy="rg" type="text" name="rg" />
              </AvGroup>
              <AvGroup>
                <Label id="enderecoLabel" for="pessoa-endereco">
                  <Translate contentKey="escolaOnlineApp.pessoa.endereco">Endereco</Translate>
                </Label>
                <AvField id="pessoa-endereco" data-cy="endereco" type="text" name="endereco" />
              </AvGroup>
              <AvGroup>
                <Label id="complementoLabel" for="pessoa-complemento">
                  <Translate contentKey="escolaOnlineApp.pessoa.complemento">Complemento</Translate>
                </Label>
                <AvField id="pessoa-complemento" data-cy="complemento" type="text" name="complemento" />
              </AvGroup>
              <AvGroup>
                <Label id="bairroLabel" for="pessoa-bairro">
                  <Translate contentKey="escolaOnlineApp.pessoa.bairro">Bairro</Translate>
                </Label>
                <AvField id="pessoa-bairro" data-cy="bairro" type="text" name="bairro" />
              </AvGroup>
              <AvGroup>
                <Label id="cidadeLabel" for="pessoa-cidade">
                  <Translate contentKey="escolaOnlineApp.pessoa.cidade">Cidade</Translate>
                </Label>
                <AvField id="pessoa-cidade" data-cy="cidade" type="text" name="cidade" />
              </AvGroup>
              <AvGroup>
                <Label id="cepLabel" for="pessoa-cep">
                  <Translate contentKey="escolaOnlineApp.pessoa.cep">Cep</Translate>
                </Label>
                <AvField id="pessoa-cep" data-cy="cep" type="text" name="cep" />
              </AvGroup>
              <AvGroup>
                <Label id="telefoneCelularLabel" for="pessoa-telefoneCelular">
                  <Translate contentKey="escolaOnlineApp.pessoa.telefoneCelular">Telefone Celular</Translate>
                </Label>
                <AvField id="pessoa-telefoneCelular" data-cy="telefoneCelular" type="text" name="telefoneCelular" />
              </AvGroup>
              <AvGroup>
                <Label id="telefoneResidencialLabel" for="pessoa-telefoneResidencial">
                  <Translate contentKey="escolaOnlineApp.pessoa.telefoneResidencial">Telefone Residencial</Translate>
                </Label>
                <AvField id="pessoa-telefoneResidencial" data-cy="telefoneResidencial" type="text" name="telefoneResidencial" />
              </AvGroup>
              <AvGroup>
                <Label id="telefoneComercialLabel" for="pessoa-telefoneComercial">
                  <Translate contentKey="escolaOnlineApp.pessoa.telefoneComercial">Telefone Comercial</Translate>
                </Label>
                <AvField id="pessoa-telefoneComercial" data-cy="telefoneComercial" type="text" name="telefoneComercial" />
              </AvGroup>
              <AvGroup>
                <Label id="emailLabel" for="pessoa-email">
                  <Translate contentKey="escolaOnlineApp.pessoa.email">Email</Translate>
                </Label>
                <AvField id="pessoa-email" data-cy="email" type="text" name="email" />
              </AvGroup>
              <AvGroup>
                <Label id="observacoesLabel" for="pessoa-observacoes">
                  <Translate contentKey="escolaOnlineApp.pessoa.observacoes">Observacoes</Translate>
                </Label>
                <AvField id="pessoa-observacoes" data-cy="observacoes" type="text" name="observacoes" />
              </AvGroup>
              <AvGroup>
                <Label for="pessoa-cidadePessoa">
                  <Translate contentKey="escolaOnlineApp.pessoa.cidadePessoa">Cidade Pessoa</Translate>
                </Label>
                <AvInput id="pessoa-cidadePessoa" data-cy="cidadePessoa" type="select" className="form-control" name="cidadePessoaId">
                  <option value="" key="0" />
                  {cidades
                    ? cidades.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="pessoa-escolaPessoa">
                  <Translate contentKey="escolaOnlineApp.pessoa.escolaPessoa">Escola Pessoa</Translate>
                </Label>
                <AvInput id="pessoa-escolaPessoa" data-cy="escolaPessoa" type="select" className="form-control" name="escolaPessoaId">
                  <option value="" key="0" />
                  {escolas
                    ? escolas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/pessoa" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  cidades: storeState.cidade.entities,
  escolas: storeState.escola.entities,
  pessoaEntity: storeState.pessoa.entity,
  loading: storeState.pessoa.loading,
  updating: storeState.pessoa.updating,
  updateSuccess: storeState.pessoa.updateSuccess,
});

const mapDispatchToProps = {
  getCidades,
  getEscolas,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(PessoaUpdate);
