// src/main/webapp/app/entities/escola/update/escola-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { IEscola, Escola } from '../escola.model';
import { EscolaService } from '../service/escola.service';

@Component({
  selector: 'jhi-escola-update',
  templateUrl: './escola-update.component.html',
})
export class EscolaUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    nome: [],
    razaoSocial: [],
    cnpjPrincipal: [],
    url: [],
    prefixo: [],
    responsavelNome: [],
    responsavelCpf: [],
    responsavelEmail: [],
    responsavelCelular: [],
  });

  constructor(protected escolaService: EscolaService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ escola }) => {
      this.updateForm(escola);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const escola = this.createFromForm();
    if (escola.id !== undefined) {
      this.subscribeToSaveResponse(this.escolaService.update(escola));
    } else {
      this.subscribeToSaveResponse(this.escolaService.create(escola));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IEscola>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(escola: IEscola): void {
    this.editForm.patchValue({
      id: escola.id,
      nome: escola.nome,
      razaoSocial: escola.razaoSocial,
      cnpjPrincipal: escola.cnpjPrincipal,
      url: escola.url,
      prefixo: escola.prefixo,
      responsavelNome: escola.responsavelNome,
      responsavelCpf: escola.responsavelCpf,
      responsavelEmail: escola.responsavelEmail,
      responsavelCelular: escola.responsavelCelular,
    });
  }

  protected createFromForm(): IEscola {
    return {
      ...new Escola(),
      id: this.editForm.get(['id'])!.value,
      nome: this.editForm.get(['nome'])!.value,
      razaoSocial: this.editForm.get(['razaoSocial'])!.value,
      cnpjPrincipal: this.editForm.get(['cnpjPrincipal'])!.value,
      url: this.editForm.get(['url'])!.value,
      prefixo: this.editForm.get(['prefixo'])!.value,
      responsavelNome: this.editForm.get(['responsavelNome'])!.value,
      responsavelCpf: this.editForm.get(['responsavelCpf'])!.value,
      responsavelEmail: this.editForm.get(['responsavelEmail'])!.value,
      responsavelCelular: this.editForm.get(['responsavelCelular'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-escola-heading" data-cy="EscolaCreateUpdateHeading" jhiTranslate="escolaOnlineApp.escola.home.createOrEditLabel">
        Create or edit a Escola
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.nome" for="field_nome">Nome</label>
          <input type="text" class="form-control" name="nome" id="field_nome" data-cy="nome" formControlName="nome" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.razaoSocial" for="field_razaoSocial">Razao Social</label>
          <input
            type="text"
            class="form-control"
            name="razaoSocial"
            id="field_razaoSocial"
            data-cy="razaoSocial"
            formControlName="razaoSocial"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.cnpjPrincipal" for="field_cnpjPrincipal"
            >Cnpj Principal</label
          >
          <input
            type="text"
            class="form-control"
            name="cnpjPrincipal"
            id="field_cnpjPrincipal"
            data-cy="cnpjPrincipal"
            formControlName="cnpjPrincipal"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.url" for="field_url">Url</label>
          <input type="text" class="form-control" name="url" id="field_url" data-cy="url" formControlName="url" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.prefixo" for="field_prefixo">Prefixo</label>
          <input type="text" class="form-control" name="prefixo" id="field_prefixo" data-cy="prefixo" formControlName="prefixo" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.responsavelNome" for="field_responsavelNome"
            >Responsavel Nome</label
          >
          <input
            type="text"
            class="form-control"
            name="responsavelNome"
            id="field_responsavelNome"
            data-cy="responsavelNome"
            formControlName="responsavelNome"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.responsavelCpf" for="field_responsavelCpf"
            >Responsavel Cpf</label
          >
          <input
            type="text"
            class="form-control"
            name="responsavelCpf"
            id="field_responsavelCpf"
            data-cy="responsavelCpf"
            formControlName="responsavelCpf"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.responsavelEmail" for="field_responsavelEmail"
            >Responsavel Email</label
          >
          <input
            type="text"
            class="form-control"
            name="responsavelEmail"
            id="field_responsavelEmail"
            data-cy="responsavelEmail"
            formControlName="responsavelEmail"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.escola.responsavelCelular" for="field_responsavelCelular"
            >Responsavel Celular</label
          >
          <input
            type="text"
            class="form-control"
            name="responsavelCelular"
            id="field_responsavelCelular"
            data-cy="responsavelCelular"
            formControlName="responsavelCelular"
          />
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/escola/escola-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { getEntity, updateEntity, createEntity, reset } from './escola.reducer';
import { IEscola } from 'app/shared/model/escola.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IEscolaUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const EscolaUpdate = (props: IEscolaUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { escolaEntity, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/escola' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...escolaEntity,
        ...values,
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.escola.home.createOrEditLabel" data-cy="EscolaCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.escola.home.createOrEditLabel">Create or edit a Escola</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : escolaEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="escola-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="escola-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="nomeLabel" for="escola-nome">
                  <Translate contentKey="escolaOnlineApp.escola.nome">Nome</Translate>
                </Label>
                <AvField id="escola-nome" data-cy="nome" type="text" name="nome" />
              </AvGroup>
              <AvGroup>
                <Label id="razaoSocialLabel" for="escola-razaoSocial">
                  <Translate contentKey="escolaOnlineApp.escola.razaoSocial">Razao Social</Translate>
                </Label>
                <AvField id="escola-razaoSocial" data-cy="razaoSocial" type="text" name="razaoSocial" />
              </AvGroup>
              <AvGroup>
                <Label id="cnpjPrincipalLabel" for="escola-cnpjPrincipal">
                  <Translate contentKey="escolaOnlineApp.escola.cnpjPrincipal">Cnpj Principal</Translate>
                </Label>
                <AvField id="escola-cnpjPrincipal" data-cy="cnpjPrincipal" type="text" name="cnpjPrincipal" />
              </AvGroup>
              <AvGroup>
                <Label id="urlLabel" for="escola-url">
                  <Translate contentKey="escolaOnlineApp.escola.url">Url</Translate>
                </Label>
                <AvField id="escola-url" data-cy="url" type="text" name="url" />
              </AvGroup>
              <AvGroup>
                <Label id="prefixoLabel" for="escola-prefixo">
                  <Translate contentKey="escolaOnlineApp.escola.prefixo">Prefixo</Translate>
                </Label>
                <AvField id="escola-prefixo" data-cy="prefixo" type="text" name="prefixo" />
              </AvGroup>
              <AvGroup>
                <Label id="responsavelNomeLabel" for="escola-responsavelNome">
                  <Translate contentKey="escolaOnlineApp.escola.responsavelNome">Responsavel Nome</Translate>
                </Label>
                <AvField id="escola-responsavelNome" data-cy="responsavelNome" type="text" name="responsavelNome" />
              </AvGroup>
              <AvGroup>
                <Label id="responsavelCpfLabel" for="escola-responsavelCpf">
                  <Translate contentKey="escolaOnlineApp.escola.responsavelCpf">Responsavel Cpf</Translate>
                </Label>
                <AvField id="escola-responsavelCpf" data-cy="responsavelCpf" type="text" name="responsavelCpf" />
              </AvGroup>
              <AvGroup>
                <Label id="responsavelEmailLabel" for="escola-responsavelEmail">
                  <Translate contentKey="escolaOnlineApp.escola.responsavelEmail">Responsavel Email</Translate>
                </Label>
                <AvField id="escola-responsavelEmail" data-cy="responsavelEmail" type="text" name="responsavelEmail" />
              </AvGroup>
              <AvGroup>
                <Label id="responsavelCelularLabel" for="escola-responsavelCelular">
                  <Translate contentKey="escolaOnlineApp.escola.responsavelCelular">Responsavel Celular</Translate>
                </Label>
                <AvField id="escola-responsavelCelular" data-cy="responsavelCelular" type="text" name="responsavelCelular" />
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/escola" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  escolaEntity: storeState.escola.entity,
  loading: storeState.escola.loading,
  updating: storeState.escola.updating,
  updateSuccess: storeState.escola.updateSuccess,
});

const mapDispatchToProps = {
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(EscolaUpdate);
