// src/main/webapp/app/entities/historico-debito/historico-debito-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IDebito } from 'app/shared/model/debito.model';
import { getEntities as getDebitos } from 'app/entities/debito/debito.reducer';
import { IDetalheUsuario } from 'app/shared/model/detalhe-usuario.model';
import { getEntities as getDetalheUsuarios } from 'app/entities/detalhe-usuario/detalhe-usuario.reducer';
import { getEntity, updateEntity, createEntity, reset } from './historico-debito.reducer';
import { IHistoricoDebito } from 'app/shared/model/historico-debito.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IHistoricoDebitoUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const HistoricoDebitoUpdate = (props: IHistoricoDebitoUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { historicoDebitoEntity, debitos, detalheUsuarios, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/historico-debito' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getDebitos();
    props.getDetalheUsuarios();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...historicoDebitoEntity,
        ...values,
        debitoHistoricoDebito: debitos.find(it => it.id.toString() === values.debitoHistoricoDebitoId.toString()),
        detalheUsuarioLancamento: detalheUsuarios.find(it => it.id.toString() === values.detalheUsuarioLancamentoId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.historicoDebito.home.createOrEditLabel" data-cy="HistoricoDebitoCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.historicoDebito.home.createOrEditLabel">Create or edit a HistoricoDebito</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : historicoDebitoEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="historico-debito-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="historico-debito-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="dataLancamentoLabel" for="historico-debito-dataLancamento">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.dataLancamento">Data Lancamento</Translate>
                </Label>
                <AvField
                  id="historico-debito-dataLancamento"
                  data-cy="dataLancamento"
                  type="date"
                  className="form-control"
                  name="dataLancamento"
                />
              </AvGroup>
              <AvGroup>
                <Label id="situacaoDebitoLabel" for="historico-debito-situacaoDebito">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.situacaoDebito">Situacao Debito</Translate>
                </Label>
                <AvInput
                  id="historico-debito-situacaoDebito"
                  data-cy="situacaoDebito"
                  type="select"
                  className="form-control"
                  name="situacaoDebito"
                  value={(!isNew && historicoDebitoEntity.situacaoDebito) || 'NAO_PAGO'}
                >
                  <option value="NAO_PAGO">{translate('escolaOnlineApp.SituacaoDebito.NAO_PAGO')}</option>
                  <option value="PAGO_PARCIAL">{translate('escolaOnlineApp.SituacaoDebito.PAGO_PARCIAL')}</option>
                  <option value="PAGO">{translate('escolaOnlineApp.SituacaoDebito.PAGO')}</option>
                  <option value="CANCELADO">{translate('escolaOnlineApp.SituacaoDebito.CANCELADO')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="dataVencimentoLabel" for="historico-debito-dataVencimento">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.dataVencimento">Data Vencimento</Translate>
                </Label>
                <AvField
                  id="historico-debito-dataVencimento"
                  data-cy="dataVencimento"
                  type="date"
                  className="form-control"
                  name="dataVencimento"
                />
              </AvGroup>
              <AvGroup>
                <Label id="dataPagamentoLabel" for="historico-debito-dataPagamento">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.dataPagamento">Data Pagamento</Translate>
                </Label>
                <AvField
                  id="historico-debito-dataPagamento"
                  data-cy="dataPagamento"
                  type="date"
                  className="form-control"
                  name="dataPagamento"
                />
              </AvGroup>
              <AvGroup>
                <Label id="valorOriginalLabel" for="historico-debito-valorOriginal">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.valorOriginal">Valor Original</Translate>
                </Label>
                <AvField id="historico-debito-valorOriginal" data-cy="valorOriginal" type="text" name="valorOriginal" />
              </AvGroup>
              <AvGroup>
                <Label id="totalPagoLabel" for="historico-debito-totalPago">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.totalPago">Total Pago</Translate>
                </Label>
                <AvField id="historico-debito-totalPago" data-cy="totalPago" type="text" name="totalPago" />
              </AvGroup>
              <AvGroup>
                <Label id="totalDescontoLabel" for="historico-debito-totalDesconto">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.totalDesconto">Total Desconto</Translate>
                </Label>
                <AvField id="historico-debito-totalDesconto" data-cy="totalDesconto" type="text" name="totalDesconto" />
              </AvGroup>
              <AvGroup>
                <Label id="totalDevidoLabel" for="historico-debito-totalDevido">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.totalDevido">Total Devido</Translate>
                </Label>
                <AvField id="historico-debito-totalDevido" data-cy="totalDevido" type="text" name="totalDevido" />
              </AvGroup>
              <AvGroup>
                <Label id="observacoesLabel" for="historico-debito-observacoes">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.observacoes">Observacoes</Translate>
                </Label>
                <AvField id="historico-debito-observacoes" data-cy="observacoes" type="text" name="observacoes" />
              </AvGroup>
              <AvGroup>
                <Label for="historico-debito-debitoHistoricoDebito">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.debitoHistoricoDebito">Debito Historico Debito</Translate>
                </Label>
                <AvInput
                  id="historico-debito-debitoHistoricoDebito"
                  data-cy="debitoHistoricoDebito"
                  type="select"
                  className="form-control"
                  name="debitoHistoricoDebitoId"
                >
                  <option value="" key="0" />
                  {debitos
                    ? debitos.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="historico-debito-detalheUsuarioLancamento">
                  <Translate contentKey="escolaOnlineApp.historicoDebito.detalheUsuarioLancamento">Detalhe Usuario Lancamento</Translate>
                </Label>
                <AvInput
                  id="historico-debito-detalheUsuarioLancamento"
                  data-cy="detalheUsuarioLancamento"
                  type="select"
                  className="form-control"
                  name="detalheUsuarioLancamentoId"
                >
                  <option value="" key="0" />
                  {detalheUsuarios
                    ? detalheUsuarios.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/historico-debito" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  debitos: storeState.debito.entities,
  detalheUsuarios: storeState.detalheUsuario.entities,
  historicoDebitoEntity: storeState.historicoDebito.entity,
  loading: storeState.historicoDebito.loading,
  updating: storeState.historicoDebito.updating,
  updateSuccess: storeState.historicoDebito.updateSuccess,
});

const mapDispatchToProps = {
  getDebitos,
  getDetalheUsuarios,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(HistoricoDebitoUpdate);

// src/main/webapp/app/entities/historico-debito/update/historico-debito-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IHistoricoDebito, HistoricoDebito } from '../historico-debito.model';
import { HistoricoDebitoService } from '../service/historico-debito.service';
import { IDebito } from 'app/entities/debito/debito.model';
import { DebitoService } from 'app/entities/debito/service/debito.service';
import { IDetalheUsuario } from 'app/entities/detalhe-usuario/detalhe-usuario.model';
import { DetalheUsuarioService } from 'app/entities/detalhe-usuario/service/detalhe-usuario.service';

@Component({
  selector: 'jhi-historico-debito-update',
  templateUrl: './historico-debito-update.component.html',
})
export class HistoricoDebitoUpdateComponent implements OnInit {
  isSaving = false;

  debitosSharedCollection: IDebito[] = [];
  detalheUsuariosSharedCollection: IDetalheUsuario[] = [];

  editForm = this.fb.group({
    id: [],
    dataLancamento: [],
    situacaoDebito: [],
    dataVencimento: [],
    dataPagamento: [],
    valorOriginal: [],
    totalPago: [],
    totalDesconto: [],
    totalDevido: [],
    observacoes: [],
    debitoHistoricoDebito: [],
    detalheUsuarioLancamento: [],
  });

  constructor(
    protected historicoDebitoService: HistoricoDebitoService,
    protected debitoService: DebitoService,
    protected detalheUsuarioService: DetalheUsuarioService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ historicoDebito }) => {
      this.updateForm(historicoDebito);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const historicoDebito = this.createFromForm();
    if (historicoDebito.id !== undefined) {
      this.subscribeToSaveResponse(this.historicoDebitoService.update(historicoDebito));
    } else {
      this.subscribeToSaveResponse(this.historicoDebitoService.create(historicoDebito));
    }
  }

  trackDebitoById(index: number, item: IDebito): number {
    return item.id!;
  }

  trackDetalheUsuarioById(index: number, item: IDetalheUsuario): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IHistoricoDebito>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(historicoDebito: IHistoricoDebito): void {
    this.editForm.patchValue({
      id: historicoDebito.id,
      dataLancamento: historicoDebito.dataLancamento,
      situacaoDebito: historicoDebito.situacaoDebito,
      dataVencimento: historicoDebito.dataVencimento,
      dataPagamento: historicoDebito.dataPagamento,
      valorOriginal: historicoDebito.valorOriginal,
      totalPago: historicoDebito.totalPago,
      totalDesconto: historicoDebito.totalDesconto,
      totalDevido: historicoDebito.totalDevido,
      observacoes: historicoDebito.observacoes,
      debitoHistoricoDebito: historicoDebito.debitoHistoricoDebito,
      detalheUsuarioLancamento: historicoDebito.detalheUsuarioLancamento,
    });

    this.debitosSharedCollection = this.debitoService.addDebitoToCollectionIfMissing(
      this.debitosSharedCollection,
      historicoDebito.debitoHistoricoDebito
    );
    this.detalheUsuariosSharedCollection = this.detalheUsuarioService.addDetalheUsuarioToCollectionIfMissing(
      this.detalheUsuariosSharedCollection,
      historicoDebito.detalheUsuarioLancamento
    );
  }

  protected loadRelationshipsOptions(): void {
    this.debitoService
      .query()
      .pipe(map((res: HttpResponse<IDebito[]>) => res.body ?? []))
      .pipe(
        map((debitos: IDebito[]) =>
          this.debitoService.addDebitoToCollectionIfMissing(debitos, this.editForm.get('debitoHistoricoDebito')!.value)
        )
      )
      .subscribe((debitos: IDebito[]) => (this.debitosSharedCollection = debitos));

    this.detalheUsuarioService
      .query()
      .pipe(map((res: HttpResponse<IDetalheUsuario[]>) => res.body ?? []))
      .pipe(
        map((detalheUsuarios: IDetalheUsuario[]) =>
          this.detalheUsuarioService.addDetalheUsuarioToCollectionIfMissing(
            detalheUsuarios,
            this.editForm.get('detalheUsuarioLancamento')!.value
          )
        )
      )
      .subscribe((detalheUsuarios: IDetalheUsuario[]) => (this.detalheUsuariosSharedCollection = detalheUsuarios));
  }

  protected createFromForm(): IHistoricoDebito {
    return {
      ...new HistoricoDebito(),
      id: this.editForm.get(['id'])!.value,
      dataLancamento: this.editForm.get(['dataLancamento'])!.value,
      situacaoDebito: this.editForm.get(['situacaoDebito'])!.value,
      dataVencimento: this.editForm.get(['dataVencimento'])!.value,
      dataPagamento: this.editForm.get(['dataPagamento'])!.value,
      valorOriginal: this.editForm.get(['valorOriginal'])!.value,
      totalPago: this.editForm.get(['totalPago'])!.value,
      totalDesconto: this.editForm.get(['totalDesconto'])!.value,
      totalDevido: this.editForm.get(['totalDevido'])!.value,
      observacoes: this.editForm.get(['observacoes'])!.value,
      debitoHistoricoDebito: this.editForm.get(['debitoHistoricoDebito'])!.value,
      detalheUsuarioLancamento: this.editForm.get(['detalheUsuarioLancamento'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2
        id="jhi-historico-debito-heading"
        data-cy="HistoricoDebitoCreateUpdateHeading"
        jhiTranslate="escolaOnlineApp.historicoDebito.home.createOrEditLabel"
      >
        Create or edit a Historico Debito
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.dataLancamento" for="field_dataLancamento"
            >Data Lancamento</label
          >
          <div class="input-group">
            <input
              id="field_dataLancamento"
              data-cy="dataLancamento"
              type="text"
              class="form-control"
              name="dataLancamento"
              ngbDatepicker
              #dataLancamentoDp="ngbDatepicker"
              formControlName="dataLancamento"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataLancamentoDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.situacaoDebito" for="field_situacaoDebito"
            >Situacao Debito</label
          >
          <select
            class="form-control"
            name="situacaoDebito"
            formControlName="situacaoDebito"
            id="field_situacaoDebito"
            data-cy="situacaoDebito"
          >
            <option [ngValue]="null">{{ 'escolaOnlineApp.SituacaoDebito.null' | translate }}</option>
            <option value="NAO_PAGO">{{ 'escolaOnlineApp.SituacaoDebito.NAO_PAGO' | translate }}</option>
            <option value="PAGO_PARCIAL">{{ 'escolaOnlineApp.SituacaoDebito.PAGO_PARCIAL' | translate }}</option>
            <option value="PAGO">{{ 'escolaOnlineApp.SituacaoDebito.PAGO' | translate }}</option>
            <option value="CANCELADO">{{ 'escolaOnlineApp.SituacaoDebito.CANCELADO' | translate }}</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.dataVencimento" for="field_dataVencimento"
            >Data Vencimento</label
          >
          <div class="input-group">
            <input
              id="field_dataVencimento"
              data-cy="dataVencimento"
              type="text"
              class="form-control"
              name="dataVencimento"
              ngbDatepicker
              #dataVencimentoDp="ngbDatepicker"
              formControlName="dataVencimento"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataVencimentoDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.dataPagamento" for="field_dataPagamento"
            >Data Pagamento</label
          >
          <div class="input-group">
            <input
              id="field_dataPagamento"
              data-cy="dataPagamento"
              type="text"
              class="form-control"
              name="dataPagamento"
              ngbDatepicker
              #dataPagamentoDp="ngbDatepicker"
              formControlName="dataPagamento"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataPagamentoDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.valorOriginal" for="field_valorOriginal"
            >Valor Original</label
          >
          <input
            type="number"
            class="form-control"
            name="valorOriginal"
            id="field_valorOriginal"
            data-cy="valorOriginal"
            formControlName="valorOriginal"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.totalPago" for="field_totalPago"
            >Total Pago</label
          >
          <input type="number" class="form-control" name="totalPago" id="field_totalPago" data-cy="totalPago" formControlName="totalPago" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.totalDesconto" for="field_totalDesconto"
            >Total Desconto</label
          >
          <input
            type="number"
            class="form-control"
            name="totalDesconto"
            id="field_totalDesconto"
            data-cy="totalDesconto"
            formControlName="totalDesconto"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.totalDevido" for="field_totalDevido"
            >Total Devido</label
          >
          <input
            type="number"
            class="form-control"
            name="totalDevido"
            id="field_totalDevido"
            data-cy="totalDevido"
            formControlName="totalDevido"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.historicoDebito.observacoes" for="field_observacoes"
            >Observacoes</label
          >
          <input
            type="text"
            class="form-control"
            name="observacoes"
            id="field_observacoes"
            data-cy="observacoes"
            formControlName="observacoes"
          />
        </div>

        <div class="form-group">
          <label
            class="form-control-label"
            jhiTranslate="escolaOnlineApp.historicoDebito.debitoHistoricoDebito"
            for="field_debitoHistoricoDebito"
            >Debito Historico Debito</label
          >
          <select
            class="form-control"
            id="field_debitoHistoricoDebito"
            data-cy="debitoHistoricoDebito"
            name="debitoHistoricoDebito"
            formControlName="debitoHistoricoDebito"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                debitoOption.id === editForm.get('debitoHistoricoDebito')!.value?.id
                  ? editForm.get('debitoHistoricoDebito')!.value
                  : debitoOption
              "
              *ngFor="let debitoOption of debitosSharedCollection; trackBy: trackDebitoById"
            >
              {{ debitoOption.id }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label
            class="form-control-label"
            jhiTranslate="escolaOnlineApp.historicoDebito.detalheUsuarioLancamento"
            for="field_detalheUsuarioLancamento"
            >Detalhe Usuario Lancamento</label
          >
          <select
            class="form-control"
            id="field_detalheUsuarioLancamento"
            data-cy="detalheUsuarioLancamento"
            name="detalheUsuarioLancamento"
            formControlName="detalheUsuarioLancamento"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                detalheUsuarioOption.id === editForm.get('detalheUsuarioLancamento')!.value?.id
                  ? editForm.get('detalheUsuarioLancamento')!.value
                  : detalheUsuarioOption
              "
              *ngFor="let detalheUsuarioOption of detalheUsuariosSharedCollection; trackBy: trackDetalheUsuarioById"
            >
              {{ detalheUsuarioOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
