// src/main/webapp/app/entities/matricula/list/matricula.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IMatricula } from '../matricula.model';
import { MatriculaService } from '../service/matricula.service';
import { MatriculaDeleteDialogComponent } from '../delete/matricula-delete-dialog.component';

@Component({
  selector: 'jhi-matricula',
  templateUrl: './matricula.component.html',
})
export class MatriculaComponent implements OnInit {
  matriculas?: IMatricula[];
  isLoading = false;

  constructor(protected matriculaService: MatriculaService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.matriculaService.query().subscribe(
      (res: HttpResponse<IMatricula[]>) => {
        this.isLoading = false;
        this.matriculas = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IMatricula): number {
    return item.id!;
  }

  delete(matricula: IMatricula): void {
    const modalRef = this.modalService.open(MatriculaDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.matricula = matricula;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="MatriculaHeading">
    <span jhiTranslate="escolaOnlineApp.matricula.home.title">Matriculas</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.matricula.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-matricula"
        [routerLink]="['/matricula/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.matricula.home.createLabel"> Create a new Matricula </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="matriculas?.length === 0">
    <span jhiTranslate="escolaOnlineApp.matricula.home.notFound">No matriculas found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="matriculas && matriculas.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.matricula.anoLetivo">Ano Letivo</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.matricula.dataInicio">Data Inicio</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.matricula.dataFim">Data Fim</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.matricula.turmaMatricula">Turma Matricula</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.matricula.alunoMatricula">Aluno Matricula</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let matricula of matriculas; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/matricula', matricula.id, 'view']">{{ matricula.id }}</a>
          </td>
          <td>{{ matricula.anoLetivo }}</td>
          <td>{{ matricula.dataInicio | formatMediumDate }}</td>
          <td>{{ matricula.dataFim | formatMediumDate }}</td>
          <td>
            <div *ngIf="matricula.turmaMatricula">
              <a [routerLink]="['/turma', matricula.turmaMatricula?.id, 'view']">{{ matricula.turmaMatricula?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="matricula.alunoMatricula">
              <a [routerLink]="['/aluno', matricula.alunoMatricula?.id, 'view']">{{ matricula.alunoMatricula?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/matricula', matricula.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/matricula', matricula.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(matricula)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/matricula/matricula.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './matricula.reducer';
import { IMatricula } from 'app/shared/model/matricula.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IMatriculaProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Matricula = (props: IMatriculaProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { matriculaList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="matricula-heading" data-cy="MatriculaHeading">
        <Translate contentKey="escolaOnlineApp.matricula.home.title">Matriculas</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.matricula.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.matricula.home.createLabel">Create new Matricula</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {matriculaList && matriculaList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.matricula.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('anoLetivo')}>
                  <Translate contentKey="escolaOnlineApp.matricula.anoLetivo">Ano Letivo</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataInicio')}>
                  <Translate contentKey="escolaOnlineApp.matricula.dataInicio">Data Inicio</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataFim')}>
                  <Translate contentKey="escolaOnlineApp.matricula.dataFim">Data Fim</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.matricula.turmaMatricula">Turma Matricula</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.matricula.alunoMatricula">Aluno Matricula</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {matriculaList.map((matricula, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${matricula.id}`} color="link" size="sm">
                      {matricula.id}
                    </Button>
                  </td>
                  <td>{matricula.id}</td>
                  <td>{matricula.anoLetivo}</td>
                  <td>
                    {matricula.dataInicio ? <TextFormat type="date" value={matricula.dataInicio} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>{matricula.dataFim ? <TextFormat type="date" value={matricula.dataFim} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>
                    {matricula.turmaMatricula ? <Link to={`turma/${matricula.turmaMatricula.id}`}>{matricula.turmaMatricula.id}</Link> : ''}
                  </td>
                  <td>
                    {matricula.alunoMatricula ? <Link to={`aluno/${matricula.alunoMatricula.id}`}>{matricula.alunoMatricula.id}</Link> : ''}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${matricula.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${matricula.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${matricula.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.matricula.home.notFound">No Matriculas found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={matriculaList && matriculaList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ matricula }: IRootState) => ({
  matriculaList: matricula.entities,
  loading: matricula.loading,
  totalItems: matricula.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Matricula);
