// src/main/webapp/app/entities/matricula/matricula.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './matricula.reducer';
import { IMatricula } from 'app/shared/model/matricula.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IMatriculaProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Matricula = (props: IMatriculaProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { matriculaList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="matricula-heading" data-cy="MatriculaHeading">
        <Translate contentKey="escolaOnlineApp.matricula.home.title">Matriculas</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.matricula.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.matricula.home.createLabel">Create new Matricula</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {matriculaList && matriculaList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.matricula.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('anoLetivo')}>
                  <Translate contentKey="escolaOnlineApp.matricula.anoLetivo">Ano Letivo</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataInicio')}>
                  <Translate contentKey="escolaOnlineApp.matricula.dataInicio">Data Inicio</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataFim')}>
                  <Translate contentKey="escolaOnlineApp.matricula.dataFim">Data Fim</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.matricula.turmaMatricula">Turma Matricula</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.matricula.alunoMatricula">Aluno Matricula</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {matriculaList.map((matricula, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${matricula.id}`} color="link" size="sm">
                      {matricula.id}
                    </Button>
                  </td>
                  <td>{matricula.id}</td>
                  <td>{matricula.anoLetivo}</td>
                  <td>
                    {matricula.dataInicio ? <TextFormat type="date" value={matricula.dataInicio} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>{matricula.dataFim ? <TextFormat type="date" value={matricula.dataFim} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>
                    {matricula.turmaMatricula ? <Link to={`turma/${matricula.turmaMatricula.id}`}>{matricula.turmaMatricula.id}</Link> : ''}
                  </td>
                  <td>
                    {matricula.alunoMatricula ? <Link to={`aluno/${matricula.alunoMatricula.id}`}>{matricula.alunoMatricula.id}</Link> : ''}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${matricula.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${matricula.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${matricula.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.matricula.home.notFound">No Matriculas found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={matriculaList && matriculaList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ matricula }: IRootState) => ({
  matriculaList: matricula.entities,
  loading: matricula.loading,
  totalItems: matricula.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Matricula);

// src/main/webapp/app/entities/matricula/matricula.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, ParamMap, Router, Data } from '@angular/router';
import { Subscription, combineLatest } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IMatricula } from 'app/shared/model/matricula.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { MatriculaService } from './matricula.service';
import { MatriculaDeleteDialogComponent } from './matricula-delete-dialog.component';

@Component({
  selector: 'jhi-matricula',
  templateUrl: './matricula.component.html',
})
export class MatriculaComponent implements OnInit, OnDestroy {
  matriculas?: IMatricula[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected matriculaService: MatriculaService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    const pageToLoad: number = page || this.page || 1;

    this.matriculaService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<IMatricula[]>) => this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
    this.registerChangeInMatriculas();
  }

  protected handleNavigation(): void {
    combineLatest(this.activatedRoute.data, this.activatedRoute.queryParamMap, (data: Data, params: ParamMap) => {
      const page = params.get('page');
      const pageNumber = page !== null ? +page : 1;
      const sort = (params.get('sort') ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === 'asc';
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    }).subscribe();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IMatricula): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInMatriculas(): void {
    this.eventSubscriber = this.eventManager.subscribe('matriculaListModification', () => this.loadPage());
  }

  delete(matricula: IMatricula): void {
    const modalRef = this.modalService.open(MatriculaDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.matricula = matricula;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IMatricula[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/matricula'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
        },
      });
    }
    this.matriculas = data || [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="escolaOnlineApp.matricula.home.title">Matriculas</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-matricula" [routerLink]="['/matricula/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="escolaOnlineApp.matricula.home.createLabel">
            Create a new Matricula
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="matriculas?.length === 0">
        <span jhiTranslate="escolaOnlineApp.matricula.home.notFound">No matriculas found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="matriculas && matriculas.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="anoLetivo"><span jhiTranslate="escolaOnlineApp.matricula.anoLetivo">Ano Letivo</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="dataInicio"><span jhiTranslate="escolaOnlineApp.matricula.dataInicio">Data Inicio</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="dataFim"><span jhiTranslate="escolaOnlineApp.matricula.dataFim">Data Fim</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="turmaMatricula.id"><span jhiTranslate="escolaOnlineApp.matricula.turmaMatricula">Turma Matricula</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="alunoMatricula.id"><span jhiTranslate="escolaOnlineApp.matricula.alunoMatricula">Aluno Matricula</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let matricula of matriculas ;trackBy: trackId">
                    <td><a [routerLink]="['/matricula', matricula.id, 'view']">{{ matricula.id }}</a></td>
                    <td>{{ matricula.anoLetivo }}</td>
                    <td>{{ matricula.dataInicio | date:'mediumDate' }}</td>
                    <td>{{ matricula.dataFim | date:'mediumDate' }}</td>
                    <td>
                        <div *ngIf="matricula.turmaMatricula">
                            <a [routerLink]="['/turma', matricula.turmaMatricula?.id, 'view']" >{{ matricula.turmaMatricula?.id }}</a>
                        </div>
                    </td>
                    <td>
                        <div *ngIf="matricula.alunoMatricula">
                            <a [routerLink]="['/aluno', matricula.alunoMatricula?.id, 'view']" >{{ matricula.alunoMatricula?.id }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/matricula', matricula.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/matricula', matricula.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(matricula)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="matriculas && matriculas.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>
