// src/main/webapp/app/entities/matricula/update/matricula-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IMatricula, Matricula } from '../matricula.model';
import { MatriculaService } from '../service/matricula.service';
import { ITurma } from 'app/entities/turma/turma.model';
import { TurmaService } from 'app/entities/turma/service/turma.service';
import { IAluno } from 'app/entities/aluno/aluno.model';
import { AlunoService } from 'app/entities/aluno/service/aluno.service';

@Component({
  selector: 'jhi-matricula-update',
  templateUrl: './matricula-update.component.html',
})
export class MatriculaUpdateComponent implements OnInit {
  isSaving = false;

  turmasSharedCollection: ITurma[] = [];
  alunosSharedCollection: IAluno[] = [];

  editForm = this.fb.group({
    id: [],
    anoLetivo: [],
    dataInicio: [],
    dataFim: [],
    turmaMatricula: [],
    alunoMatricula: [],
  });

  constructor(
    protected matriculaService: MatriculaService,
    protected turmaService: TurmaService,
    protected alunoService: AlunoService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ matricula }) => {
      this.updateForm(matricula);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const matricula = this.createFromForm();
    if (matricula.id !== undefined) {
      this.subscribeToSaveResponse(this.matriculaService.update(matricula));
    } else {
      this.subscribeToSaveResponse(this.matriculaService.create(matricula));
    }
  }

  trackTurmaById(index: number, item: ITurma): number {
    return item.id!;
  }

  trackAlunoById(index: number, item: IAluno): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IMatricula>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(matricula: IMatricula): void {
    this.editForm.patchValue({
      id: matricula.id,
      anoLetivo: matricula.anoLetivo,
      dataInicio: matricula.dataInicio,
      dataFim: matricula.dataFim,
      turmaMatricula: matricula.turmaMatricula,
      alunoMatricula: matricula.alunoMatricula,
    });

    this.turmasSharedCollection = this.turmaService.addTurmaToCollectionIfMissing(this.turmasSharedCollection, matricula.turmaMatricula);
    this.alunosSharedCollection = this.alunoService.addAlunoToCollectionIfMissing(this.alunosSharedCollection, matricula.alunoMatricula);
  }

  protected loadRelationshipsOptions(): void {
    this.turmaService
      .query()
      .pipe(map((res: HttpResponse<ITurma[]>) => res.body ?? []))
      .pipe(map((turmas: ITurma[]) => this.turmaService.addTurmaToCollectionIfMissing(turmas, this.editForm.get('turmaMatricula')!.value)))
      .subscribe((turmas: ITurma[]) => (this.turmasSharedCollection = turmas));

    this.alunoService
      .query()
      .pipe(map((res: HttpResponse<IAluno[]>) => res.body ?? []))
      .pipe(map((alunos: IAluno[]) => this.alunoService.addAlunoToCollectionIfMissing(alunos, this.editForm.get('alunoMatricula')!.value)))
      .subscribe((alunos: IAluno[]) => (this.alunosSharedCollection = alunos));
  }

  protected createFromForm(): IMatricula {
    return {
      ...new Matricula(),
      id: this.editForm.get(['id'])!.value,
      anoLetivo: this.editForm.get(['anoLetivo'])!.value,
      dataInicio: this.editForm.get(['dataInicio'])!.value,
      dataFim: this.editForm.get(['dataFim'])!.value,
      turmaMatricula: this.editForm.get(['turmaMatricula'])!.value,
      alunoMatricula: this.editForm.get(['alunoMatricula'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-matricula-heading" data-cy="MatriculaCreateUpdateHeading" jhiTranslate="escolaOnlineApp.matricula.home.createOrEditLabel">
        Create or edit a Matricula
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.matricula.anoLetivo" for="field_anoLetivo">Ano Letivo</label>
          <input type="number" class="form-control" name="anoLetivo" id="field_anoLetivo" data-cy="anoLetivo" formControlName="anoLetivo" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.matricula.dataInicio" for="field_dataInicio">Data Inicio</label>
          <div class="input-group">
            <input
              id="field_dataInicio"
              data-cy="dataInicio"
              type="text"
              class="form-control"
              name="dataInicio"
              ngbDatepicker
              #dataInicioDp="ngbDatepicker"
              formControlName="dataInicio"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataInicioDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.matricula.dataFim" for="field_dataFim">Data Fim</label>
          <div class="input-group">
            <input
              id="field_dataFim"
              data-cy="dataFim"
              type="text"
              class="form-control"
              name="dataFim"
              ngbDatepicker
              #dataFimDp="ngbDatepicker"
              formControlName="dataFim"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataFimDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.matricula.turmaMatricula" for="field_turmaMatricula"
            >Turma Matricula</label
          >
          <select
            class="form-control"
            id="field_turmaMatricula"
            data-cy="turmaMatricula"
            name="turmaMatricula"
            formControlName="turmaMatricula"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="turmaOption.id === editForm.get('turmaMatricula')!.value?.id ? editForm.get('turmaMatricula')!.value : turmaOption"
              *ngFor="let turmaOption of turmasSharedCollection; trackBy: trackTurmaById"
            >
              {{ turmaOption.id }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.matricula.alunoMatricula" for="field_alunoMatricula"
            >Aluno Matricula</label
          >
          <select
            class="form-control"
            id="field_alunoMatricula"
            data-cy="alunoMatricula"
            name="alunoMatricula"
            formControlName="alunoMatricula"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="alunoOption.id === editForm.get('alunoMatricula')!.value?.id ? editForm.get('alunoMatricula')!.value : alunoOption"
              *ngFor="let alunoOption of alunosSharedCollection; trackBy: trackAlunoById"
            >
              {{ alunoOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/matricula/matricula-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ITurma } from 'app/shared/model/turma.model';
import { getEntities as getTurmas } from 'app/entities/turma/turma.reducer';
import { IAluno } from 'app/shared/model/aluno.model';
import { getEntities as getAlunos } from 'app/entities/aluno/aluno.reducer';
import { getEntity, updateEntity, createEntity, reset } from './matricula.reducer';
import { IMatricula } from 'app/shared/model/matricula.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IMatriculaUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const MatriculaUpdate = (props: IMatriculaUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { matriculaEntity, turmas, alunos, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/matricula' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getTurmas();
    props.getAlunos();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...matriculaEntity,
        ...values,
        turmaMatricula: turmas.find(it => it.id.toString() === values.turmaMatriculaId.toString()),
        alunoMatricula: alunos.find(it => it.id.toString() === values.alunoMatriculaId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.matricula.home.createOrEditLabel" data-cy="MatriculaCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.matricula.home.createOrEditLabel">Create or edit a Matricula</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : matriculaEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="matricula-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="matricula-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="anoLetivoLabel" for="matricula-anoLetivo">
                  <Translate contentKey="escolaOnlineApp.matricula.anoLetivo">Ano Letivo</Translate>
                </Label>
                <AvField id="matricula-anoLetivo" data-cy="anoLetivo" type="string" className="form-control" name="anoLetivo" />
              </AvGroup>
              <AvGroup>
                <Label id="dataInicioLabel" for="matricula-dataInicio">
                  <Translate contentKey="escolaOnlineApp.matricula.dataInicio">Data Inicio</Translate>
                </Label>
                <AvField id="matricula-dataInicio" data-cy="dataInicio" type="date" className="form-control" name="dataInicio" />
              </AvGroup>
              <AvGroup>
                <Label id="dataFimLabel" for="matricula-dataFim">
                  <Translate contentKey="escolaOnlineApp.matricula.dataFim">Data Fim</Translate>
                </Label>
                <AvField id="matricula-dataFim" data-cy="dataFim" type="date" className="form-control" name="dataFim" />
              </AvGroup>
              <AvGroup>
                <Label for="matricula-turmaMatricula">
                  <Translate contentKey="escolaOnlineApp.matricula.turmaMatricula">Turma Matricula</Translate>
                </Label>
                <AvInput
                  id="matricula-turmaMatricula"
                  data-cy="turmaMatricula"
                  type="select"
                  className="form-control"
                  name="turmaMatriculaId"
                >
                  <option value="" key="0" />
                  {turmas
                    ? turmas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="matricula-alunoMatricula">
                  <Translate contentKey="escolaOnlineApp.matricula.alunoMatricula">Aluno Matricula</Translate>
                </Label>
                <AvInput
                  id="matricula-alunoMatricula"
                  data-cy="alunoMatricula"
                  type="select"
                  className="form-control"
                  name="alunoMatriculaId"
                >
                  <option value="" key="0" />
                  {alunos
                    ? alunos.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/matricula" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  turmas: storeState.turma.entities,
  alunos: storeState.aluno.entities,
  matriculaEntity: storeState.matricula.entity,
  loading: storeState.matricula.loading,
  updating: storeState.matricula.updating,
  updateSuccess: storeState.matricula.updateSuccess,
});

const mapDispatchToProps = {
  getTurmas,
  getAlunos,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(MatriculaUpdate);
