// src/main/webapp/app/entities/solicitacao/solicitacao-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { ISolicitacao, Solicitacao } from 'app/shared/model/solicitacao.model';
import { SolicitacaoService } from './solicitacao.service';
import { ITipoSolicitacao } from 'app/shared/model/tipo-solicitacao.model';
import { TipoSolicitacaoService } from 'app/entities/tipo-solicitacao/tipo-solicitacao.service';
import { IAluno } from 'app/shared/model/aluno.model';
import { AlunoService } from 'app/entities/aluno/aluno.service';

type SelectableEntity = ITipoSolicitacao | IAluno;

@Component({
  selector: 'jhi-solicitacao-update',
  templateUrl: './solicitacao-update.component.html',
})
export class SolicitacaoUpdateComponent implements OnInit {
  isSaving = false;
  tiposolicitacaos: ITipoSolicitacao[] = [];
  alunos: IAluno[] = [];
  dataSolicitacaoDp: any;

  editForm = this.fb.group({
    id: [],
    situacaoSolicitacao: [],
    dataSolicitacao: [],
    observacoesSolicitante: [],
    observacoesAtendimento: [],
    tipoSolicitacaoSolicitacao: [],
    alunoSolicitacao: [],
  });

  constructor(
    protected solicitacaoService: SolicitacaoService,
    protected tipoSolicitacaoService: TipoSolicitacaoService,
    protected alunoService: AlunoService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ solicitacao }) => {
      this.updateForm(solicitacao);

      this.tipoSolicitacaoService.query().subscribe((res: HttpResponse<ITipoSolicitacao[]>) => (this.tiposolicitacaos = res.body || []));

      this.alunoService.query().subscribe((res: HttpResponse<IAluno[]>) => (this.alunos = res.body || []));
    });
  }

  updateForm(solicitacao: ISolicitacao): void {
    this.editForm.patchValue({
      id: solicitacao.id,
      situacaoSolicitacao: solicitacao.situacaoSolicitacao,
      dataSolicitacao: solicitacao.dataSolicitacao,
      observacoesSolicitante: solicitacao.observacoesSolicitante,
      observacoesAtendimento: solicitacao.observacoesAtendimento,
      tipoSolicitacaoSolicitacao: solicitacao.tipoSolicitacaoSolicitacao,
      alunoSolicitacao: solicitacao.alunoSolicitacao,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const solicitacao = this.createFromForm();
    if (solicitacao.id !== undefined) {
      this.subscribeToSaveResponse(this.solicitacaoService.update(solicitacao));
    } else {
      this.subscribeToSaveResponse(this.solicitacaoService.create(solicitacao));
    }
  }

  private createFromForm(): ISolicitacao {
    return {
      ...new Solicitacao(),
      id: this.editForm.get(['id'])!.value,
      situacaoSolicitacao: this.editForm.get(['situacaoSolicitacao'])!.value,
      dataSolicitacao: this.editForm.get(['dataSolicitacao'])!.value,
      observacoesSolicitante: this.editForm.get(['observacoesSolicitante'])!.value,
      observacoesAtendimento: this.editForm.get(['observacoesAtendimento'])!.value,
      tipoSolicitacaoSolicitacao: this.editForm.get(['tipoSolicitacaoSolicitacao'])!.value,
      alunoSolicitacao: this.editForm.get(['alunoSolicitacao'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ISolicitacao>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: SelectableEntity): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-solicitacao-heading" jhiTranslate="escolaOnlineApp.solicitacao.home.createOrEditLabel">Create or edit a Solicitacao</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.solicitacao.situacaoSolicitacao" for="field_situacaoSolicitacao">Situacao Solicitacao</label>
                    <select class="form-control" name="situacaoSolicitacao" formControlName="situacaoSolicitacao" id="field_situacaoSolicitacao">
                        <option value="AGUARDANDO">{{ 'escolaOnlineApp.SituacaoSolicitacao.AGUARDANDO' | translate }}</option>
                        <option value="EM_ANDAMENTO">{{ 'escolaOnlineApp.SituacaoSolicitacao.EM_ANDAMENTO' | translate }}</option>
                        <option value="CONCLUIDO">{{ 'escolaOnlineApp.SituacaoSolicitacao.CONCLUIDO' | translate }}</option>
                        <option value="CANCELADO">{{ 'escolaOnlineApp.SituacaoSolicitacao.CANCELADO' | translate }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.solicitacao.dataSolicitacao" for="field_dataSolicitacao">Data Solicitacao</label>
                    <div class="input-group">
                        <input id="field_dataSolicitacao" type="text" class="form-control" name="dataSolicitacao" ngbDatepicker #dataSolicitacaoDp="ngbDatepicker" formControlName="dataSolicitacao"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="dataSolicitacaoDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.solicitacao.observacoesSolicitante" for="field_observacoesSolicitante">Observacoes Solicitante</label>
                    <input type="text" class="form-control" name="observacoesSolicitante" id="field_observacoesSolicitante"
                           formControlName="observacoesSolicitante"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.solicitacao.observacoesAtendimento" for="field_observacoesAtendimento">Observacoes Atendimento</label>
                    <input type="text" class="form-control" name="observacoesAtendimento" id="field_observacoesAtendimento"
                           formControlName="observacoesAtendimento"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.solicitacao.tipoSolicitacaoSolicitacao" for="field_tipoSolicitacaoSolicitacao">Tipo Solicitacao Solicitacao</label>
                    <select class="form-control" id="field_tipoSolicitacaoSolicitacao" name="tipoSolicitacaoSolicitacao" formControlName="tipoSolicitacaoSolicitacao">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="tipoSolicitacaoOption.id === editForm.get('tipoSolicitacaoSolicitacao')!.value?.id ? editForm.get('tipoSolicitacaoSolicitacao')!.value : tipoSolicitacaoOption" *ngFor="let tipoSolicitacaoOption of tiposolicitacaos; trackBy: trackById">{{ tipoSolicitacaoOption.nome }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.solicitacao.alunoSolicitacao" for="field_alunoSolicitacao">Aluno Solicitacao</label>
                    <select class="form-control" id="field_alunoSolicitacao" name="alunoSolicitacao" formControlName="alunoSolicitacao">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="alunoOption.id === editForm.get('alunoSolicitacao')!.value?.id ? editForm.get('alunoSolicitacao')!.value : alunoOption" *ngFor="let alunoOption of alunos; trackBy: trackById">{{ alunoOption.pessoaAluno?.nome }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/solicitacao/solicitacao-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ITipoSolicitacao } from 'app/shared/model/tipo-solicitacao.model';
import { getEntities as getTipoSolicitacaos } from 'app/entities/tipo-solicitacao/tipo-solicitacao.reducer';
import { IAluno } from 'app/shared/model/aluno.model';
import { getEntities as getAlunos } from 'app/entities/aluno/aluno.reducer';
import { getEntity, updateEntity, createEntity, reset } from './solicitacao.reducer';
import { ISolicitacao } from 'app/shared/model/solicitacao.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ISolicitacaoUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SolicitacaoUpdate = (props: ISolicitacaoUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { solicitacaoEntity, tipoSolicitacaos, alunos, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/solicitacao' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getTipoSolicitacaos();
    props.getAlunos();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...solicitacaoEntity,
        ...values,
        tipoSolicitacaoSolicitacao: tipoSolicitacaos.find(it => it.id.toString() === values.tipoSolicitacaoSolicitacaoId.toString()),
        alunoSolicitacao: alunos.find(it => it.id.toString() === values.alunoSolicitacaoId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.solicitacao.home.createOrEditLabel" data-cy="SolicitacaoCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.solicitacao.home.createOrEditLabel">Create or edit a Solicitacao</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : solicitacaoEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="solicitacao-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="solicitacao-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="situacaoSolicitacaoLabel" for="solicitacao-situacaoSolicitacao">
                  <Translate contentKey="escolaOnlineApp.solicitacao.situacaoSolicitacao">Situacao Solicitacao</Translate>
                </Label>
                <AvInput
                  id="solicitacao-situacaoSolicitacao"
                  data-cy="situacaoSolicitacao"
                  type="select"
                  className="form-control"
                  name="situacaoSolicitacao"
                  value={(!isNew && solicitacaoEntity.situacaoSolicitacao) || 'AGUARDANDO'}
                >
                  <option value="AGUARDANDO">{translate('escolaOnlineApp.SituacaoSolicitacao.AGUARDANDO')}</option>
                  <option value="EM_ANDAMENTO">{translate('escolaOnlineApp.SituacaoSolicitacao.EM_ANDAMENTO')}</option>
                  <option value="CONCLUIDO">{translate('escolaOnlineApp.SituacaoSolicitacao.CONCLUIDO')}</option>
                  <option value="CANCELADO">{translate('escolaOnlineApp.SituacaoSolicitacao.CANCELADO')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="dataSolicitacaoLabel" for="solicitacao-dataSolicitacao">
                  <Translate contentKey="escolaOnlineApp.solicitacao.dataSolicitacao">Data Solicitacao</Translate>
                </Label>
                <AvField
                  id="solicitacao-dataSolicitacao"
                  data-cy="dataSolicitacao"
                  type="date"
                  className="form-control"
                  name="dataSolicitacao"
                />
              </AvGroup>
              <AvGroup>
                <Label id="observacoesSolicitanteLabel" for="solicitacao-observacoesSolicitante">
                  <Translate contentKey="escolaOnlineApp.solicitacao.observacoesSolicitante">Observacoes Solicitante</Translate>
                </Label>
                <AvField
                  id="solicitacao-observacoesSolicitante"
                  data-cy="observacoesSolicitante"
                  type="text"
                  name="observacoesSolicitante"
                />
              </AvGroup>
              <AvGroup>
                <Label id="observacoesAtendimentoLabel" for="solicitacao-observacoesAtendimento">
                  <Translate contentKey="escolaOnlineApp.solicitacao.observacoesAtendimento">Observacoes Atendimento</Translate>
                </Label>
                <AvField
                  id="solicitacao-observacoesAtendimento"
                  data-cy="observacoesAtendimento"
                  type="text"
                  name="observacoesAtendimento"
                />
              </AvGroup>
              <AvGroup>
                <Label for="solicitacao-tipoSolicitacaoSolicitacao">
                  <Translate contentKey="escolaOnlineApp.solicitacao.tipoSolicitacaoSolicitacao">Tipo Solicitacao Solicitacao</Translate>
                </Label>
                <AvInput
                  id="solicitacao-tipoSolicitacaoSolicitacao"
                  data-cy="tipoSolicitacaoSolicitacao"
                  type="select"
                  className="form-control"
                  name="tipoSolicitacaoSolicitacaoId"
                >
                  <option value="" key="0" />
                  {tipoSolicitacaos
                    ? tipoSolicitacaos.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="solicitacao-alunoSolicitacao">
                  <Translate contentKey="escolaOnlineApp.solicitacao.alunoSolicitacao">Aluno Solicitacao</Translate>
                </Label>
                <AvInput
                  id="solicitacao-alunoSolicitacao"
                  data-cy="alunoSolicitacao"
                  type="select"
                  className="form-control"
                  name="alunoSolicitacaoId"
                >
                  <option value="" key="0" />
                  {alunos
                    ? alunos.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/solicitacao" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  tipoSolicitacaos: storeState.tipoSolicitacao.entities,
  alunos: storeState.aluno.entities,
  solicitacaoEntity: storeState.solicitacao.entity,
  loading: storeState.solicitacao.loading,
  updating: storeState.solicitacao.updating,
  updateSuccess: storeState.solicitacao.updateSuccess,
});

const mapDispatchToProps = {
  getTipoSolicitacaos,
  getAlunos,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SolicitacaoUpdate);
