// src/main/webapp/app/entities/solicitacao/detail/solicitacao-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ISolicitacao } from '../solicitacao.model';

@Component({
  selector: 'jhi-solicitacao-detail',
  templateUrl: './solicitacao-detail.component.html',
})
export class SolicitacaoDetailComponent implements OnInit {
  solicitacao: ISolicitacao | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ solicitacao }) => {
      this.solicitacao = solicitacao;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="solicitacao">
      <h2 data-cy="solicitacaoDetailsHeading"><span jhiTranslate="escolaOnlineApp.solicitacao.detail.title">Solicitacao</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ solicitacao.id }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.solicitacao.situacaoSolicitacao">Situacao Solicitacao</span></dt>
        <dd>
          <span jhiTranslate="{{ 'escolaOnlineApp.SituacaoSolicitacao.' + solicitacao.situacaoSolicitacao }}">{{
            solicitacao.situacaoSolicitacao
          }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.solicitacao.dataSolicitacao">Data Solicitacao</span></dt>
        <dd>
          <span>{{ solicitacao.dataSolicitacao | formatMediumDate }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.solicitacao.observacoesSolicitante">Observacoes Solicitante</span></dt>
        <dd>
          <span>{{ solicitacao.observacoesSolicitante }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.solicitacao.observacoesAtendimento">Observacoes Atendimento</span></dt>
        <dd>
          <span>{{ solicitacao.observacoesAtendimento }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.solicitacao.tipoSolicitacaoSolicitacao">Tipo Solicitacao Solicitacao</span></dt>
        <dd>
          <div *ngIf="solicitacao.tipoSolicitacaoSolicitacao">
            <a [routerLink]="['/tipo-solicitacao', solicitacao.tipoSolicitacaoSolicitacao?.id, 'view']">{{
              solicitacao.tipoSolicitacaoSolicitacao?.id
            }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.solicitacao.alunoSolicitacao">Aluno Solicitacao</span></dt>
        <dd>
          <div *ngIf="solicitacao.alunoSolicitacao">
            <a [routerLink]="['/aluno', solicitacao.alunoSolicitacao?.id, 'view']">{{ solicitacao.alunoSolicitacao?.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/solicitacao', solicitacao.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/solicitacao/solicitacao-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './solicitacao.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ISolicitacaoDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SolicitacaoDetail = (props: ISolicitacaoDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { solicitacaoEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="solicitacaoDetailsHeading">
          <Translate contentKey="escolaOnlineApp.solicitacao.detail.title">Solicitacao</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{solicitacaoEntity.id}</dd>
          <dt>
            <span id="situacaoSolicitacao">
              <Translate contentKey="escolaOnlineApp.solicitacao.situacaoSolicitacao">Situacao Solicitacao</Translate>
            </span>
          </dt>
          <dd>{solicitacaoEntity.situacaoSolicitacao}</dd>
          <dt>
            <span id="dataSolicitacao">
              <Translate contentKey="escolaOnlineApp.solicitacao.dataSolicitacao">Data Solicitacao</Translate>
            </span>
          </dt>
          <dd>
            {solicitacaoEntity.dataSolicitacao ? (
              <TextFormat value={solicitacaoEntity.dataSolicitacao} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <span id="observacoesSolicitante">
              <Translate contentKey="escolaOnlineApp.solicitacao.observacoesSolicitante">Observacoes Solicitante</Translate>
            </span>
          </dt>
          <dd>{solicitacaoEntity.observacoesSolicitante}</dd>
          <dt>
            <span id="observacoesAtendimento">
              <Translate contentKey="escolaOnlineApp.solicitacao.observacoesAtendimento">Observacoes Atendimento</Translate>
            </span>
          </dt>
          <dd>{solicitacaoEntity.observacoesAtendimento}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.solicitacao.tipoSolicitacaoSolicitacao">Tipo Solicitacao Solicitacao</Translate>
          </dt>
          <dd>{solicitacaoEntity.tipoSolicitacaoSolicitacao ? solicitacaoEntity.tipoSolicitacaoSolicitacao.id : ''}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.solicitacao.alunoSolicitacao">Aluno Solicitacao</Translate>
          </dt>
          <dd>{solicitacaoEntity.alunoSolicitacao ? solicitacaoEntity.alunoSolicitacao.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/solicitacao" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/solicitacao/${solicitacaoEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ solicitacao }: IRootState) => ({
  solicitacaoEntity: solicitacao.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SolicitacaoDetail);
