// src/main/webapp/app/entities/debito/debito-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IAluno } from 'app/shared/model/aluno.model';
import { getEntities as getAlunos } from 'app/entities/aluno/aluno.reducer';
import { getEntity, updateEntity, createEntity, reset } from './debito.reducer';
import { IDebito } from 'app/shared/model/debito.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IDebitoUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const DebitoUpdate = (props: IDebitoUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { debitoEntity, alunos, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/debito' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getAlunos();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...debitoEntity,
        ...values,
        alunoDebito: alunos.find(it => it.id.toString() === values.alunoDebitoId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.debito.home.createOrEditLabel" data-cy="DebitoCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.debito.home.createOrEditLabel">Create or edit a Debito</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : debitoEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="debito-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="debito-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="tipoDebitoLabel" for="debito-tipoDebito">
                  <Translate contentKey="escolaOnlineApp.debito.tipoDebito">Tipo Debito</Translate>
                </Label>
                <AvInput
                  id="debito-tipoDebito"
                  data-cy="tipoDebito"
                  type="select"
                  className="form-control"
                  name="tipoDebito"
                  value={(!isNew && debitoEntity.tipoDebito) || 'MENSALIDADE'}
                >
                  <option value="MENSALIDADE">{translate('escolaOnlineApp.TipoDebito.MENSALIDADE')}</option>
                  <option value="TAXA_MATERIAL">{translate('escolaOnlineApp.TipoDebito.TAXA_MATERIAL')}</option>
                  <option value="TAXA_MATRICULA">{translate('escolaOnlineApp.TipoDebito.TAXA_MATRICULA')}</option>
                  <option value="TAXA_DOCUMENTO">{translate('escolaOnlineApp.TipoDebito.TAXA_DOCUMENTO')}</option>
                  <option value="UNIFORME">{translate('escolaOnlineApp.TipoDebito.UNIFORME')}</option>
                  <option value="LIVRO">{translate('escolaOnlineApp.TipoDebito.LIVRO')}</option>
                  <option value="CANTINA">{translate('escolaOnlineApp.TipoDebito.CANTINA')}</option>
                  <option value="EVENTO">{translate('escolaOnlineApp.TipoDebito.EVENTO')}</option>
                  <option value="OUTROS">{translate('escolaOnlineApp.TipoDebito.OUTROS')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="situacaoDebitoLabel" for="debito-situacaoDebito">
                  <Translate contentKey="escolaOnlineApp.debito.situacaoDebito">Situacao Debito</Translate>
                </Label>
                <AvInput
                  id="debito-situacaoDebito"
                  data-cy="situacaoDebito"
                  type="select"
                  className="form-control"
                  name="situacaoDebito"
                  value={(!isNew && debitoEntity.situacaoDebito) || 'NAO_PAGO'}
                >
                  <option value="NAO_PAGO">{translate('escolaOnlineApp.SituacaoDebito.NAO_PAGO')}</option>
                  <option value="PAGO_PARCIAL">{translate('escolaOnlineApp.SituacaoDebito.PAGO_PARCIAL')}</option>
                  <option value="PAGO">{translate('escolaOnlineApp.SituacaoDebito.PAGO')}</option>
                  <option value="CANCELADO">{translate('escolaOnlineApp.SituacaoDebito.CANCELADO')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="dataVencimentoLabel" for="debito-dataVencimento">
                  <Translate contentKey="escolaOnlineApp.debito.dataVencimento">Data Vencimento</Translate>
                </Label>
                <AvField id="debito-dataVencimento" data-cy="dataVencimento" type="date" className="form-control" name="dataVencimento" />
              </AvGroup>
              <AvGroup>
                <Label id="dataPagamentoLabel" for="debito-dataPagamento">
                  <Translate contentKey="escolaOnlineApp.debito.dataPagamento">Data Pagamento</Translate>
                </Label>
                <AvField id="debito-dataPagamento" data-cy="dataPagamento" type="date" className="form-control" name="dataPagamento" />
              </AvGroup>
              <AvGroup>
                <Label id="valorOriginalLabel" for="debito-valorOriginal">
                  <Translate contentKey="escolaOnlineApp.debito.valorOriginal">Valor Original</Translate>
                </Label>
                <AvField id="debito-valorOriginal" data-cy="valorOriginal" type="text" name="valorOriginal" />
              </AvGroup>
              <AvGroup>
                <Label id="totalPagoLabel" for="debito-totalPago">
                  <Translate contentKey="escolaOnlineApp.debito.totalPago">Total Pago</Translate>
                </Label>
                <AvField id="debito-totalPago" data-cy="totalPago" type="text" name="totalPago" />
              </AvGroup>
              <AvGroup>
                <Label id="totalDescontoLabel" for="debito-totalDesconto">
                  <Translate contentKey="escolaOnlineApp.debito.totalDesconto">Total Desconto</Translate>
                </Label>
                <AvField id="debito-totalDesconto" data-cy="totalDesconto" type="text" name="totalDesconto" />
              </AvGroup>
              <AvGroup>
                <Label id="totalDevidoLabel" for="debito-totalDevido">
                  <Translate contentKey="escolaOnlineApp.debito.totalDevido">Total Devido</Translate>
                </Label>
                <AvField id="debito-totalDevido" data-cy="totalDevido" type="text" name="totalDevido" />
              </AvGroup>
              <AvGroup>
                <Label id="observacoesLabel" for="debito-observacoes">
                  <Translate contentKey="escolaOnlineApp.debito.observacoes">Observacoes</Translate>
                </Label>
                <AvField id="debito-observacoes" data-cy="observacoes" type="text" name="observacoes" />
              </AvGroup>
              <AvGroup>
                <Label for="debito-alunoDebito">
                  <Translate contentKey="escolaOnlineApp.debito.alunoDebito">Aluno Debito</Translate>
                </Label>
                <AvInput id="debito-alunoDebito" data-cy="alunoDebito" type="select" className="form-control" name="alunoDebitoId">
                  <option value="" key="0" />
                  {alunos
                    ? alunos.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/debito" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  alunos: storeState.aluno.entities,
  debitoEntity: storeState.debito.entity,
  loading: storeState.debito.loading,
  updating: storeState.debito.updating,
  updateSuccess: storeState.debito.updateSuccess,
});

const mapDispatchToProps = {
  getAlunos,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(DebitoUpdate);

// src/main/webapp/app/entities/debito/update/debito-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IDebito, Debito } from '../debito.model';
import { DebitoService } from '../service/debito.service';
import { IAluno } from 'app/entities/aluno/aluno.model';
import { AlunoService } from 'app/entities/aluno/service/aluno.service';

@Component({
  selector: 'jhi-debito-update',
  templateUrl: './debito-update.component.html',
})
export class DebitoUpdateComponent implements OnInit {
  isSaving = false;

  alunosSharedCollection: IAluno[] = [];

  editForm = this.fb.group({
    id: [],
    tipoDebito: [],
    situacaoDebito: [],
    dataVencimento: [],
    dataPagamento: [],
    valorOriginal: [],
    totalPago: [],
    totalDesconto: [],
    totalDevido: [],
    observacoes: [],
    alunoDebito: [],
  });

  constructor(
    protected debitoService: DebitoService,
    protected alunoService: AlunoService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ debito }) => {
      this.updateForm(debito);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const debito = this.createFromForm();
    if (debito.id !== undefined) {
      this.subscribeToSaveResponse(this.debitoService.update(debito));
    } else {
      this.subscribeToSaveResponse(this.debitoService.create(debito));
    }
  }

  trackAlunoById(index: number, item: IAluno): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IDebito>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(debito: IDebito): void {
    this.editForm.patchValue({
      id: debito.id,
      tipoDebito: debito.tipoDebito,
      situacaoDebito: debito.situacaoDebito,
      dataVencimento: debito.dataVencimento,
      dataPagamento: debito.dataPagamento,
      valorOriginal: debito.valorOriginal,
      totalPago: debito.totalPago,
      totalDesconto: debito.totalDesconto,
      totalDevido: debito.totalDevido,
      observacoes: debito.observacoes,
      alunoDebito: debito.alunoDebito,
    });

    this.alunosSharedCollection = this.alunoService.addAlunoToCollectionIfMissing(this.alunosSharedCollection, debito.alunoDebito);
  }

  protected loadRelationshipsOptions(): void {
    this.alunoService
      .query()
      .pipe(map((res: HttpResponse<IAluno[]>) => res.body ?? []))
      .pipe(map((alunos: IAluno[]) => this.alunoService.addAlunoToCollectionIfMissing(alunos, this.editForm.get('alunoDebito')!.value)))
      .subscribe((alunos: IAluno[]) => (this.alunosSharedCollection = alunos));
  }

  protected createFromForm(): IDebito {
    return {
      ...new Debito(),
      id: this.editForm.get(['id'])!.value,
      tipoDebito: this.editForm.get(['tipoDebito'])!.value,
      situacaoDebito: this.editForm.get(['situacaoDebito'])!.value,
      dataVencimento: this.editForm.get(['dataVencimento'])!.value,
      dataPagamento: this.editForm.get(['dataPagamento'])!.value,
      valorOriginal: this.editForm.get(['valorOriginal'])!.value,
      totalPago: this.editForm.get(['totalPago'])!.value,
      totalDesconto: this.editForm.get(['totalDesconto'])!.value,
      totalDevido: this.editForm.get(['totalDevido'])!.value,
      observacoes: this.editForm.get(['observacoes'])!.value,
      alunoDebito: this.editForm.get(['alunoDebito'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-debito-heading" data-cy="DebitoCreateUpdateHeading" jhiTranslate="escolaOnlineApp.debito.home.createOrEditLabel">
        Create or edit a Debito
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.tipoDebito" for="field_tipoDebito">Tipo Debito</label>
          <select class="form-control" name="tipoDebito" formControlName="tipoDebito" id="field_tipoDebito" data-cy="tipoDebito">
            <option [ngValue]="null">{{ 'escolaOnlineApp.TipoDebito.null' | translate }}</option>
            <option value="MENSALIDADE">{{ 'escolaOnlineApp.TipoDebito.MENSALIDADE' | translate }}</option>
            <option value="TAXA_MATERIAL">{{ 'escolaOnlineApp.TipoDebito.TAXA_MATERIAL' | translate }}</option>
            <option value="TAXA_MATRICULA">{{ 'escolaOnlineApp.TipoDebito.TAXA_MATRICULA' | translate }}</option>
            <option value="TAXA_DOCUMENTO">{{ 'escolaOnlineApp.TipoDebito.TAXA_DOCUMENTO' | translate }}</option>
            <option value="UNIFORME">{{ 'escolaOnlineApp.TipoDebito.UNIFORME' | translate }}</option>
            <option value="LIVRO">{{ 'escolaOnlineApp.TipoDebito.LIVRO' | translate }}</option>
            <option value="CANTINA">{{ 'escolaOnlineApp.TipoDebito.CANTINA' | translate }}</option>
            <option value="EVENTO">{{ 'escolaOnlineApp.TipoDebito.EVENTO' | translate }}</option>
            <option value="OUTROS">{{ 'escolaOnlineApp.TipoDebito.OUTROS' | translate }}</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.situacaoDebito" for="field_situacaoDebito"
            >Situacao Debito</label
          >
          <select
            class="form-control"
            name="situacaoDebito"
            formControlName="situacaoDebito"
            id="field_situacaoDebito"
            data-cy="situacaoDebito"
          >
            <option [ngValue]="null">{{ 'escolaOnlineApp.SituacaoDebito.null' | translate }}</option>
            <option value="NAO_PAGO">{{ 'escolaOnlineApp.SituacaoDebito.NAO_PAGO' | translate }}</option>
            <option value="PAGO_PARCIAL">{{ 'escolaOnlineApp.SituacaoDebito.PAGO_PARCIAL' | translate }}</option>
            <option value="PAGO">{{ 'escolaOnlineApp.SituacaoDebito.PAGO' | translate }}</option>
            <option value="CANCELADO">{{ 'escolaOnlineApp.SituacaoDebito.CANCELADO' | translate }}</option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.dataVencimento" for="field_dataVencimento"
            >Data Vencimento</label
          >
          <div class="input-group">
            <input
              id="field_dataVencimento"
              data-cy="dataVencimento"
              type="text"
              class="form-control"
              name="dataVencimento"
              ngbDatepicker
              #dataVencimentoDp="ngbDatepicker"
              formControlName="dataVencimento"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataVencimentoDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.dataPagamento" for="field_dataPagamento"
            >Data Pagamento</label
          >
          <div class="input-group">
            <input
              id="field_dataPagamento"
              data-cy="dataPagamento"
              type="text"
              class="form-control"
              name="dataPagamento"
              ngbDatepicker
              #dataPagamentoDp="ngbDatepicker"
              formControlName="dataPagamento"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataPagamentoDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.valorOriginal" for="field_valorOriginal"
            >Valor Original</label
          >
          <input
            type="number"
            class="form-control"
            name="valorOriginal"
            id="field_valorOriginal"
            data-cy="valorOriginal"
            formControlName="valorOriginal"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.totalPago" for="field_totalPago">Total Pago</label>
          <input type="number" class="form-control" name="totalPago" id="field_totalPago" data-cy="totalPago" formControlName="totalPago" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.totalDesconto" for="field_totalDesconto"
            >Total Desconto</label
          >
          <input
            type="number"
            class="form-control"
            name="totalDesconto"
            id="field_totalDesconto"
            data-cy="totalDesconto"
            formControlName="totalDesconto"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.totalDevido" for="field_totalDevido">Total Devido</label>
          <input
            type="number"
            class="form-control"
            name="totalDevido"
            id="field_totalDevido"
            data-cy="totalDevido"
            formControlName="totalDevido"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.observacoes" for="field_observacoes">Observacoes</label>
          <input
            type="text"
            class="form-control"
            name="observacoes"
            id="field_observacoes"
            data-cy="observacoes"
            formControlName="observacoes"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.debito.alunoDebito" for="field_alunoDebito">Aluno Debito</label>
          <select class="form-control" id="field_alunoDebito" data-cy="alunoDebito" name="alunoDebito" formControlName="alunoDebito">
            <option [ngValue]="null"></option>
            <option
              [ngValue]="alunoOption.id === editForm.get('alunoDebito')!.value?.id ? editForm.get('alunoDebito')!.value : alunoOption"
              *ngFor="let alunoOption of alunosSharedCollection; trackBy: trackAlunoById"
            >
              {{ alunoOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
