// src/main/webapp/app/entities/historico-debito/historico-debito-delete-dialog.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { RouteComponentProps } from 'react-router-dom';
import { Modal, ModalHeader, ModalBody, ModalFooter, Button } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity, deleteEntity } from './historico-debito.reducer';

export interface IHistoricoDebitoDeleteDialogProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const HistoricoDebitoDeleteDialog = (props: IHistoricoDebitoDeleteDialogProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const handleClose = () => {
    props.history.push('/historico-debito' + props.location.search);
  };

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const confirmDelete = () => {
    props.deleteEntity(props.historicoDebitoEntity.id);
  };

  const { historicoDebitoEntity } = props;
  return (
    <Modal isOpen toggle={handleClose}>
      <ModalHeader toggle={handleClose} data-cy="historicoDebitoDeleteDialogHeading">
        <Translate contentKey="entity.delete.title">Confirm delete operation</Translate>
      </ModalHeader>
      <ModalBody id="escolaOnlineApp.historicoDebito.delete.question">
        <Translate contentKey="escolaOnlineApp.historicoDebito.delete.question" interpolate={{ id: historicoDebitoEntity.id }}>
          Are you sure you want to delete this HistoricoDebito?
        </Translate>
      </ModalBody>
      <ModalFooter>
        <Button color="secondary" onClick={handleClose}>
          <FontAwesomeIcon icon="ban" />
          &nbsp;
          <Translate contentKey="entity.action.cancel">Cancel</Translate>
        </Button>
        <Button id="jhi-confirm-delete-historicoDebito" data-cy="entityConfirmDeleteButton" color="danger" onClick={confirmDelete}>
          <FontAwesomeIcon icon="trash" />
          &nbsp;
          <Translate contentKey="entity.action.delete">Delete</Translate>
        </Button>
      </ModalFooter>
    </Modal>
  );
};

const mapStateToProps = ({ historicoDebito }: IRootState) => ({
  historicoDebitoEntity: historicoDebito.entity,
  updateSuccess: historicoDebito.updateSuccess,
});

const mapDispatchToProps = { getEntity, deleteEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(HistoricoDebitoDeleteDialog);

// src/main/webapp/app/entities/historico-debito/historico-debito-delete-dialog.component.ts
import { Component } from '@angular/core';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { JhiEventManager } from 'ng-jhipster';

import { IHistoricoDebito } from 'app/shared/model/historico-debito.model';
import { HistoricoDebitoService } from './historico-debito.service';

@Component({
  templateUrl: './historico-debito-delete-dialog.component.html',
})
export class HistoricoDebitoDeleteDialogComponent {
  historicoDebito?: IHistoricoDebito;

  constructor(
    protected historicoDebitoService: HistoricoDebitoService,
    public activeModal: NgbActiveModal,
    protected eventManager: JhiEventManager
  ) {}

  cancel(): void {
    this.activeModal.dismiss();
  }

  confirmDelete(id: number): void {
    this.historicoDebitoService.delete(id).subscribe(() => {
      this.eventManager.broadcast('historicoDebitoListModification');
      this.activeModal.close();
    });
  }
}

<form *ngIf="historicoDebito" name="deleteForm" (ngSubmit)="confirmDelete(historicoDebito?.id!)">
    <div class="modal-header">
        <h4 class="modal-title" jhiTranslate="entity.delete.title">Confirm delete operation</h4>

        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"
                (click)="cancel()">&times;</button>
    </div>

    <div class="modal-body">
        <jhi-alert-error></jhi-alert-error>

        <p id="jhi-delete-historicoDebito-heading" jhiTranslate="escolaOnlineApp.historicoDebito.delete.question" [translateValues]="{ id: historicoDebito.id }">Are you sure you want to delete this Historico Debito?</p>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" (click)="cancel()">
            <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button id="jhi-confirm-delete-historicoDebito" type="submit" class="btn btn-danger">
            <fa-icon icon="times"></fa-icon>&nbsp;<span jhiTranslate="entity.action.delete">Delete</span>
        </button>
    </div>
</form>
