// src/main/webapp/app/entities/historico-debito/historico-debito.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './historico-debito.reducer';
import { IHistoricoDebito } from 'app/shared/model/historico-debito.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IHistoricoDebitoProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const HistoricoDebito = (props: IHistoricoDebitoProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { historicoDebitoList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="historico-debito-heading" data-cy="HistoricoDebitoHeading">
        <Translate contentKey="escolaOnlineApp.historicoDebito.home.title">Historico Debitos</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.historicoDebito.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.historicoDebito.home.createLabel">Create new Historico Debito</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {historicoDebitoList && historicoDebitoList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataLancamento')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.dataLancamento">Data Lancamento</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('situacaoDebito')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.situacaoDebito">Situacao Debito</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataVencimento')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.dataVencimento">Data Vencimento</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataPagamento')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.dataPagamento">Data Pagamento</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('valorOriginal')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.valorOriginal">Valor Original</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('totalPago')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.totalPago">Total Pago</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('totalDesconto')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.totalDesconto">Total Desconto</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('totalDevido')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.totalDevido">Total Devido</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoes')}>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.observacoes">Observacoes</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.debitoHistoricoDebito">Debito Historico Debito</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.historicoDebito.detalheUsuarioLancamento">Detalhe Usuario Lancamento</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {historicoDebitoList.map((historicoDebito, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${historicoDebito.id}`} color="link" size="sm">
                      {historicoDebito.id}
                    </Button>
                  </td>
                  <td>{historicoDebito.id}</td>
                  <td>
                    {historicoDebito.dataLancamento ? (
                      <TextFormat type="date" value={historicoDebito.dataLancamento} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td>
                    <Translate contentKey={`escolaOnlineApp.SituacaoDebito.${historicoDebito.situacaoDebito}`} />
                  </td>
                  <td>
                    {historicoDebito.dataVencimento ? (
                      <TextFormat type="date" value={historicoDebito.dataVencimento} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td>
                    {historicoDebito.dataPagamento ? (
                      <TextFormat type="date" value={historicoDebito.dataPagamento} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td>{historicoDebito.valorOriginal}</td>
                  <td>{historicoDebito.totalPago}</td>
                  <td>{historicoDebito.totalDesconto}</td>
                  <td>{historicoDebito.totalDevido}</td>
                  <td>{historicoDebito.observacoes}</td>
                  <td>
                    {historicoDebito.debitoHistoricoDebito ? (
                      <Link to={`debito/${historicoDebito.debitoHistoricoDebito.id}`}>{historicoDebito.debitoHistoricoDebito.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {historicoDebito.detalheUsuarioLancamento ? (
                      <Link to={`detalhe-usuario/${historicoDebito.detalheUsuarioLancamento.id}`}>
                        {historicoDebito.detalheUsuarioLancamento.id}
                      </Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${historicoDebito.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${historicoDebito.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${historicoDebito.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.historicoDebito.home.notFound">No Historico Debitos found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={historicoDebitoList && historicoDebitoList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ historicoDebito }: IRootState) => ({
  historicoDebitoList: historicoDebito.entities,
  loading: historicoDebito.loading,
  totalItems: historicoDebito.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(HistoricoDebito);

// src/main/webapp/app/entities/historico-debito/historico-debito.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, ParamMap, Router, Data } from '@angular/router';
import { Subscription, combineLatest } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IHistoricoDebito } from 'app/shared/model/historico-debito.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { HistoricoDebitoService } from './historico-debito.service';
import { HistoricoDebitoDeleteDialogComponent } from './historico-debito-delete-dialog.component';

@Component({
  selector: 'jhi-historico-debito',
  templateUrl: './historico-debito.component.html',
})
export class HistoricoDebitoComponent implements OnInit, OnDestroy {
  historicoDebitos?: IHistoricoDebito[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected historicoDebitoService: HistoricoDebitoService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    const pageToLoad: number = page || this.page || 1;

    this.historicoDebitoService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<IHistoricoDebito[]>) => this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
    this.registerChangeInHistoricoDebitos();
  }

  protected handleNavigation(): void {
    combineLatest(this.activatedRoute.data, this.activatedRoute.queryParamMap, (data: Data, params: ParamMap) => {
      const page = params.get('page');
      const pageNumber = page !== null ? +page : 1;
      const sort = (params.get('sort') ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === 'asc';
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    }).subscribe();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IHistoricoDebito): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInHistoricoDebitos(): void {
    this.eventSubscriber = this.eventManager.subscribe('historicoDebitoListModification', () => this.loadPage());
  }

  delete(historicoDebito: IHistoricoDebito): void {
    const modalRef = this.modalService.open(HistoricoDebitoDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.historicoDebito = historicoDebito;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IHistoricoDebito[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/historico-debito'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
        },
      });
    }
    this.historicoDebitos = data || [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="escolaOnlineApp.historicoDebito.home.title">Historico Debitos</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-historico-debito" [routerLink]="['/historico-debito/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="escolaOnlineApp.historicoDebito.home.createLabel">
            Create a new Historico Debito
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="historicoDebitos?.length === 0">
        <span jhiTranslate="escolaOnlineApp.historicoDebito.home.notFound">No historicoDebitos found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="historicoDebitos && historicoDebitos.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="dataLancamento"><span jhiTranslate="escolaOnlineApp.historicoDebito.dataLancamento">Data Lancamento</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="situacaoDebito"><span jhiTranslate="escolaOnlineApp.historicoDebito.situacaoDebito">Situacao Debito</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="dataVencimento"><span jhiTranslate="escolaOnlineApp.historicoDebito.dataVencimento">Data Vencimento</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="dataPagamento"><span jhiTranslate="escolaOnlineApp.historicoDebito.dataPagamento">Data Pagamento</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="valorOriginal"><span jhiTranslate="escolaOnlineApp.historicoDebito.valorOriginal">Valor Original</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="totalPago"><span jhiTranslate="escolaOnlineApp.historicoDebito.totalPago">Total Pago</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="totalDesconto"><span jhiTranslate="escolaOnlineApp.historicoDebito.totalDesconto">Total Desconto</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="totalDevido"><span jhiTranslate="escolaOnlineApp.historicoDebito.totalDevido">Total Devido</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="observacoes"><span jhiTranslate="escolaOnlineApp.historicoDebito.observacoes">Observacoes</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="debitoHistoricoDebito.id"><span jhiTranslate="escolaOnlineApp.historicoDebito.debitoHistoricoDebito">Debito Historico Debito</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="detalheUsuarioLancamento.id"><span jhiTranslate="escolaOnlineApp.historicoDebito.detalheUsuarioLancamento">Detalhe Usuario Lancamento</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let historicoDebito of historicoDebitos ;trackBy: trackId">
                    <td><a [routerLink]="['/historico-debito', historicoDebito.id, 'view']">{{ historicoDebito.id }}</a></td>
                    <td>{{ historicoDebito.dataLancamento | date:'mediumDate' }}</td>
                    <td jhiTranslate="{{ 'escolaOnlineApp.SituacaoDebito.' + historicoDebito.situacaoDebito }}">{{ historicoDebito.situacaoDebito }}</td>
                    <td>{{ historicoDebito.dataVencimento | date:'mediumDate' }}</td>
                    <td>{{ historicoDebito.dataPagamento | date:'mediumDate' }}</td>
                    <td>{{ historicoDebito.valorOriginal }}</td>
                    <td>{{ historicoDebito.totalPago }}</td>
                    <td>{{ historicoDebito.totalDesconto }}</td>
                    <td>{{ historicoDebito.totalDevido }}</td>
                    <td>{{ historicoDebito.observacoes }}</td>
                    <td>
                        <div *ngIf="historicoDebito.debitoHistoricoDebito">
                            <a [routerLink]="['/debito', historicoDebito.debitoHistoricoDebito?.id, 'view']" >{{ historicoDebito.debitoHistoricoDebito?.id }}</a>
                        </div>
                    </td>
                    <td>
                        <div *ngIf="historicoDebito.detalheUsuarioLancamento">
                            <a [routerLink]="['/detalhe-usuario', historicoDebito.detalheUsuarioLancamento?.id, 'view']" >{{ historicoDebito.detalheUsuarioLancamento?.id }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/historico-debito', historicoDebito.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/historico-debito', historicoDebito.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(historicoDebito)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="historicoDebitos && historicoDebitos.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>
