// src/main/webapp/app/entities/aluno/aluno-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IPessoa } from 'app/shared/model/pessoa.model';
import { getEntities as getPessoas } from 'app/entities/pessoa/pessoa.reducer';
import { IEscola } from 'app/shared/model/escola.model';
import { getEntities as getEscolas } from 'app/entities/escola/escola.reducer';
import { getEntity, updateEntity, createEntity, reset } from './aluno.reducer';
import { IAluno } from 'app/shared/model/aluno.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IAlunoUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const AlunoUpdate = (props: IAlunoUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { alunoEntity, pessoas, escolas, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/aluno' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getPessoas();
    props.getEscolas();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...alunoEntity,
        ...values,
        pessoaAluno: pessoas.find(it => it.id.toString() === values.pessoaAlunoId.toString()),
        escolaAluno: escolas.find(it => it.id.toString() === values.escolaAlunoId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.aluno.home.createOrEditLabel" data-cy="AlunoCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.aluno.home.createOrEditLabel">Create or edit a Aluno</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : alunoEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="aluno-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="aluno-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="dataNascimentoLabel" for="aluno-dataNascimento">
                  <Translate contentKey="escolaOnlineApp.aluno.dataNascimento">Data Nascimento</Translate>
                </Label>
                <AvField id="aluno-dataNascimento" data-cy="dataNascimento" type="date" className="form-control" name="dataNascimento" />
              </AvGroup>
              <AvGroup>
                <Label id="tipoSanguineoLabel" for="aluno-tipoSanguineo">
                  <Translate contentKey="escolaOnlineApp.aluno.tipoSanguineo">Tipo Sanguineo</Translate>
                </Label>
                <AvInput
                  id="aluno-tipoSanguineo"
                  data-cy="tipoSanguineo"
                  type="select"
                  className="form-control"
                  name="tipoSanguineo"
                  value={(!isNew && alunoEntity.tipoSanguineo) || 'NI'}
                >
                  <option value="NI">{translate('escolaOnlineApp.TipoSanguineo.NI')}</option>
                  <option value="AP">{translate('escolaOnlineApp.TipoSanguineo.AP')}</option>
                  <option value="AN">{translate('escolaOnlineApp.TipoSanguineo.AN')}</option>
                  <option value="BP">{translate('escolaOnlineApp.TipoSanguineo.BP')}</option>
                  <option value="BN">{translate('escolaOnlineApp.TipoSanguineo.BN')}</option>
                  <option value="ABP">{translate('escolaOnlineApp.TipoSanguineo.ABP')}</option>
                  <option value="ABN">{translate('escolaOnlineApp.TipoSanguineo.ABN')}</option>
                  <option value="OP">{translate('escolaOnlineApp.TipoSanguineo.OP')}</option>
                  <option value="ON">{translate('escolaOnlineApp.TipoSanguineo.ON')}</option>
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label id="nomePaiLabel" for="aluno-nomePai">
                  <Translate contentKey="escolaOnlineApp.aluno.nomePai">Nome Pai</Translate>
                </Label>
                <AvField id="aluno-nomePai" data-cy="nomePai" type="text" name="nomePai" />
              </AvGroup>
              <AvGroup>
                <Label id="telefonePaiLabel" for="aluno-telefonePai">
                  <Translate contentKey="escolaOnlineApp.aluno.telefonePai">Telefone Pai</Translate>
                </Label>
                <AvField id="aluno-telefonePai" data-cy="telefonePai" type="text" name="telefonePai" />
              </AvGroup>
              <AvGroup>
                <Label id="nomeMaeLabel" for="aluno-nomeMae">
                  <Translate contentKey="escolaOnlineApp.aluno.nomeMae">Nome Mae</Translate>
                </Label>
                <AvField id="aluno-nomeMae" data-cy="nomeMae" type="text" name="nomeMae" />
              </AvGroup>
              <AvGroup>
                <Label id="telefoneMaeLabel" for="aluno-telefoneMae">
                  <Translate contentKey="escolaOnlineApp.aluno.telefoneMae">Telefone Mae</Translate>
                </Label>
                <AvField id="aluno-telefoneMae" data-cy="telefoneMae" type="text" name="telefoneMae" />
              </AvGroup>
              <AvGroup>
                <Label id="nomeResponsavelLabel" for="aluno-nomeResponsavel">
                  <Translate contentKey="escolaOnlineApp.aluno.nomeResponsavel">Nome Responsavel</Translate>
                </Label>
                <AvField id="aluno-nomeResponsavel" data-cy="nomeResponsavel" type="text" name="nomeResponsavel" />
              </AvGroup>
              <AvGroup>
                <Label id="cpfResponsavelLabel" for="aluno-cpfResponsavel">
                  <Translate contentKey="escolaOnlineApp.aluno.cpfResponsavel">Cpf Responsavel</Translate>
                </Label>
                <AvField id="aluno-cpfResponsavel" data-cy="cpfResponsavel" type="text" name="cpfResponsavel" />
              </AvGroup>
              <AvGroup>
                <Label id="observacoesLabel" for="aluno-observacoes">
                  <Translate contentKey="escolaOnlineApp.aluno.observacoes">Observacoes</Translate>
                </Label>
                <AvField id="aluno-observacoes" data-cy="observacoes" type="text" name="observacoes" />
              </AvGroup>
              <AvGroup>
                <Label for="aluno-pessoaAluno">
                  <Translate contentKey="escolaOnlineApp.aluno.pessoaAluno">Pessoa Aluno</Translate>
                </Label>
                <AvInput id="aluno-pessoaAluno" data-cy="pessoaAluno" type="select" className="form-control" name="pessoaAlunoId">
                  <option value="" key="0" />
                  {pessoas
                    ? pessoas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="aluno-escolaAluno">
                  <Translate contentKey="escolaOnlineApp.aluno.escolaAluno">Escola Aluno</Translate>
                </Label>
                <AvInput id="aluno-escolaAluno" data-cy="escolaAluno" type="select" className="form-control" name="escolaAlunoId">
                  <option value="" key="0" />
                  {escolas
                    ? escolas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/aluno" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  pessoas: storeState.pessoa.entities,
  escolas: storeState.escola.entities,
  alunoEntity: storeState.aluno.entity,
  loading: storeState.aluno.loading,
  updating: storeState.aluno.updating,
  updateSuccess: storeState.aluno.updateSuccess,
});

const mapDispatchToProps = {
  getPessoas,
  getEscolas,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(AlunoUpdate);

// src/main/webapp/app/entities/aluno/aluno-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IAluno, Aluno } from 'app/shared/model/aluno.model';
import { AlunoService } from './aluno.service';
import { IPessoa } from 'app/shared/model/pessoa.model';
import { PessoaService } from 'app/entities/pessoa/pessoa.service';
import { IEscola } from 'app/shared/model/escola.model';
import { EscolaService } from 'app/entities/escola/escola.service';

type SelectableEntity = IPessoa | IEscola;

@Component({
  selector: 'jhi-aluno-update',
  templateUrl: './aluno-update.component.html',
})
export class AlunoUpdateComponent implements OnInit {
  isSaving = false;
  pessoas: IPessoa[] = [];
  escolas: IEscola[] = [];
  dataNascimentoDp: any;

  editForm = this.fb.group({
    id: [],
    dataNascimento: [],
    tipoSanguineo: [],
    nomePai: [],
    telefonePai: [],
    nomeMae: [],
    telefoneMae: [],
    nomeResponsavel: [],
    cpfResponsavel: [],
    observacoes: [],
    pessoaAluno: [],
    escolaAluno: [],
  });

  constructor(
    protected alunoService: AlunoService,
    protected pessoaService: PessoaService,
    protected escolaService: EscolaService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ aluno }) => {
      this.updateForm(aluno);

      this.pessoaService.query().subscribe((res: HttpResponse<IPessoa[]>) => (this.pessoas = res.body || []));

      this.escolaService.query().subscribe((res: HttpResponse<IEscola[]>) => (this.escolas = res.body || []));
    });
  }

  updateForm(aluno: IAluno): void {
    this.editForm.patchValue({
      id: aluno.id,
      dataNascimento: aluno.dataNascimento,
      tipoSanguineo: aluno.tipoSanguineo,
      nomePai: aluno.nomePai,
      telefonePai: aluno.telefonePai,
      nomeMae: aluno.nomeMae,
      telefoneMae: aluno.telefoneMae,
      nomeResponsavel: aluno.nomeResponsavel,
      cpfResponsavel: aluno.cpfResponsavel,
      observacoes: aluno.observacoes,
      pessoaAluno: aluno.pessoaAluno,
      escolaAluno: aluno.escolaAluno,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const aluno = this.createFromForm();
    if (aluno.id !== undefined) {
      this.subscribeToSaveResponse(this.alunoService.update(aluno));
    } else {
      this.subscribeToSaveResponse(this.alunoService.create(aluno));
    }
  }

  private createFromForm(): IAluno {
    return {
      ...new Aluno(),
      id: this.editForm.get(['id'])!.value,
      dataNascimento: this.editForm.get(['dataNascimento'])!.value,
      tipoSanguineo: this.editForm.get(['tipoSanguineo'])!.value,
      nomePai: this.editForm.get(['nomePai'])!.value,
      telefonePai: this.editForm.get(['telefonePai'])!.value,
      nomeMae: this.editForm.get(['nomeMae'])!.value,
      telefoneMae: this.editForm.get(['telefoneMae'])!.value,
      nomeResponsavel: this.editForm.get(['nomeResponsavel'])!.value,
      cpfResponsavel: this.editForm.get(['cpfResponsavel'])!.value,
      observacoes: this.editForm.get(['observacoes'])!.value,
      pessoaAluno: this.editForm.get(['pessoaAluno'])!.value,
      escolaAluno: this.editForm.get(['escolaAluno'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IAluno>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: SelectableEntity): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-aluno-heading" jhiTranslate="escolaOnlineApp.aluno.home.createOrEditLabel">Create or edit a Aluno</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.dataNascimento" for="field_dataNascimento">Data Nascimento</label>
                    <div class="input-group">
                        <input id="field_dataNascimento" type="text" class="form-control" name="dataNascimento" ngbDatepicker #dataNascimentoDp="ngbDatepicker" formControlName="dataNascimento"/>
                        <span class="input-group-append">
                            <button type="button" class="btn btn-secondary" (click)="dataNascimentoDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.tipoSanguineo" for="field_tipoSanguineo">Tipo Sanguineo</label>
                    <select class="form-control" name="tipoSanguineo" formControlName="tipoSanguineo" id="field_tipoSanguineo">
                        <option value="NI">{{ 'escolaOnlineApp.TipoSanguineo.NI' | translate }}</option>
                        <option value="AP">{{ 'escolaOnlineApp.TipoSanguineo.AP' | translate }}</option>
                        <option value="AN">{{ 'escolaOnlineApp.TipoSanguineo.AN' | translate }}</option>
                        <option value="BP">{{ 'escolaOnlineApp.TipoSanguineo.BP' | translate }}</option>
                        <option value="BN">{{ 'escolaOnlineApp.TipoSanguineo.BN' | translate }}</option>
                        <option value="ABP">{{ 'escolaOnlineApp.TipoSanguineo.ABP' | translate }}</option>
                        <option value="ABN">{{ 'escolaOnlineApp.TipoSanguineo.ABN' | translate }}</option>
                        <option value="OP">{{ 'escolaOnlineApp.TipoSanguineo.OP' | translate }}</option>
                        <option value="ON">{{ 'escolaOnlineApp.TipoSanguineo.ON' | translate }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.nomePai" for="field_nomePai">Nome Pai</label>
                    <input type="text" class="form-control" name="nomePai" id="field_nomePai"
                           formControlName="nomePai"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.telefonePai" for="field_telefonePai">Telefone Pai</label>
                    <input type="text" class="form-control" name="telefonePai" id="field_telefonePai"
                           formControlName="telefonePai"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.nomeMae" for="field_nomeMae">Nome Mae</label>
                    <input type="text" class="form-control" name="nomeMae" id="field_nomeMae"
                           formControlName="nomeMae"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.telefoneMae" for="field_telefoneMae">Telefone Mae</label>
                    <input type="text" class="form-control" name="telefoneMae" id="field_telefoneMae"
                           formControlName="telefoneMae"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.nomeResponsavel" for="field_nomeResponsavel">Nome Responsavel</label>
                    <input type="text" class="form-control" name="nomeResponsavel" id="field_nomeResponsavel"
                           formControlName="nomeResponsavel"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.cpfResponsavel" for="field_cpfResponsavel">Cpf Responsavel</label>
                    <input type="text" class="form-control" name="cpfResponsavel" id="field_cpfResponsavel"
                           formControlName="cpfResponsavel"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.observacoes" for="field_observacoes">Observacoes</label>
                    <input type="text" class="form-control" name="observacoes" id="field_observacoes"
                           formControlName="observacoes"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.pessoaAluno" for="field_pessoaAluno">Pessoa Aluno</label>
                    <select class="form-control" id="field_pessoaAluno" name="pessoaAluno" formControlName="pessoaAluno">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="pessoaOption.id === editForm.get('pessoaAluno')!.value?.id ? editForm.get('pessoaAluno')!.value : pessoaOption" *ngFor="let pessoaOption of pessoas; trackBy: trackById">{{ pessoaOption.nome }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.aluno.escolaAluno" for="field_escolaAluno">Escola Aluno</label>
                    <select class="form-control" id="field_escolaAluno" name="escolaAluno" formControlName="escolaAluno">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="escolaOption.id === editForm.get('escolaAluno')!.value?.id ? editForm.get('escolaAluno')!.value : escolaOption" *ngFor="let escolaOption of escolas; trackBy: trackById">{{ escolaOption.nome }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
