// src/main/webapp/app/entities/aluno/aluno.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { HttpHeaders, HttpResponse } from '@angular/common/http';
import { ActivatedRoute, ParamMap, Router, Data } from '@angular/router';
import { Subscription, combineLatest } from 'rxjs';
import { JhiEventManager } from 'ng-jhipster';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IAluno } from 'app/shared/model/aluno.model';

import { ITEMS_PER_PAGE } from 'app/shared/constants/pagination.constants';
import { AlunoService } from './aluno.service';
import { AlunoDeleteDialogComponent } from './aluno-delete-dialog.component';

@Component({
  selector: 'jhi-aluno',
  templateUrl: './aluno.component.html',
})
export class AlunoComponent implements OnInit, OnDestroy {
  alunos?: IAluno[];
  eventSubscriber?: Subscription;
  totalItems = 0;
  itemsPerPage = ITEMS_PER_PAGE;
  page!: number;
  predicate!: string;
  ascending!: boolean;
  ngbPaginationPage = 1;

  constructor(
    protected alunoService: AlunoService,
    protected activatedRoute: ActivatedRoute,
    protected router: Router,
    protected eventManager: JhiEventManager,
    protected modalService: NgbModal
  ) {}

  loadPage(page?: number, dontNavigate?: boolean): void {
    const pageToLoad: number = page || this.page || 1;

    this.alunoService
      .query({
        page: pageToLoad - 1,
        size: this.itemsPerPage,
        sort: this.sort(),
      })
      .subscribe(
        (res: HttpResponse<IAluno[]>) => this.onSuccess(res.body, res.headers, pageToLoad, !dontNavigate),
        () => this.onError()
      );
  }

  ngOnInit(): void {
    this.handleNavigation();
    this.registerChangeInAlunos();
  }

  protected handleNavigation(): void {
    combineLatest(this.activatedRoute.data, this.activatedRoute.queryParamMap, (data: Data, params: ParamMap) => {
      const page = params.get('page');
      const pageNumber = page !== null ? +page : 1;
      const sort = (params.get('sort') ?? data['defaultSort']).split(',');
      const predicate = sort[0];
      const ascending = sort[1] === 'asc';
      if (pageNumber !== this.page || predicate !== this.predicate || ascending !== this.ascending) {
        this.predicate = predicate;
        this.ascending = ascending;
        this.loadPage(pageNumber, true);
      }
    }).subscribe();
  }

  ngOnDestroy(): void {
    if (this.eventSubscriber) {
      this.eventManager.destroy(this.eventSubscriber);
    }
  }

  trackId(index: number, item: IAluno): number {
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-type-assertion
    return item.id!;
  }

  registerChangeInAlunos(): void {
    this.eventSubscriber = this.eventManager.subscribe('alunoListModification', () => this.loadPage());
  }

  delete(aluno: IAluno): void {
    const modalRef = this.modalService.open(AlunoDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.aluno = aluno;
  }

  sort(): string[] {
    const result = [this.predicate + ',' + (this.ascending ? 'asc' : 'desc')];
    if (this.predicate !== 'id') {
      result.push('id');
    }
    return result;
  }

  protected onSuccess(data: IAluno[] | null, headers: HttpHeaders, page: number, navigate: boolean): void {
    this.totalItems = Number(headers.get('X-Total-Count'));
    this.page = page;
    if (navigate) {
      this.router.navigate(['/aluno'], {
        queryParams: {
          page: this.page,
          size: this.itemsPerPage,
          sort: this.predicate + ',' + (this.ascending ? 'asc' : 'desc'),
        },
      });
    }
    this.alunos = data || [];
    this.ngbPaginationPage = this.page;
  }

  protected onError(): void {
    this.ngbPaginationPage = this.page ?? 1;
  }
}

<div>
    <h2 id="page-heading">
        <span jhiTranslate="escolaOnlineApp.aluno.home.title">Alunos</span>

        <button id="jh-create-entity" class="btn btn-primary float-right jh-create-entity create-aluno" [routerLink]="['/aluno/new']">
            <fa-icon icon="plus"></fa-icon>
            <span  jhiTranslate="escolaOnlineApp.aluno.home.createLabel">
            Create a new Aluno
            </span>
        </button>
    </h2>

    <jhi-alert-error></jhi-alert-error>

    <jhi-alert></jhi-alert>

    <div class="alert alert-warning" id="no-result" *ngIf="alunos?.length === 0">
        <span jhiTranslate="escolaOnlineApp.aluno.home.notFound">No alunos found</span>
    </div>

    <div class="table-responsive" id="entities" *ngIf="alunos && alunos.length > 0">
        <table class="table table-striped" aria-describedby="page-heading">
            <thead>
                <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="loadPage.bind(this)">
                    <th scope="col"  jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="dataNascimento"><span jhiTranslate="escolaOnlineApp.aluno.dataNascimento">Data Nascimento</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="tipoSanguineo"><span jhiTranslate="escolaOnlineApp.aluno.tipoSanguineo">Tipo Sanguineo</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="nomePai"><span jhiTranslate="escolaOnlineApp.aluno.nomePai">Nome Pai</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="telefonePai"><span jhiTranslate="escolaOnlineApp.aluno.telefonePai">Telefone Pai</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="nomeMae"><span jhiTranslate="escolaOnlineApp.aluno.nomeMae">Nome Mae</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="telefoneMae"><span jhiTranslate="escolaOnlineApp.aluno.telefoneMae">Telefone Mae</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="nomeResponsavel"><span jhiTranslate="escolaOnlineApp.aluno.nomeResponsavel">Nome Responsavel</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="cpfResponsavel"><span jhiTranslate="escolaOnlineApp.aluno.cpfResponsavel">Cpf Responsavel</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="observacoes"><span jhiTranslate="escolaOnlineApp.aluno.observacoes">Observacoes</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="pessoaAluno.id"><span jhiTranslate="escolaOnlineApp.aluno.pessoaAluno">Pessoa Aluno</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"  jhiSortBy="escolaAluno.id"><span jhiTranslate="escolaOnlineApp.aluno.escolaAluno">Escola Aluno</span> <fa-icon icon="sort"></fa-icon></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let aluno of alunos ;trackBy: trackId">
                    <td><a [routerLink]="['/aluno', aluno.id, 'view']">{{ aluno.id }}</a></td>
                    <td>{{ aluno.dataNascimento | date:'mediumDate' }}</td>
                    <td jhiTranslate="{{ 'escolaOnlineApp.TipoSanguineo.' + aluno.tipoSanguineo }}">{{ aluno.tipoSanguineo }}</td>
                    <td>{{ aluno.nomePai }}</td>
                    <td>{{ aluno.telefonePai }}</td>
                    <td>{{ aluno.nomeMae }}</td>
                    <td>{{ aluno.telefoneMae }}</td>
                    <td>{{ aluno.nomeResponsavel }}</td>
                    <td>{{ aluno.cpfResponsavel }}</td>
                    <td>{{ aluno.observacoes }}</td>
                    <td>
                        <div *ngIf="aluno.pessoaAluno">
                            <a [routerLink]="['/pessoa', aluno.pessoaAluno?.id, 'view']" >{{ aluno.pessoaAluno?.id }}</a>
                        </div>
                    </td>
                    <td>
                        <div *ngIf="aluno.escolaAluno">
                            <a [routerLink]="['/escola', aluno.escolaAluno?.id, 'view']" >{{ aluno.escolaAluno?.id }}</a>
                        </div>
                    </td>
                    <td class="text-right">
                        <div class="btn-group">
                            <button type="submit"
                                    [routerLink]="['/aluno', aluno.id, 'view']"
                                    class="btn btn-info btn-sm">
                                <fa-icon icon="eye"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
                            </button>

                            <button type="submit"
                                    [routerLink]="['/aluno', aluno.id, 'edit']"
                                    class="btn btn-primary btn-sm">
                                <fa-icon icon="pencil-alt"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
                            </button>

                            <button type="submit" (click)="delete(aluno)"
                                    class="btn btn-danger btn-sm">
                                <fa-icon icon="times"></fa-icon>
                                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
                            </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <div *ngIf="alunos && alunos.length > 0">
        <div class="row justify-content-center">
            <jhi-item-count [page]="page" [total]="totalItems" [itemsPerPage]="itemsPerPage"></jhi-item-count>
        </div>

        <div class="row justify-content-center">
            <ngb-pagination [collectionSize]="totalItems" [(page)]="ngbPaginationPage" [pageSize]="itemsPerPage" [maxSize]="5" [rotate]="true" [boundaryLinks]="true" (pageChange)="loadPage($event)"></ngb-pagination>
        </div>
    </div>
</div>

// src/main/webapp/app/entities/aluno/aluno.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './aluno.reducer';
import { IAluno } from 'app/shared/model/aluno.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IAlunoProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Aluno = (props: IAlunoProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { alunoList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="aluno-heading" data-cy="AlunoHeading">
        <Translate contentKey="escolaOnlineApp.aluno.home.title">Alunos</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.aluno.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.aluno.home.createLabel">Create new Aluno</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {alunoList && alunoList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.aluno.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataNascimento')}>
                  <Translate contentKey="escolaOnlineApp.aluno.dataNascimento">Data Nascimento</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('tipoSanguineo')}>
                  <Translate contentKey="escolaOnlineApp.aluno.tipoSanguineo">Tipo Sanguineo</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('nomePai')}>
                  <Translate contentKey="escolaOnlineApp.aluno.nomePai">Nome Pai</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('telefonePai')}>
                  <Translate contentKey="escolaOnlineApp.aluno.telefonePai">Telefone Pai</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('nomeMae')}>
                  <Translate contentKey="escolaOnlineApp.aluno.nomeMae">Nome Mae</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('telefoneMae')}>
                  <Translate contentKey="escolaOnlineApp.aluno.telefoneMae">Telefone Mae</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('nomeResponsavel')}>
                  <Translate contentKey="escolaOnlineApp.aluno.nomeResponsavel">Nome Responsavel</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('cpfResponsavel')}>
                  <Translate contentKey="escolaOnlineApp.aluno.cpfResponsavel">Cpf Responsavel</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoes')}>
                  <Translate contentKey="escolaOnlineApp.aluno.observacoes">Observacoes</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.aluno.pessoaAluno">Pessoa Aluno</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.aluno.escolaAluno">Escola Aluno</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {alunoList.map((aluno, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${aluno.id}`} color="link" size="sm">
                      {aluno.id}
                    </Button>
                  </td>
                  <td>{aluno.id}</td>
                  <td>
                    {aluno.dataNascimento ? <TextFormat type="date" value={aluno.dataNascimento} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>
                    <Translate contentKey={`escolaOnlineApp.TipoSanguineo.${aluno.tipoSanguineo}`} />
                  </td>
                  <td>{aluno.nomePai}</td>
                  <td>{aluno.telefonePai}</td>
                  <td>{aluno.nomeMae}</td>
                  <td>{aluno.telefoneMae}</td>
                  <td>{aluno.nomeResponsavel}</td>
                  <td>{aluno.cpfResponsavel}</td>
                  <td>{aluno.observacoes}</td>
                  <td>{aluno.pessoaAluno ? <Link to={`pessoa/${aluno.pessoaAluno.id}`}>{aluno.pessoaAluno.id}</Link> : ''}</td>
                  <td>{aluno.escolaAluno ? <Link to={`escola/${aluno.escolaAluno.id}`}>{aluno.escolaAluno.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${aluno.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${aluno.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${aluno.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.aluno.home.notFound">No Alunos found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={alunoList && alunoList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ aluno }: IRootState) => ({
  alunoList: aluno.entities,
  loading: aluno.loading,
  totalItems: aluno.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Aluno);
