// src/main/webapp/app/entities/professor/list/professor.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IProfessor } from '../professor.model';
import { ProfessorService } from '../service/professor.service';
import { ProfessorDeleteDialogComponent } from '../delete/professor-delete-dialog.component';

@Component({
  selector: 'jhi-professor',
  templateUrl: './professor.component.html',
})
export class ProfessorComponent implements OnInit {
  professors?: IProfessor[];
  isLoading = false;

  constructor(protected professorService: ProfessorService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.professorService.query().subscribe(
      (res: HttpResponse<IProfessor[]>) => {
        this.isLoading = false;
        this.professors = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IProfessor): number {
    return item.id!;
  }

  delete(professor: IProfessor): void {
    const modalRef = this.modalService.open(ProfessorDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.professor = professor;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="ProfessorHeading">
    <span jhiTranslate="escolaOnlineApp.professor.home.title">Professors</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.professor.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-professor"
        [routerLink]="['/professor/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.professor.home.createLabel"> Create a new Professor </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="professors?.length === 0">
    <span jhiTranslate="escolaOnlineApp.professor.home.notFound">No professors found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="professors && professors.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.professor.anoLetivo">Ano Letivo</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.professor.dataInicio">Data Inicio</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.professor.dataFim">Data Fim</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.professor.pessoaProfessor">Pessoa Professor</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.professor.unidadeProfessor">Unidade Professor</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let professor of professors; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/professor', professor.id, 'view']">{{ professor.id }}</a>
          </td>
          <td>{{ professor.anoLetivo }}</td>
          <td>{{ professor.dataInicio | formatMediumDate }}</td>
          <td>{{ professor.dataFim | formatMediumDate }}</td>
          <td>
            <div *ngIf="professor.pessoaProfessor">
              <a [routerLink]="['/pessoa', professor.pessoaProfessor?.id, 'view']">{{ professor.pessoaProfessor?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="professor.unidadeProfessor">
              <a [routerLink]="['/unidade', professor.unidadeProfessor?.id, 'view']">{{ professor.unidadeProfessor?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/professor', professor.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/professor', professor.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(professor)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/professor/professor.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './professor.reducer';
import { IProfessor } from 'app/shared/model/professor.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IProfessorProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Professor = (props: IProfessorProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { professorList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="professor-heading" data-cy="ProfessorHeading">
        <Translate contentKey="escolaOnlineApp.professor.home.title">Professors</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.professor.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.professor.home.createLabel">Create new Professor</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {professorList && professorList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.professor.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('anoLetivo')}>
                  <Translate contentKey="escolaOnlineApp.professor.anoLetivo">Ano Letivo</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataInicio')}>
                  <Translate contentKey="escolaOnlineApp.professor.dataInicio">Data Inicio</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataFim')}>
                  <Translate contentKey="escolaOnlineApp.professor.dataFim">Data Fim</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.professor.pessoaProfessor">Pessoa Professor</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.professor.unidadeProfessor">Unidade Professor</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {professorList.map((professor, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${professor.id}`} color="link" size="sm">
                      {professor.id}
                    </Button>
                  </td>
                  <td>{professor.id}</td>
                  <td>{professor.anoLetivo}</td>
                  <td>
                    {professor.dataInicio ? <TextFormat type="date" value={professor.dataInicio} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>{professor.dataFim ? <TextFormat type="date" value={professor.dataFim} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>
                    {professor.pessoaProfessor ? (
                      <Link to={`pessoa/${professor.pessoaProfessor.id}`}>{professor.pessoaProfessor.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {professor.unidadeProfessor ? (
                      <Link to={`unidade/${professor.unidadeProfessor.id}`}>{professor.unidadeProfessor.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${professor.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${professor.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${professor.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.professor.home.notFound">No Professors found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={professorList && professorList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ professor }: IRootState) => ({
  professorList: professor.entities,
  loading: professor.loading,
  totalItems: professor.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Professor);
