// src/main/webapp/app/entities/professor/detail/professor-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IProfessor } from '../professor.model';

@Component({
  selector: 'jhi-professor-detail',
  templateUrl: './professor-detail.component.html',
})
export class ProfessorDetailComponent implements OnInit {
  professor: IProfessor | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ professor }) => {
      this.professor = professor;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="professor">
      <h2 data-cy="professorDetailsHeading"><span jhiTranslate="escolaOnlineApp.professor.detail.title">Professor</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ professor.id }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.professor.anoLetivo">Ano Letivo</span></dt>
        <dd>
          <span>{{ professor.anoLetivo }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.professor.dataInicio">Data Inicio</span></dt>
        <dd>
          <span>{{ professor.dataInicio | formatMediumDate }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.professor.dataFim">Data Fim</span></dt>
        <dd>
          <span>{{ professor.dataFim | formatMediumDate }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.professor.pessoaProfessor">Pessoa Professor</span></dt>
        <dd>
          <div *ngIf="professor.pessoaProfessor">
            <a [routerLink]="['/pessoa', professor.pessoaProfessor?.id, 'view']">{{ professor.pessoaProfessor?.id }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.professor.unidadeProfessor">Unidade Professor</span></dt>
        <dd>
          <div *ngIf="professor.unidadeProfessor">
            <a [routerLink]="['/unidade', professor.unidadeProfessor?.id, 'view']">{{ professor.unidadeProfessor?.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/professor', professor.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>

// src/main/webapp/app/entities/professor/professor-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './professor.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IProfessorDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ProfessorDetail = (props: IProfessorDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { professorEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="professorDetailsHeading">
          <Translate contentKey="escolaOnlineApp.professor.detail.title">Professor</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{professorEntity.id}</dd>
          <dt>
            <span id="anoLetivo">
              <Translate contentKey="escolaOnlineApp.professor.anoLetivo">Ano Letivo</Translate>
            </span>
          </dt>
          <dd>{professorEntity.anoLetivo}</dd>
          <dt>
            <span id="dataInicio">
              <Translate contentKey="escolaOnlineApp.professor.dataInicio">Data Inicio</Translate>
            </span>
          </dt>
          <dd>
            {professorEntity.dataInicio ? (
              <TextFormat value={professorEntity.dataInicio} type="date" format={APP_LOCAL_DATE_FORMAT} />
            ) : null}
          </dd>
          <dt>
            <span id="dataFim">
              <Translate contentKey="escolaOnlineApp.professor.dataFim">Data Fim</Translate>
            </span>
          </dt>
          <dd>
            {professorEntity.dataFim ? <TextFormat value={professorEntity.dataFim} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.professor.pessoaProfessor">Pessoa Professor</Translate>
          </dt>
          <dd>{professorEntity.pessoaProfessor ? professorEntity.pessoaProfessor.id : ''}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.professor.unidadeProfessor">Unidade Professor</Translate>
          </dt>
          <dd>{professorEntity.unidadeProfessor ? professorEntity.unidadeProfessor.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/professor" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/professor/${professorEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ professor }: IRootState) => ({
  professorEntity: professor.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ProfessorDetail);
