// src/main/webapp/app/entities/unidade/unidade-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IEscola } from 'app/shared/model/escola.model';
import { getEntities as getEscolas } from 'app/entities/escola/escola.reducer';
import { getEntity, updateEntity, createEntity, reset } from './unidade.reducer';
import { IUnidade } from 'app/shared/model/unidade.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IUnidadeUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const UnidadeUpdate = (props: IUnidadeUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { unidadeEntity, escolas, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/unidade' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getEscolas();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...unidadeEntity,
        ...values,
        escolaUnidade: escolas.find(it => it.id.toString() === values.escolaUnidadeId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.unidade.home.createOrEditLabel" data-cy="UnidadeCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.unidade.home.createOrEditLabel">Create or edit a Unidade</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : unidadeEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="unidade-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="unidade-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="nomeLabel" for="unidade-nome">
                  <Translate contentKey="escolaOnlineApp.unidade.nome">Nome</Translate>
                </Label>
                <AvField id="unidade-nome" data-cy="nome" type="text" name="nome" />
              </AvGroup>
              <AvGroup>
                <Label id="cnpjLabel" for="unidade-cnpj">
                  <Translate contentKey="escolaOnlineApp.unidade.cnpj">Cnpj</Translate>
                </Label>
                <AvField id="unidade-cnpj" data-cy="cnpj" type="text" name="cnpj" />
              </AvGroup>
              <AvGroup>
                <Label id="enderecoLabel" for="unidade-endereco">
                  <Translate contentKey="escolaOnlineApp.unidade.endereco">Endereco</Translate>
                </Label>
                <AvField id="unidade-endereco" data-cy="endereco" type="text" name="endereco" />
              </AvGroup>
              <AvGroup>
                <Label id="complementoLabel" for="unidade-complemento">
                  <Translate contentKey="escolaOnlineApp.unidade.complemento">Complemento</Translate>
                </Label>
                <AvField id="unidade-complemento" data-cy="complemento" type="text" name="complemento" />
              </AvGroup>
              <AvGroup>
                <Label id="bairroLabel" for="unidade-bairro">
                  <Translate contentKey="escolaOnlineApp.unidade.bairro">Bairro</Translate>
                </Label>
                <AvField id="unidade-bairro" data-cy="bairro" type="text" name="bairro" />
              </AvGroup>
              <AvGroup>
                <Label id="cidadeLabel" for="unidade-cidade">
                  <Translate contentKey="escolaOnlineApp.unidade.cidade">Cidade</Translate>
                </Label>
                <AvField id="unidade-cidade" data-cy="cidade" type="text" name="cidade" />
              </AvGroup>
              <AvGroup>
                <Label id="cepLabel" for="unidade-cep">
                  <Translate contentKey="escolaOnlineApp.unidade.cep">Cep</Translate>
                </Label>
                <AvField id="unidade-cep" data-cy="cep" type="text" name="cep" />
              </AvGroup>
              <AvGroup>
                <Label id="telefoneComercialLabel" for="unidade-telefoneComercial">
                  <Translate contentKey="escolaOnlineApp.unidade.telefoneComercial">Telefone Comercial</Translate>
                </Label>
                <AvField id="unidade-telefoneComercial" data-cy="telefoneComercial" type="text" name="telefoneComercial" />
              </AvGroup>
              <AvGroup>
                <Label id="telefoneWhatsappLabel" for="unidade-telefoneWhatsapp">
                  <Translate contentKey="escolaOnlineApp.unidade.telefoneWhatsapp">Telefone Whatsapp</Translate>
                </Label>
                <AvField id="unidade-telefoneWhatsapp" data-cy="telefoneWhatsapp" type="text" name="telefoneWhatsapp" />
              </AvGroup>
              <AvGroup>
                <Label id="emailLabel" for="unidade-email">
                  <Translate contentKey="escolaOnlineApp.unidade.email">Email</Translate>
                </Label>
                <AvField id="unidade-email" data-cy="email" type="text" name="email" />
              </AvGroup>
              <AvGroup>
                <Label id="facebookLabel" for="unidade-facebook">
                  <Translate contentKey="escolaOnlineApp.unidade.facebook">Facebook</Translate>
                </Label>
                <AvField id="unidade-facebook" data-cy="facebook" type="text" name="facebook" />
              </AvGroup>
              <AvGroup>
                <Label id="observacoesLabel" for="unidade-observacoes">
                  <Translate contentKey="escolaOnlineApp.unidade.observacoes">Observacoes</Translate>
                </Label>
                <AvField id="unidade-observacoes" data-cy="observacoes" type="text" name="observacoes" />
              </AvGroup>
              <AvGroup>
                <Label for="unidade-escolaUnidade">
                  <Translate contentKey="escolaOnlineApp.unidade.escolaUnidade">Escola Unidade</Translate>
                </Label>
                <AvInput id="unidade-escolaUnidade" data-cy="escolaUnidade" type="select" className="form-control" name="escolaUnidadeId">
                  <option value="" key="0" />
                  {escolas
                    ? escolas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/unidade" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  escolas: storeState.escola.entities,
  unidadeEntity: storeState.unidade.entity,
  loading: storeState.unidade.loading,
  updating: storeState.unidade.updating,
  updateSuccess: storeState.unidade.updateSuccess,
});

const mapDispatchToProps = {
  getEscolas,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(UnidadeUpdate);

// src/main/webapp/app/entities/unidade/unidade-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IUnidade, Unidade } from 'app/shared/model/unidade.model';
import { UnidadeService } from './unidade.service';
import { IEscola } from 'app/shared/model/escola.model';
import { EscolaService } from 'app/entities/escola/escola.service';

@Component({
  selector: 'jhi-unidade-update',
  templateUrl: './unidade-update.component.html',
})
export class UnidadeUpdateComponent implements OnInit {
  isSaving = false;
  escolas: IEscola[] = [];

  editForm = this.fb.group({
    id: [],
    nome: [],
    cnpj: [],
    endereco: [],
    complemento: [],
    bairro: [],
    cidade: [],
    cep: [],
    telefoneComercial: [],
    telefoneWhatsapp: [],
    email: [],
    facebook: [],
    observacoes: [],
    escolaUnidade: [],
  });

  constructor(
    protected unidadeService: UnidadeService,
    protected escolaService: EscolaService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ unidade }) => {
      this.updateForm(unidade);

      this.escolaService.query().subscribe((res: HttpResponse<IEscola[]>) => (this.escolas = res.body || []));
    });
  }

  updateForm(unidade: IUnidade): void {
    this.editForm.patchValue({
      id: unidade.id,
      nome: unidade.nome,
      cnpj: unidade.cnpj,
      endereco: unidade.endereco,
      complemento: unidade.complemento,
      bairro: unidade.bairro,
      cidade: unidade.cidade,
      cep: unidade.cep,
      telefoneComercial: unidade.telefoneComercial,
      telefoneWhatsapp: unidade.telefoneWhatsapp,
      email: unidade.email,
      facebook: unidade.facebook,
      observacoes: unidade.observacoes,
      escolaUnidade: unidade.escolaUnidade,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const unidade = this.createFromForm();
    if (unidade.id !== undefined) {
      this.subscribeToSaveResponse(this.unidadeService.update(unidade));
    } else {
      this.subscribeToSaveResponse(this.unidadeService.create(unidade));
    }
  }

  private createFromForm(): IUnidade {
    return {
      ...new Unidade(),
      id: this.editForm.get(['id'])!.value,
      nome: this.editForm.get(['nome'])!.value,
      cnpj: this.editForm.get(['cnpj'])!.value,
      endereco: this.editForm.get(['endereco'])!.value,
      complemento: this.editForm.get(['complemento'])!.value,
      bairro: this.editForm.get(['bairro'])!.value,
      cidade: this.editForm.get(['cidade'])!.value,
      cep: this.editForm.get(['cep'])!.value,
      telefoneComercial: this.editForm.get(['telefoneComercial'])!.value,
      telefoneWhatsapp: this.editForm.get(['telefoneWhatsapp'])!.value,
      email: this.editForm.get(['email'])!.value,
      facebook: this.editForm.get(['facebook'])!.value,
      observacoes: this.editForm.get(['observacoes'])!.value,
      escolaUnidade: this.editForm.get(['escolaUnidade'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IUnidade>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: IEscola): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-unidade-heading" jhiTranslate="escolaOnlineApp.unidade.home.createOrEditLabel">Create or edit a Unidade</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>
                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.escolaUnidade" for="field_escolaUnidade">Escola Unidade</label>
                    <select class="form-control" id="field_escolaUnidade" name="escolaUnidade" formControlName="escolaUnidade">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="escolaOption.id === editForm.get('escolaUnidade')!.value?.id ? editForm.get('escolaUnidade')!.value : escolaOption" *ngFor="let escolaOption of escolas; trackBy: trackById">{{ escolaOption.nome }}</option>
                    </select>
                </div>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.nome" for="field_nome">Nome</label>
                    <input type="text" class="form-control" name="nome" id="field_nome"
                           formControlName="nome"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.cnpj" for="field_cnpj">Cnpj</label>
                    <input type="text" class="form-control" name="cnpj" id="field_cnpj"
                           formControlName="cnpj"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.endereco" for="field_endereco">Endereco</label>
                    <input type="text" class="form-control" name="endereco" id="field_endereco"
                           formControlName="endereco"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.complemento" for="field_complemento">Complemento</label>
                    <input type="text" class="form-control" name="complemento" id="field_complemento"
                           formControlName="complemento"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.bairro" for="field_bairro">Bairro</label>
                    <input type="text" class="form-control" name="bairro" id="field_bairro"
                           formControlName="bairro"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.cidade" for="field_cidade">Cidade</label>
                    <input type="text" class="form-control" name="cidade" id="field_cidade"
                           formControlName="cidade"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.cep" for="field_cep">Cep</label>
                    <input type="text" class="form-control" name="cep" id="field_cep"
                           formControlName="cep"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.telefoneComercial" for="field_telefoneComercial">Telefone Comercial</label>
                    <input type="text" class="form-control" name="telefoneComercial" id="field_telefoneComercial"
                           formControlName="telefoneComercial"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.telefoneWhatsapp" for="field_telefoneWhatsapp">Telefone Whatsapp</label>
                    <input type="text" class="form-control" name="telefoneWhatsapp" id="field_telefoneWhatsapp"
                           formControlName="telefoneWhatsapp"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.email" for="field_email">Email</label>
                    <input type="text" class="form-control" name="email" id="field_email"
                           formControlName="email"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.facebook" for="field_facebook">Facebook</label>
                    <input type="text" class="form-control" name="facebook" id="field_facebook"
                           formControlName="facebook"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.unidade.observacoes" for="field_observacoes">Observacoes</label>
                    <input type="text" class="form-control" name="observacoes" id="field_observacoes"
                           formControlName="observacoes"/>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
