// src/main/webapp/app/entities/unidade/list/unidade.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IUnidade } from '../unidade.model';
import { UnidadeService } from '../service/unidade.service';
import { UnidadeDeleteDialogComponent } from '../delete/unidade-delete-dialog.component';

@Component({
  selector: 'jhi-unidade',
  templateUrl: './unidade.component.html',
})
export class UnidadeComponent implements OnInit {
  unidades?: IUnidade[];
  isLoading = false;

  constructor(protected unidadeService: UnidadeService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.unidadeService.query().subscribe(
      (res: HttpResponse<IUnidade[]>) => {
        this.isLoading = false;
        this.unidades = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IUnidade): number {
    return item.id!;
  }

  delete(unidade: IUnidade): void {
    const modalRef = this.modalService.open(UnidadeDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.unidade = unidade;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="UnidadeHeading">
    <span jhiTranslate="escolaOnlineApp.unidade.home.title">Unidades</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.unidade.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-unidade"
        [routerLink]="['/unidade/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.unidade.home.createLabel"> Create a new Unidade </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="unidades?.length === 0">
    <span jhiTranslate="escolaOnlineApp.unidade.home.notFound">No unidades found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="unidades && unidades.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.nome">Nome</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.cnpj">Cnpj</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.endereco">Endereco</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.complemento">Complemento</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.bairro">Bairro</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.cidade">Cidade</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.cep">Cep</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.telefoneComercial">Telefone Comercial</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.telefoneWhatsapp">Telefone Whatsapp</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.email">Email</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.facebook">Facebook</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.observacoes">Observacoes</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.unidade.escolaUnidade">Escola Unidade</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let unidade of unidades; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/unidade', unidade.id, 'view']">{{ unidade.id }}</a>
          </td>
          <td>{{ unidade.nome }}</td>
          <td>{{ unidade.cnpj }}</td>
          <td>{{ unidade.endereco }}</td>
          <td>{{ unidade.complemento }}</td>
          <td>{{ unidade.bairro }}</td>
          <td>{{ unidade.cidade }}</td>
          <td>{{ unidade.cep }}</td>
          <td>{{ unidade.telefoneComercial }}</td>
          <td>{{ unidade.telefoneWhatsapp }}</td>
          <td>{{ unidade.email }}</td>
          <td>{{ unidade.facebook }}</td>
          <td>{{ unidade.observacoes }}</td>
          <td>
            <div *ngIf="unidade.escolaUnidade">
              <a [routerLink]="['/escola', unidade.escolaUnidade?.id, 'view']">{{ unidade.escolaUnidade?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/unidade', unidade.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/unidade', unidade.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(unidade)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/unidade/unidade.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './unidade.reducer';
import { IUnidade } from 'app/shared/model/unidade.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IUnidadeProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Unidade = (props: IUnidadeProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { unidadeList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="unidade-heading" data-cy="UnidadeHeading">
        <Translate contentKey="escolaOnlineApp.unidade.home.title">Unidades</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.unidade.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.unidade.home.createLabel">Create new Unidade</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {unidadeList && unidadeList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.unidade.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('nome')}>
                  <Translate contentKey="escolaOnlineApp.unidade.nome">Nome</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('cnpj')}>
                  <Translate contentKey="escolaOnlineApp.unidade.cnpj">Cnpj</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('endereco')}>
                  <Translate contentKey="escolaOnlineApp.unidade.endereco">Endereco</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('complemento')}>
                  <Translate contentKey="escolaOnlineApp.unidade.complemento">Complemento</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('bairro')}>
                  <Translate contentKey="escolaOnlineApp.unidade.bairro">Bairro</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('cidade')}>
                  <Translate contentKey="escolaOnlineApp.unidade.cidade">Cidade</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('cep')}>
                  <Translate contentKey="escolaOnlineApp.unidade.cep">Cep</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('telefoneComercial')}>
                  <Translate contentKey="escolaOnlineApp.unidade.telefoneComercial">Telefone Comercial</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('telefoneWhatsapp')}>
                  <Translate contentKey="escolaOnlineApp.unidade.telefoneWhatsapp">Telefone Whatsapp</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('email')}>
                  <Translate contentKey="escolaOnlineApp.unidade.email">Email</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('facebook')}>
                  <Translate contentKey="escolaOnlineApp.unidade.facebook">Facebook</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoes')}>
                  <Translate contentKey="escolaOnlineApp.unidade.observacoes">Observacoes</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.unidade.escolaUnidade">Escola Unidade</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {unidadeList.map((unidade, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${unidade.id}`} color="link" size="sm">
                      {unidade.id}
                    </Button>
                  </td>
                  <td>{unidade.id}</td>
                  <td>{unidade.nome}</td>
                  <td>{unidade.cnpj}</td>
                  <td>{unidade.endereco}</td>
                  <td>{unidade.complemento}</td>
                  <td>{unidade.bairro}</td>
                  <td>{unidade.cidade}</td>
                  <td>{unidade.cep}</td>
                  <td>{unidade.telefoneComercial}</td>
                  <td>{unidade.telefoneWhatsapp}</td>
                  <td>{unidade.email}</td>
                  <td>{unidade.facebook}</td>
                  <td>{unidade.observacoes}</td>
                  <td>{unidade.escolaUnidade ? <Link to={`escola/${unidade.escolaUnidade.id}`}>{unidade.escolaUnidade.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${unidade.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${unidade.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${unidade.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.unidade.home.notFound">No Unidades found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={unidadeList && unidadeList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ unidade }: IRootState) => ({
  unidadeList: unidade.entities,
  loading: unidade.loading,
  totalItems: unidade.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Unidade);
