// src/main/webapp/app/entities/turma/turma-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './turma.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ITurmaDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const TurmaDetail = (props: ITurmaDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { turmaEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="turmaDetailsHeading">
          <Translate contentKey="escolaOnlineApp.turma.detail.title">Turma</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{turmaEntity.id}</dd>
          <dt>
            <span id="nome">
              <Translate contentKey="escolaOnlineApp.turma.nome">Nome</Translate>
            </span>
          </dt>
          <dd>{turmaEntity.nome}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.turma.serieTurma">Serie Turma</Translate>
          </dt>
          <dd>{turmaEntity.serieTurma ? turmaEntity.serieTurma.id : ''}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.turma.unidadeTurma">Unidade Turma</Translate>
          </dt>
          <dd>{turmaEntity.unidadeTurma ? turmaEntity.unidadeTurma.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/turma" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/turma/${turmaEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ turma }: IRootState) => ({
  turmaEntity: turma.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(TurmaDetail);

// src/main/webapp/app/entities/turma/detail/turma-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ITurma } from '../turma.model';

@Component({
  selector: 'jhi-turma-detail',
  templateUrl: './turma-detail.component.html',
})
export class TurmaDetailComponent implements OnInit {
  turma: ITurma | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ turma }) => {
      this.turma = turma;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="turma">
      <h2 data-cy="turmaDetailsHeading"><span jhiTranslate="escolaOnlineApp.turma.detail.title">Turma</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ turma.id }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.turma.nome">Nome</span></dt>
        <dd>
          <span>{{ turma.nome }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.turma.serieTurma">Serie Turma</span></dt>
        <dd>
          <div *ngIf="turma.serieTurma">
            <a [routerLink]="['/serie', turma.serieTurma?.id, 'view']">{{ turma.serieTurma?.id }}</a>
          </div>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.turma.unidadeTurma">Unidade Turma</span></dt>
        <dd>
          <div *ngIf="turma.unidadeTurma">
            <a [routerLink]="['/unidade', turma.unidadeTurma?.id, 'view']">{{ turma.unidadeTurma?.id }}</a>
          </div>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/turma', turma.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>
