// src/main/webapp/app/entities/materia/materia-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './materia.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IMateriaDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const MateriaDetail = (props: IMateriaDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { materiaEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="materiaDetailsHeading">
          <Translate contentKey="escolaOnlineApp.materia.detail.title">Materia</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{materiaEntity.id}</dd>
          <dt>
            <span id="nome">
              <Translate contentKey="escolaOnlineApp.materia.nome">Nome</Translate>
            </span>
          </dt>
          <dd>{materiaEntity.nome}</dd>
          <dt>
            <span id="sigla">
              <Translate contentKey="escolaOnlineApp.materia.sigla">Sigla</Translate>
            </span>
          </dt>
          <dd>{materiaEntity.sigla}</dd>
        </dl>
        <Button tag={Link} to="/materia" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/materia/${materiaEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ materia }: IRootState) => ({
  materiaEntity: materia.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(MateriaDetail);

// src/main/webapp/app/entities/materia/detail/materia-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IMateria } from '../materia.model';

@Component({
  selector: 'jhi-materia-detail',
  templateUrl: './materia-detail.component.html',
})
export class MateriaDetailComponent implements OnInit {
  materia: IMateria | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ materia }) => {
      this.materia = materia;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="materia">
      <h2 data-cy="materiaDetailsHeading"><span jhiTranslate="escolaOnlineApp.materia.detail.title">Materia</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ materia.id }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.materia.nome">Nome</span></dt>
        <dd>
          <span>{{ materia.nome }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.materia.sigla">Sigla</span></dt>
        <dd>
          <span>{{ materia.sigla }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/materia', materia.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>
