// src/main/webapp/app/entities/pessoa/pessoa.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './pessoa.reducer';
import { IPessoa } from 'app/shared/model/pessoa.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IPessoaProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Pessoa = (props: IPessoaProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { pessoaList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="pessoa-heading" data-cy="PessoaHeading">
        <Translate contentKey="escolaOnlineApp.pessoa.home.title">Pessoas</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.pessoa.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.pessoa.home.createLabel">Create new Pessoa</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {pessoaList && pessoaList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('nome')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.nome">Nome</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('cpf')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.cpf">Cpf</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('rg')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.rg">Rg</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('endereco')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.endereco">Endereco</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('complemento')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.complemento">Complemento</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('bairro')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.bairro">Bairro</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('cidade')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.cidade">Cidade</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('cep')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.cep">Cep</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('telefoneCelular')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.telefoneCelular">Telefone Celular</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('telefoneResidencial')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.telefoneResidencial">Telefone Residencial</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('telefoneComercial')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.telefoneComercial">Telefone Comercial</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('email')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.email">Email</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoes')}>
                  <Translate contentKey="escolaOnlineApp.pessoa.observacoes">Observacoes</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.pessoa.cidadePessoa">Cidade Pessoa</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.pessoa.escolaPessoa">Escola Pessoa</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {pessoaList.map((pessoa, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${pessoa.id}`} color="link" size="sm">
                      {pessoa.id}
                    </Button>
                  </td>
                  <td>{pessoa.id}</td>
                  <td>{pessoa.nome}</td>
                  <td>{pessoa.cpf}</td>
                  <td>{pessoa.rg}</td>
                  <td>{pessoa.endereco}</td>
                  <td>{pessoa.complemento}</td>
                  <td>{pessoa.bairro}</td>
                  <td>{pessoa.cidade}</td>
                  <td>{pessoa.cep}</td>
                  <td>{pessoa.telefoneCelular}</td>
                  <td>{pessoa.telefoneResidencial}</td>
                  <td>{pessoa.telefoneComercial}</td>
                  <td>{pessoa.email}</td>
                  <td>{pessoa.observacoes}</td>
                  <td>{pessoa.cidadePessoa ? <Link to={`cidade/${pessoa.cidadePessoa.id}`}>{pessoa.cidadePessoa.id}</Link> : ''}</td>
                  <td>{pessoa.escolaPessoa ? <Link to={`escola/${pessoa.escolaPessoa.id}`}>{pessoa.escolaPessoa.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${pessoa.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${pessoa.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${pessoa.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.pessoa.home.notFound">No Pessoas found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={pessoaList && pessoaList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ pessoa }: IRootState) => ({
  pessoaList: pessoa.entities,
  loading: pessoa.loading,
  totalItems: pessoa.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Pessoa);

// src/main/webapp/app/entities/pessoa/list/pessoa.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IPessoa } from '../pessoa.model';
import { PessoaService } from '../service/pessoa.service';
import { PessoaDeleteDialogComponent } from '../delete/pessoa-delete-dialog.component';

@Component({
  selector: 'jhi-pessoa',
  templateUrl: './pessoa.component.html',
})
export class PessoaComponent implements OnInit {
  pessoas?: IPessoa[];
  isLoading = false;

  constructor(protected pessoaService: PessoaService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.pessoaService.query().subscribe(
      (res: HttpResponse<IPessoa[]>) => {
        this.isLoading = false;
        this.pessoas = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IPessoa): number {
    return item.id!;
  }

  delete(pessoa: IPessoa): void {
    const modalRef = this.modalService.open(PessoaDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.pessoa = pessoa;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="PessoaHeading">
    <span jhiTranslate="escolaOnlineApp.pessoa.home.title">Pessoas</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.pessoa.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-pessoa"
        [routerLink]="['/pessoa/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.pessoa.home.createLabel"> Create a new Pessoa </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="pessoas?.length === 0">
    <span jhiTranslate="escolaOnlineApp.pessoa.home.notFound">No pessoas found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="pessoas && pessoas.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.nome">Nome</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.cpf">Cpf</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.rg">Rg</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.endereco">Endereco</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.complemento">Complemento</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.bairro">Bairro</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.cidade">Cidade</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.cep">Cep</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.telefoneCelular">Telefone Celular</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.telefoneResidencial">Telefone Residencial</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.telefoneComercial">Telefone Comercial</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.email">Email</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.observacoes">Observacoes</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.cidadePessoa">Cidade Pessoa</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.pessoa.escolaPessoa">Escola Pessoa</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let pessoa of pessoas; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/pessoa', pessoa.id, 'view']">{{ pessoa.id }}</a>
          </td>
          <td>{{ pessoa.nome }}</td>
          <td>{{ pessoa.cpf }}</td>
          <td>{{ pessoa.rg }}</td>
          <td>{{ pessoa.endereco }}</td>
          <td>{{ pessoa.complemento }}</td>
          <td>{{ pessoa.bairro }}</td>
          <td>{{ pessoa.cidade }}</td>
          <td>{{ pessoa.cep }}</td>
          <td>{{ pessoa.telefoneCelular }}</td>
          <td>{{ pessoa.telefoneResidencial }}</td>
          <td>{{ pessoa.telefoneComercial }}</td>
          <td>{{ pessoa.email }}</td>
          <td>{{ pessoa.observacoes }}</td>
          <td>
            <div *ngIf="pessoa.cidadePessoa">
              <a [routerLink]="['/cidade', pessoa.cidadePessoa?.id, 'view']">{{ pessoa.cidadePessoa?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="pessoa.escolaPessoa">
              <a [routerLink]="['/escola', pessoa.escolaPessoa?.id, 'view']">{{ pessoa.escolaPessoa?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/pessoa', pessoa.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/pessoa', pessoa.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(pessoa)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
