// src/main/webapp/app/entities/tipo-solicitacao/tipo-solicitacao-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IEscola } from 'app/shared/model/escola.model';
import { getEntities as getEscolas } from 'app/entities/escola/escola.reducer';
import { getEntity, updateEntity, createEntity, reset } from './tipo-solicitacao.reducer';
import { ITipoSolicitacao } from 'app/shared/model/tipo-solicitacao.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface ITipoSolicitacaoUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const TipoSolicitacaoUpdate = (props: ITipoSolicitacaoUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { tipoSolicitacaoEntity, escolas, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/tipo-solicitacao' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getEscolas();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...tipoSolicitacaoEntity,
        ...values,
        escolaTipoSolicitacao: escolas.find(it => it.id.toString() === values.escolaTipoSolicitacaoId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.tipoSolicitacao.home.createOrEditLabel" data-cy="TipoSolicitacaoCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.tipoSolicitacao.home.createOrEditLabel">Create or edit a TipoSolicitacao</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : tipoSolicitacaoEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="tipo-solicitacao-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="tipo-solicitacao-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="nomeLabel" for="tipo-solicitacao-nome">
                  <Translate contentKey="escolaOnlineApp.tipoSolicitacao.nome">Nome</Translate>
                </Label>
                <AvField id="tipo-solicitacao-nome" data-cy="nome" type="text" name="nome" />
              </AvGroup>
              <AvGroup>
                <Label id="prazoAtendimentoLabel" for="tipo-solicitacao-prazoAtendimento">
                  <Translate contentKey="escolaOnlineApp.tipoSolicitacao.prazoAtendimento">Prazo Atendimento</Translate>
                </Label>
                <AvField
                  id="tipo-solicitacao-prazoAtendimento"
                  data-cy="prazoAtendimento"
                  type="string"
                  className="form-control"
                  name="prazoAtendimento"
                />
              </AvGroup>
              <AvGroup>
                <Label id="valorEmissaoLabel" for="tipo-solicitacao-valorEmissao">
                  <Translate contentKey="escolaOnlineApp.tipoSolicitacao.valorEmissao">Valor Emissao</Translate>
                </Label>
                <AvField id="tipo-solicitacao-valorEmissao" data-cy="valorEmissao" type="text" name="valorEmissao" />
              </AvGroup>
              <AvGroup>
                <Label for="tipo-solicitacao-escolaTipoSolicitacao">
                  <Translate contentKey="escolaOnlineApp.tipoSolicitacao.escolaTipoSolicitacao">Escola Tipo Solicitacao</Translate>
                </Label>
                <AvInput
                  id="tipo-solicitacao-escolaTipoSolicitacao"
                  data-cy="escolaTipoSolicitacao"
                  type="select"
                  className="form-control"
                  name="escolaTipoSolicitacaoId"
                >
                  <option value="" key="0" />
                  {escolas
                    ? escolas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/tipo-solicitacao" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  escolas: storeState.escola.entities,
  tipoSolicitacaoEntity: storeState.tipoSolicitacao.entity,
  loading: storeState.tipoSolicitacao.loading,
  updating: storeState.tipoSolicitacao.updating,
  updateSuccess: storeState.tipoSolicitacao.updateSuccess,
});

const mapDispatchToProps = {
  getEscolas,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(TipoSolicitacaoUpdate);

// src/main/webapp/app/entities/tipo-solicitacao/tipo-solicitacao-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { ITipoSolicitacao, TipoSolicitacao } from 'app/shared/model/tipo-solicitacao.model';
import { TipoSolicitacaoService } from './tipo-solicitacao.service';
import { IEscola } from 'app/shared/model/escola.model';
import { EscolaService } from 'app/entities/escola/escola.service';

@Component({
  selector: 'jhi-tipo-solicitacao-update',
  templateUrl: './tipo-solicitacao-update.component.html',
})
export class TipoSolicitacaoUpdateComponent implements OnInit {
  isSaving = false;
  escolas: IEscola[] = [];

  editForm = this.fb.group({
    id: [],
    nome: [],
    prazoAtendimento: [],
    valorEmissao: [],
    escolaTipoSolicitacao: [],
  });

  constructor(
    protected tipoSolicitacaoService: TipoSolicitacaoService,
    protected escolaService: EscolaService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ tipoSolicitacao }) => {
      this.updateForm(tipoSolicitacao);

      this.escolaService.query().subscribe((res: HttpResponse<IEscola[]>) => (this.escolas = res.body || []));
    });
  }

  updateForm(tipoSolicitacao: ITipoSolicitacao): void {
    this.editForm.patchValue({
      id: tipoSolicitacao.id,
      nome: tipoSolicitacao.nome,
      prazoAtendimento: tipoSolicitacao.prazoAtendimento,
      valorEmissao: tipoSolicitacao.valorEmissao,
      escolaTipoSolicitacao: tipoSolicitacao.escolaTipoSolicitacao,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const tipoSolicitacao = this.createFromForm();
    if (tipoSolicitacao.id !== undefined) {
      this.subscribeToSaveResponse(this.tipoSolicitacaoService.update(tipoSolicitacao));
    } else {
      this.subscribeToSaveResponse(this.tipoSolicitacaoService.create(tipoSolicitacao));
    }
  }

  private createFromForm(): ITipoSolicitacao {
    return {
      ...new TipoSolicitacao(),
      id: this.editForm.get(['id'])!.value,
      nome: this.editForm.get(['nome'])!.value,
      prazoAtendimento: this.editForm.get(['prazoAtendimento'])!.value,
      valorEmissao: this.editForm.get(['valorEmissao'])!.value,
      escolaTipoSolicitacao: this.editForm.get(['escolaTipoSolicitacao'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<ITipoSolicitacao>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: IEscola): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-tipo-solicitacao-heading" jhiTranslate="escolaOnlineApp.tipoSolicitacao.home.createOrEditLabel">Create or edit a Tipo Solicitacao</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.tipoSolicitacao.nome" for="field_nome">Nome</label>
                    <input type="text" class="form-control" name="nome" id="field_nome"
                           formControlName="nome"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.tipoSolicitacao.prazoAtendimento" for="field_prazoAtendimento">Prazo Atendimento</label>
                    <input type="number" class="form-control" name="prazoAtendimento" id="field_prazoAtendimento"
                           formControlName="prazoAtendimento"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.tipoSolicitacao.valorEmissao" for="field_valorEmissao">Valor Emissao</label>
                    <input type="number" class="form-control" name="valorEmissao" id="field_valorEmissao"
                           formControlName="valorEmissao"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.tipoSolicitacao.escolaTipoSolicitacao" for="field_escolaTipoSolicitacao">Escola Tipo Solicitacao</label>
                    <select class="form-control" id="field_escolaTipoSolicitacao" name="escolaTipoSolicitacao" formControlName="escolaTipoSolicitacao">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="escolaOption.id === editForm.get('escolaTipoSolicitacao')!.value?.id ? editForm.get('escolaTipoSolicitacao')!.value : escolaOption" *ngFor="let escolaOption of escolas; trackBy: trackById">{{ escolaOption.id }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>
