// src/main/webapp/app/entities/conteudo/update/conteudo-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IConteudo, Conteudo } from '../conteudo.model';
import { ConteudoService } from '../service/conteudo.service';
import { ITurma } from 'app/entities/turma/turma.model';
import { TurmaService } from 'app/entities/turma/service/turma.service';
import { IProfessor } from 'app/entities/professor/professor.model';
import { ProfessorService } from 'app/entities/professor/service/professor.service';
import { IMateria } from 'app/entities/materia/materia.model';
import { MateriaService } from 'app/entities/materia/service/materia.service';

@Component({
  selector: 'jhi-conteudo-update',
  templateUrl: './conteudo-update.component.html',
})
export class ConteudoUpdateComponent implements OnInit {
  isSaving = false;

  turmasSharedCollection: ITurma[] = [];
  professorsSharedCollection: IProfessor[] = [];
  materiasSharedCollection: IMateria[] = [];

  editForm = this.fb.group({
    id: [],
    dataAula: [],
    habilidadesCompetencias: [],
    observacoes: [],
    turmaConteudo: [],
    professorConteudo: [],
    materiaConteudo: [],
  });

  constructor(
    protected conteudoService: ConteudoService,
    protected turmaService: TurmaService,
    protected professorService: ProfessorService,
    protected materiaService: MateriaService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ conteudo }) => {
      this.updateForm(conteudo);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const conteudo = this.createFromForm();
    if (conteudo.id !== undefined) {
      this.subscribeToSaveResponse(this.conteudoService.update(conteudo));
    } else {
      this.subscribeToSaveResponse(this.conteudoService.create(conteudo));
    }
  }

  trackTurmaById(index: number, item: ITurma): number {
    return item.id!;
  }

  trackProfessorById(index: number, item: IProfessor): number {
    return item.id!;
  }

  trackMateriaById(index: number, item: IMateria): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IConteudo>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(conteudo: IConteudo): void {
    this.editForm.patchValue({
      id: conteudo.id,
      dataAula: conteudo.dataAula,
      habilidadesCompetencias: conteudo.habilidadesCompetencias,
      observacoes: conteudo.observacoes,
      turmaConteudo: conteudo.turmaConteudo,
      professorConteudo: conteudo.professorConteudo,
      materiaConteudo: conteudo.materiaConteudo,
    });

    this.turmasSharedCollection = this.turmaService.addTurmaToCollectionIfMissing(this.turmasSharedCollection, conteudo.turmaConteudo);
    this.professorsSharedCollection = this.professorService.addProfessorToCollectionIfMissing(
      this.professorsSharedCollection,
      conteudo.professorConteudo
    );
    this.materiasSharedCollection = this.materiaService.addMateriaToCollectionIfMissing(
      this.materiasSharedCollection,
      conteudo.materiaConteudo
    );
  }

  protected loadRelationshipsOptions(): void {
    this.turmaService
      .query()
      .pipe(map((res: HttpResponse<ITurma[]>) => res.body ?? []))
      .pipe(map((turmas: ITurma[]) => this.turmaService.addTurmaToCollectionIfMissing(turmas, this.editForm.get('turmaConteudo')!.value)))
      .subscribe((turmas: ITurma[]) => (this.turmasSharedCollection = turmas));

    this.professorService
      .query()
      .pipe(map((res: HttpResponse<IProfessor[]>) => res.body ?? []))
      .pipe(
        map((professors: IProfessor[]) =>
          this.professorService.addProfessorToCollectionIfMissing(professors, this.editForm.get('professorConteudo')!.value)
        )
      )
      .subscribe((professors: IProfessor[]) => (this.professorsSharedCollection = professors));

    this.materiaService
      .query()
      .pipe(map((res: HttpResponse<IMateria[]>) => res.body ?? []))
      .pipe(
        map((materias: IMateria[]) =>
          this.materiaService.addMateriaToCollectionIfMissing(materias, this.editForm.get('materiaConteudo')!.value)
        )
      )
      .subscribe((materias: IMateria[]) => (this.materiasSharedCollection = materias));
  }

  protected createFromForm(): IConteudo {
    return {
      ...new Conteudo(),
      id: this.editForm.get(['id'])!.value,
      dataAula: this.editForm.get(['dataAula'])!.value,
      habilidadesCompetencias: this.editForm.get(['habilidadesCompetencias'])!.value,
      observacoes: this.editForm.get(['observacoes'])!.value,
      turmaConteudo: this.editForm.get(['turmaConteudo'])!.value,
      professorConteudo: this.editForm.get(['professorConteudo'])!.value,
      materiaConteudo: this.editForm.get(['materiaConteudo'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-conteudo-heading" data-cy="ConteudoCreateUpdateHeading" jhiTranslate="escolaOnlineApp.conteudo.home.createOrEditLabel">
        Create or edit a Conteudo
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.conteudo.dataAula" for="field_dataAula">Data Aula</label>
          <div class="input-group">
            <input
              id="field_dataAula"
              data-cy="dataAula"
              type="text"
              class="form-control"
              name="dataAula"
              ngbDatepicker
              #dataAulaDp="ngbDatepicker"
              formControlName="dataAula"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataAulaDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label
            class="form-control-label"
            jhiTranslate="escolaOnlineApp.conteudo.habilidadesCompetencias"
            for="field_habilidadesCompetencias"
            >Habilidades Competencias</label
          >
          <input
            type="text"
            class="form-control"
            name="habilidadesCompetencias"
            id="field_habilidadesCompetencias"
            data-cy="habilidadesCompetencias"
            formControlName="habilidadesCompetencias"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.conteudo.observacoes" for="field_observacoes">Observacoes</label>
          <input
            type="text"
            class="form-control"
            name="observacoes"
            id="field_observacoes"
            data-cy="observacoes"
            formControlName="observacoes"
          />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.conteudo.turmaConteudo" for="field_turmaConteudo"
            >Turma Conteudo</label
          >
          <select
            class="form-control"
            id="field_turmaConteudo"
            data-cy="turmaConteudo"
            name="turmaConteudo"
            formControlName="turmaConteudo"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="turmaOption.id === editForm.get('turmaConteudo')!.value?.id ? editForm.get('turmaConteudo')!.value : turmaOption"
              *ngFor="let turmaOption of turmasSharedCollection; trackBy: trackTurmaById"
            >
              {{ turmaOption.id }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.conteudo.professorConteudo" for="field_professorConteudo"
            >Professor Conteudo</label
          >
          <select
            class="form-control"
            id="field_professorConteudo"
            data-cy="professorConteudo"
            name="professorConteudo"
            formControlName="professorConteudo"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                professorOption.id === editForm.get('professorConteudo')!.value?.id
                  ? editForm.get('professorConteudo')!.value
                  : professorOption
              "
              *ngFor="let professorOption of professorsSharedCollection; trackBy: trackProfessorById"
            >
              {{ professorOption.id }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.conteudo.materiaConteudo" for="field_materiaConteudo"
            >Materia Conteudo</label
          >
          <select
            class="form-control"
            id="field_materiaConteudo"
            data-cy="materiaConteudo"
            name="materiaConteudo"
            formControlName="materiaConteudo"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                materiaOption.id === editForm.get('materiaConteudo')!.value?.id ? editForm.get('materiaConteudo')!.value : materiaOption
              "
              *ngFor="let materiaOption of materiasSharedCollection; trackBy: trackMateriaById"
            >
              {{ materiaOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/conteudo/conteudo-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ITurma } from 'app/shared/model/turma.model';
import { getEntities as getTurmas } from 'app/entities/turma/turma.reducer';
import { IProfessor } from 'app/shared/model/professor.model';
import { getEntities as getProfessors } from 'app/entities/professor/professor.reducer';
import { IMateria } from 'app/shared/model/materia.model';
import { getEntities as getMaterias } from 'app/entities/materia/materia.reducer';
import { getEntity, updateEntity, createEntity, reset } from './conteudo.reducer';
import { IConteudo } from 'app/shared/model/conteudo.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IConteudoUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ConteudoUpdate = (props: IConteudoUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { conteudoEntity, turmas, professors, materias, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/conteudo' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getTurmas();
    props.getProfessors();
    props.getMaterias();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...conteudoEntity,
        ...values,
        turmaConteudo: turmas.find(it => it.id.toString() === values.turmaConteudoId.toString()),
        professorConteudo: professors.find(it => it.id.toString() === values.professorConteudoId.toString()),
        materiaConteudo: materias.find(it => it.id.toString() === values.materiaConteudoId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.conteudo.home.createOrEditLabel" data-cy="ConteudoCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.conteudo.home.createOrEditLabel">Create or edit a Conteudo</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : conteudoEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="conteudo-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="conteudo-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="dataAulaLabel" for="conteudo-dataAula">
                  <Translate contentKey="escolaOnlineApp.conteudo.dataAula">Data Aula</Translate>
                </Label>
                <AvField id="conteudo-dataAula" data-cy="dataAula" type="date" className="form-control" name="dataAula" />
              </AvGroup>
              <AvGroup>
                <Label id="habilidadesCompetenciasLabel" for="conteudo-habilidadesCompetencias">
                  <Translate contentKey="escolaOnlineApp.conteudo.habilidadesCompetencias">Habilidades Competencias</Translate>
                </Label>
                <AvField
                  id="conteudo-habilidadesCompetencias"
                  data-cy="habilidadesCompetencias"
                  type="text"
                  name="habilidadesCompetencias"
                />
              </AvGroup>
              <AvGroup>
                <Label id="observacoesLabel" for="conteudo-observacoes">
                  <Translate contentKey="escolaOnlineApp.conteudo.observacoes">Observacoes</Translate>
                </Label>
                <AvField id="conteudo-observacoes" data-cy="observacoes" type="text" name="observacoes" />
              </AvGroup>
              <AvGroup>
                <Label for="conteudo-turmaConteudo">
                  <Translate contentKey="escolaOnlineApp.conteudo.turmaConteudo">Turma Conteudo</Translate>
                </Label>
                <AvInput id="conteudo-turmaConteudo" data-cy="turmaConteudo" type="select" className="form-control" name="turmaConteudoId">
                  <option value="" key="0" />
                  {turmas
                    ? turmas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="conteudo-professorConteudo">
                  <Translate contentKey="escolaOnlineApp.conteudo.professorConteudo">Professor Conteudo</Translate>
                </Label>
                <AvInput
                  id="conteudo-professorConteudo"
                  data-cy="professorConteudo"
                  type="select"
                  className="form-control"
                  name="professorConteudoId"
                >
                  <option value="" key="0" />
                  {professors
                    ? professors.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="conteudo-materiaConteudo">
                  <Translate contentKey="escolaOnlineApp.conteudo.materiaConteudo">Materia Conteudo</Translate>
                </Label>
                <AvInput
                  id="conteudo-materiaConteudo"
                  data-cy="materiaConteudo"
                  type="select"
                  className="form-control"
                  name="materiaConteudoId"
                >
                  <option value="" key="0" />
                  {materias
                    ? materias.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/conteudo" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  turmas: storeState.turma.entities,
  professors: storeState.professor.entities,
  materias: storeState.materia.entities,
  conteudoEntity: storeState.conteudo.entity,
  loading: storeState.conteudo.loading,
  updating: storeState.conteudo.updating,
  updateSuccess: storeState.conteudo.updateSuccess,
});

const mapDispatchToProps = {
  getTurmas,
  getProfessors,
  getMaterias,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ConteudoUpdate);
