// src/main/webapp/app/entities/conteudo/conteudo.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './conteudo.reducer';
import { IConteudo } from 'app/shared/model/conteudo.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IConteudoProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Conteudo = (props: IConteudoProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { conteudoList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="conteudo-heading" data-cy="ConteudoHeading">
        <Translate contentKey="escolaOnlineApp.conteudo.home.title">Conteudos</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.conteudo.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.conteudo.home.createLabel">Create new Conteudo</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {conteudoList && conteudoList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.conteudo.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataAula')}>
                  <Translate contentKey="escolaOnlineApp.conteudo.dataAula">Data Aula</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('habilidadesCompetencias')}>
                  <Translate contentKey="escolaOnlineApp.conteudo.habilidadesCompetencias">Habilidades Competencias</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoes')}>
                  <Translate contentKey="escolaOnlineApp.conteudo.observacoes">Observacoes</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.conteudo.turmaConteudo">Turma Conteudo</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.conteudo.professorConteudo">Professor Conteudo</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.conteudo.materiaConteudo">Materia Conteudo</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {conteudoList.map((conteudo, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${conteudo.id}`} color="link" size="sm">
                      {conteudo.id}
                    </Button>
                  </td>
                  <td>{conteudo.id}</td>
                  <td>{conteudo.dataAula ? <TextFormat type="date" value={conteudo.dataAula} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>{conteudo.habilidadesCompetencias}</td>
                  <td>{conteudo.observacoes}</td>
                  <td>
                    {conteudo.turmaConteudo ? <Link to={`turma/${conteudo.turmaConteudo.id}`}>{conteudo.turmaConteudo.id}</Link> : ''}
                  </td>
                  <td>
                    {conteudo.professorConteudo ? (
                      <Link to={`professor/${conteudo.professorConteudo.id}`}>{conteudo.professorConteudo.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {conteudo.materiaConteudo ? (
                      <Link to={`materia/${conteudo.materiaConteudo.id}`}>{conteudo.materiaConteudo.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${conteudo.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${conteudo.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${conteudo.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.conteudo.home.notFound">No Conteudos found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={conteudoList && conteudoList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ conteudo }: IRootState) => ({
  conteudoList: conteudo.entities,
  loading: conteudo.loading,
  totalItems: conteudo.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Conteudo);

// src/main/webapp/app/entities/conteudo/list/conteudo.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IConteudo } from '../conteudo.model';
import { ConteudoService } from '../service/conteudo.service';
import { ConteudoDeleteDialogComponent } from '../delete/conteudo-delete-dialog.component';

@Component({
  selector: 'jhi-conteudo',
  templateUrl: './conteudo.component.html',
})
export class ConteudoComponent implements OnInit {
  conteudos?: IConteudo[];
  isLoading = false;

  constructor(protected conteudoService: ConteudoService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.conteudoService.query().subscribe(
      (res: HttpResponse<IConteudo[]>) => {
        this.isLoading = false;
        this.conteudos = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IConteudo): number {
    return item.id!;
  }

  delete(conteudo: IConteudo): void {
    const modalRef = this.modalService.open(ConteudoDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.conteudo = conteudo;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="ConteudoHeading">
    <span jhiTranslate="escolaOnlineApp.conteudo.home.title">Conteudos</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.conteudo.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-conteudo"
        [routerLink]="['/conteudo/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.conteudo.home.createLabel"> Create a new Conteudo </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="conteudos?.length === 0">
    <span jhiTranslate="escolaOnlineApp.conteudo.home.notFound">No conteudos found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="conteudos && conteudos.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.conteudo.dataAula">Data Aula</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.conteudo.habilidadesCompetencias">Habilidades Competencias</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.conteudo.observacoes">Observacoes</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.conteudo.turmaConteudo">Turma Conteudo</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.conteudo.professorConteudo">Professor Conteudo</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.conteudo.materiaConteudo">Materia Conteudo</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let conteudo of conteudos; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/conteudo', conteudo.id, 'view']">{{ conteudo.id }}</a>
          </td>
          <td>{{ conteudo.dataAula | formatMediumDate }}</td>
          <td>{{ conteudo.habilidadesCompetencias }}</td>
          <td>{{ conteudo.observacoes }}</td>
          <td>
            <div *ngIf="conteudo.turmaConteudo">
              <a [routerLink]="['/turma', conteudo.turmaConteudo?.id, 'view']">{{ conteudo.turmaConteudo?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="conteudo.professorConteudo">
              <a [routerLink]="['/professor', conteudo.professorConteudo?.id, 'view']">{{ conteudo.professorConteudo?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="conteudo.materiaConteudo">
              <a [routerLink]="['/materia', conteudo.materiaConteudo?.id, 'view']">{{ conteudo.materiaConteudo?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/conteudo', conteudo.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/conteudo', conteudo.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(conteudo)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
