// src/main/webapp/app/entities/debito/debito.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './debito.reducer';
import { IDebito } from 'app/shared/model/debito.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IDebitoProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Debito = (props: IDebitoProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { debitoList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="debito-heading" data-cy="DebitoHeading">
        <Translate contentKey="escolaOnlineApp.debito.home.title">Debitos</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.debito.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.debito.home.createLabel">Create new Debito</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {debitoList && debitoList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.debito.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('tipoDebito')}>
                  <Translate contentKey="escolaOnlineApp.debito.tipoDebito">Tipo Debito</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('situacaoDebito')}>
                  <Translate contentKey="escolaOnlineApp.debito.situacaoDebito">Situacao Debito</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataVencimento')}>
                  <Translate contentKey="escolaOnlineApp.debito.dataVencimento">Data Vencimento</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataPagamento')}>
                  <Translate contentKey="escolaOnlineApp.debito.dataPagamento">Data Pagamento</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('valorOriginal')}>
                  <Translate contentKey="escolaOnlineApp.debito.valorOriginal">Valor Original</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('totalPago')}>
                  <Translate contentKey="escolaOnlineApp.debito.totalPago">Total Pago</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('totalDesconto')}>
                  <Translate contentKey="escolaOnlineApp.debito.totalDesconto">Total Desconto</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('totalDevido')}>
                  <Translate contentKey="escolaOnlineApp.debito.totalDevido">Total Devido</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoes')}>
                  <Translate contentKey="escolaOnlineApp.debito.observacoes">Observacoes</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.debito.alunoDebito">Aluno Debito</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {debitoList.map((debito, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${debito.id}`} color="link" size="sm">
                      {debito.id}
                    </Button>
                  </td>
                  <td>{debito.id}</td>
                  <td>
                    <Translate contentKey={`escolaOnlineApp.TipoDebito.${debito.tipoDebito}`} />
                  </td>
                  <td>
                    <Translate contentKey={`escolaOnlineApp.SituacaoDebito.${debito.situacaoDebito}`} />
                  </td>
                  <td>
                    {debito.dataVencimento ? <TextFormat type="date" value={debito.dataVencimento} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>
                    {debito.dataPagamento ? <TextFormat type="date" value={debito.dataPagamento} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>{debito.valorOriginal}</td>
                  <td>{debito.totalPago}</td>
                  <td>{debito.totalDesconto}</td>
                  <td>{debito.totalDevido}</td>
                  <td>{debito.observacoes}</td>
                  <td>{debito.alunoDebito ? <Link to={`aluno/${debito.alunoDebito.id}`}>{debito.alunoDebito.id}</Link> : ''}</td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${debito.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${debito.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${debito.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.debito.home.notFound">No Debitos found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={debitoList && debitoList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ debito }: IRootState) => ({
  debitoList: debito.entities,
  loading: debito.loading,
  totalItems: debito.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Debito);

// src/main/webapp/app/entities/debito/list/debito.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IDebito } from '../debito.model';
import { DebitoService } from '../service/debito.service';
import { DebitoDeleteDialogComponent } from '../delete/debito-delete-dialog.component';

@Component({
  selector: 'jhi-debito',
  templateUrl: './debito.component.html',
})
export class DebitoComponent implements OnInit {
  debitos?: IDebito[];
  isLoading = false;

  constructor(protected debitoService: DebitoService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.debitoService.query().subscribe(
      (res: HttpResponse<IDebito[]>) => {
        this.isLoading = false;
        this.debitos = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IDebito): number {
    return item.id!;
  }

  delete(debito: IDebito): void {
    const modalRef = this.modalService.open(DebitoDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.debito = debito;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="DebitoHeading">
    <span jhiTranslate="escolaOnlineApp.debito.home.title">Debitos</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.debito.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-debito"
        [routerLink]="['/debito/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.debito.home.createLabel"> Create a new Debito </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="debitos?.length === 0">
    <span jhiTranslate="escolaOnlineApp.debito.home.notFound">No debitos found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="debitos && debitos.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.tipoDebito">Tipo Debito</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.situacaoDebito">Situacao Debito</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.dataVencimento">Data Vencimento</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.dataPagamento">Data Pagamento</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.valorOriginal">Valor Original</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.totalPago">Total Pago</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.totalDesconto">Total Desconto</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.totalDevido">Total Devido</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.observacoes">Observacoes</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.debito.alunoDebito">Aluno Debito</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let debito of debitos; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/debito', debito.id, 'view']">{{ debito.id }}</a>
          </td>
          <td jhiTranslate="{{ 'escolaOnlineApp.TipoDebito.' + debito.tipoDebito }}">{{ debito.tipoDebito }}</td>
          <td jhiTranslate="{{ 'escolaOnlineApp.SituacaoDebito.' + debito.situacaoDebito }}">{{ debito.situacaoDebito }}</td>
          <td>{{ debito.dataVencimento | formatMediumDate }}</td>
          <td>{{ debito.dataPagamento | formatMediumDate }}</td>
          <td>{{ debito.valorOriginal }}</td>
          <td>{{ debito.totalPago }}</td>
          <td>{{ debito.totalDesconto }}</td>
          <td>{{ debito.totalDevido }}</td>
          <td>{{ debito.observacoes }}</td>
          <td>
            <div *ngIf="debito.alunoDebito">
              <a [routerLink]="['/aluno', debito.alunoDebito?.id, 'view']">{{ debito.alunoDebito?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button type="submit" [routerLink]="['/debito', debito.id, 'view']" class="btn btn-info btn-sm" data-cy="entityDetailsButton">
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button type="submit" [routerLink]="['/debito', debito.id, 'edit']" class="btn btn-primary btn-sm" data-cy="entityEditButton">
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(debito)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
