// src/main/webapp/app/entities/chamada/list/chamada.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IChamada } from '../chamada.model';
import { ChamadaService } from '../service/chamada.service';
import { ChamadaDeleteDialogComponent } from '../delete/chamada-delete-dialog.component';

@Component({
  selector: 'jhi-chamada',
  templateUrl: './chamada.component.html',
})
export class ChamadaComponent implements OnInit {
  chamadas?: IChamada[];
  isLoading = false;

  constructor(protected chamadaService: ChamadaService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.chamadaService.query().subscribe(
      (res: HttpResponse<IChamada[]>) => {
        this.isLoading = false;
        this.chamadas = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IChamada): number {
    return item.id!;
  }

  delete(chamada: IChamada): void {
    const modalRef = this.modalService.open(ChamadaDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.chamada = chamada;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="ChamadaHeading">
    <span jhiTranslate="escolaOnlineApp.chamada.home.title">Chamadas</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.chamada.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-chamada"
        [routerLink]="['/chamada/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.chamada.home.createLabel"> Create a new Chamada </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="chamadas?.length === 0">
    <span jhiTranslate="escolaOnlineApp.chamada.home.notFound">No chamadas found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="chamadas && chamadas.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.chamada.dataAula">Data Aula</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.chamada.observacoes">Observacoes</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.chamada.alunoChamada">Aluno Chamada</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.chamada.turmaChamada">Turma Chamada</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.chamada.professorChamada">Professor Chamada</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let chamada of chamadas; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/chamada', chamada.id, 'view']">{{ chamada.id }}</a>
          </td>
          <td>{{ chamada.dataAula | formatMediumDate }}</td>
          <td>{{ chamada.observacoes }}</td>
          <td>
            <div *ngIf="chamada.alunoChamada">
              <a [routerLink]="['/aluno', chamada.alunoChamada?.id, 'view']">{{ chamada.alunoChamada?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="chamada.turmaChamada">
              <a [routerLink]="['/turma', chamada.turmaChamada?.id, 'view']">{{ chamada.turmaChamada?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="chamada.professorChamada">
              <a [routerLink]="['/professor', chamada.professorChamada?.id, 'view']">{{ chamada.professorChamada?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/chamada', chamada.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/chamada', chamada.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(chamada)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/chamada/chamada.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './chamada.reducer';
import { IChamada } from 'app/shared/model/chamada.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IChamadaProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Chamada = (props: IChamadaProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { chamadaList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="chamada-heading" data-cy="ChamadaHeading">
        <Translate contentKey="escolaOnlineApp.chamada.home.title">Chamadas</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.chamada.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.chamada.home.createLabel">Create new Chamada</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {chamadaList && chamadaList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.chamada.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataAula')}>
                  <Translate contentKey="escolaOnlineApp.chamada.dataAula">Data Aula</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoes')}>
                  <Translate contentKey="escolaOnlineApp.chamada.observacoes">Observacoes</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.chamada.alunoChamada">Aluno Chamada</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.chamada.turmaChamada">Turma Chamada</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.chamada.professorChamada">Professor Chamada</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {chamadaList.map((chamada, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${chamada.id}`} color="link" size="sm">
                      {chamada.id}
                    </Button>
                  </td>
                  <td>{chamada.id}</td>
                  <td>{chamada.dataAula ? <TextFormat type="date" value={chamada.dataAula} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>{chamada.observacoes}</td>
                  <td>{chamada.alunoChamada ? <Link to={`aluno/${chamada.alunoChamada.id}`}>{chamada.alunoChamada.id}</Link> : ''}</td>
                  <td>{chamada.turmaChamada ? <Link to={`turma/${chamada.turmaChamada.id}`}>{chamada.turmaChamada.id}</Link> : ''}</td>
                  <td>
                    {chamada.professorChamada ? (
                      <Link to={`professor/${chamada.professorChamada.id}`}>{chamada.professorChamada.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${chamada.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${chamada.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${chamada.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.chamada.home.notFound">No Chamadas found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={chamadaList && chamadaList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ chamada }: IRootState) => ({
  chamadaList: chamada.entities,
  loading: chamada.loading,
  totalItems: chamada.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Chamada);
