// src/main/webapp/app/entities/solicitacao/solicitacao.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './solicitacao.reducer';
import { ISolicitacao } from 'app/shared/model/solicitacao.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface ISolicitacaoProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Solicitacao = (props: ISolicitacaoProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { solicitacaoList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="solicitacao-heading" data-cy="SolicitacaoHeading">
        <Translate contentKey="escolaOnlineApp.solicitacao.home.title">Solicitacaos</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.solicitacao.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.solicitacao.home.createLabel">Create new Solicitacao</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {solicitacaoList && solicitacaoList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.solicitacao.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('situacaoSolicitacao')}>
                  <Translate contentKey="escolaOnlineApp.solicitacao.situacaoSolicitacao">Situacao Solicitacao</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataSolicitacao')}>
                  <Translate contentKey="escolaOnlineApp.solicitacao.dataSolicitacao">Data Solicitacao</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoesSolicitante')}>
                  <Translate contentKey="escolaOnlineApp.solicitacao.observacoesSolicitante">Observacoes Solicitante</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('observacoesAtendimento')}>
                  <Translate contentKey="escolaOnlineApp.solicitacao.observacoesAtendimento">Observacoes Atendimento</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.solicitacao.tipoSolicitacaoSolicitacao">Tipo Solicitacao Solicitacao</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.solicitacao.alunoSolicitacao">Aluno Solicitacao</Translate>{' '}
                  <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {solicitacaoList.map((solicitacao, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${solicitacao.id}`} color="link" size="sm">
                      {solicitacao.id}
                    </Button>
                  </td>
                  <td>{solicitacao.id}</td>
                  <td>
                    <Translate contentKey={`escolaOnlineApp.SituacaoSolicitacao.${solicitacao.situacaoSolicitacao}`} />
                  </td>
                  <td>
                    {solicitacao.dataSolicitacao ? (
                      <TextFormat type="date" value={solicitacao.dataSolicitacao} format={APP_LOCAL_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td>{solicitacao.observacoesSolicitante}</td>
                  <td>{solicitacao.observacoesAtendimento}</td>
                  <td>
                    {solicitacao.tipoSolicitacaoSolicitacao ? (
                      <Link to={`tipo-solicitacao/${solicitacao.tipoSolicitacaoSolicitacao.id}`}>
                        {solicitacao.tipoSolicitacaoSolicitacao.id}
                      </Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td>
                    {solicitacao.alunoSolicitacao ? (
                      <Link to={`aluno/${solicitacao.alunoSolicitacao.id}`}>{solicitacao.alunoSolicitacao.id}</Link>
                    ) : (
                      ''
                    )}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${solicitacao.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${solicitacao.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${solicitacao.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.solicitacao.home.notFound">No Solicitacaos found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={solicitacaoList && solicitacaoList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ solicitacao }: IRootState) => ({
  solicitacaoList: solicitacao.entities,
  loading: solicitacao.loading,
  totalItems: solicitacao.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Solicitacao);

// src/main/webapp/app/entities/solicitacao/list/solicitacao.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { ISolicitacao } from '../solicitacao.model';
import { SolicitacaoService } from '../service/solicitacao.service';
import { SolicitacaoDeleteDialogComponent } from '../delete/solicitacao-delete-dialog.component';

@Component({
  selector: 'jhi-solicitacao',
  templateUrl: './solicitacao.component.html',
})
export class SolicitacaoComponent implements OnInit {
  solicitacaos?: ISolicitacao[];
  isLoading = false;

  constructor(protected solicitacaoService: SolicitacaoService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.solicitacaoService.query().subscribe(
      (res: HttpResponse<ISolicitacao[]>) => {
        this.isLoading = false;
        this.solicitacaos = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: ISolicitacao): number {
    return item.id!;
  }

  delete(solicitacao: ISolicitacao): void {
    const modalRef = this.modalService.open(SolicitacaoDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.solicitacao = solicitacao;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="SolicitacaoHeading">
    <span jhiTranslate="escolaOnlineApp.solicitacao.home.title">Solicitacaos</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.solicitacao.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-solicitacao"
        [routerLink]="['/solicitacao/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.solicitacao.home.createLabel"> Create a new Solicitacao </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="solicitacaos?.length === 0">
    <span jhiTranslate="escolaOnlineApp.solicitacao.home.notFound">No solicitacaos found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="solicitacaos && solicitacaos.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.solicitacao.situacaoSolicitacao">Situacao Solicitacao</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.solicitacao.dataSolicitacao">Data Solicitacao</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.solicitacao.observacoesSolicitante">Observacoes Solicitante</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.solicitacao.observacoesAtendimento">Observacoes Atendimento</span></th>
          <th scope="col">
            <span jhiTranslate="escolaOnlineApp.solicitacao.tipoSolicitacaoSolicitacao">Tipo Solicitacao Solicitacao</span>
          </th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.solicitacao.alunoSolicitacao">Aluno Solicitacao</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let solicitacao of solicitacaos; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/solicitacao', solicitacao.id, 'view']">{{ solicitacao.id }}</a>
          </td>
          <td jhiTranslate="{{ 'escolaOnlineApp.SituacaoSolicitacao.' + solicitacao.situacaoSolicitacao }}">
            {{ solicitacao.situacaoSolicitacao }}
          </td>
          <td>{{ solicitacao.dataSolicitacao | formatMediumDate }}</td>
          <td>{{ solicitacao.observacoesSolicitante }}</td>
          <td>{{ solicitacao.observacoesAtendimento }}</td>
          <td>
            <div *ngIf="solicitacao.tipoSolicitacaoSolicitacao">
              <a [routerLink]="['/tipo-solicitacao', solicitacao.tipoSolicitacaoSolicitacao?.id, 'view']">{{
                solicitacao.tipoSolicitacaoSolicitacao?.id
              }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="solicitacao.alunoSolicitacao">
              <a [routerLink]="['/aluno', solicitacao.alunoSolicitacao?.id, 'view']">{{ solicitacao.alunoSolicitacao?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/solicitacao', solicitacao.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/solicitacao', solicitacao.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(solicitacao)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
