// src/main/webapp/app/entities/grade/grade-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './grade.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IGradeDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const GradeDetail = (props: IGradeDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { gradeEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="gradeDetailsHeading">
          <Translate contentKey="escolaOnlineApp.grade.detail.title">Grade</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{gradeEntity.id}</dd>
          <dt>
            <span id="anoLetivo">
              <Translate contentKey="escolaOnlineApp.grade.anoLetivo">Ano Letivo</Translate>
            </span>
          </dt>
          <dd>{gradeEntity.anoLetivo}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.grade.serieGrade">Serie Grade</Translate>
          </dt>
          <dd>{gradeEntity.serieGrade ? gradeEntity.serieGrade.id : ''}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.grade.materiaGrade">Materia Grade</Translate>
          </dt>
          <dd>{gradeEntity.materiaGrade ? gradeEntity.materiaGrade.id : ''}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.grade.escolaGrade">Escola Grade</Translate>
          </dt>
          <dd>{gradeEntity.escolaGrade ? gradeEntity.escolaGrade.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/grade" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/grade/${gradeEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ grade }: IRootState) => ({
  gradeEntity: grade.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(GradeDetail);

// src/main/webapp/app/entities/grade/grade-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IGrade } from 'app/shared/model/grade.model';

@Component({
  selector: 'jhi-grade-detail',
  templateUrl: './grade-detail.component.html',
})
export class GradeDetailComponent implements OnInit {
  grade: IGrade | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ grade }) => (this.grade = grade));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="grade">
            <h2><span jhiTranslate="escolaOnlineApp.grade.detail.title">Grade</span> {{ grade.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="escolaOnlineApp.grade.anoLetivo">Ano Letivo</span></dt>
                <dd>
                    <span>{{ grade.anoLetivo }}</span>
                </dd>
                <dt><span jhiTranslate="escolaOnlineApp.grade.serieGrade">Serie Grade</span></dt>
                <dd>
                    <div *ngIf="grade.serieGrade">
                        <a [routerLink]="['/serie', grade.serieGrade?.id, 'view']">{{ grade.serieGrade?.nome }}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="escolaOnlineApp.grade.materiaGrade">Materia Grade</span></dt>
                <dd>
                    <div *ngIf="grade.materiaGrade">
                        <a [routerLink]="['/materia', grade.materiaGrade?.id, 'view']">{{ grade.materiaGrade?.nome }}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="escolaOnlineApp.grade.escolaGrade">Escola Grade</span></dt>
                <dd>
                    <div *ngIf="grade.escolaGrade">
                        <a [routerLink]="['/escola', grade.escolaGrade?.id, 'view']">{{ grade.escolaGrade?.nome }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/grade', grade.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
