// src/main/webapp/app/entities/grade/grade-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';

import { IGrade, Grade } from 'app/shared/model/grade.model';
import { GradeService } from './grade.service';
import { ISerie } from 'app/shared/model/serie.model';
import { SerieService } from 'app/entities/serie/serie.service';
import { IMateria } from 'app/shared/model/materia.model';
import { MateriaService } from 'app/entities/materia/materia.service';
import { IEscola } from 'app/shared/model/escola.model';
import { EscolaService } from 'app/entities/escola/escola.service';

type SelectableEntity = ISerie | IMateria | IEscola;

@Component({
  selector: 'jhi-grade-update',
  templateUrl: './grade-update.component.html',
})
export class GradeUpdateComponent implements OnInit {
  isSaving = false;
  series: ISerie[] = [];
  materias: IMateria[] = [];
  escolas: IEscola[] = [];

  editForm = this.fb.group({
    id: [],
    anoLetivo: [],
    serieGrade: [],
    materiaGrade: [],
    escolaGrade: [],
  });

  constructor(
    protected gradeService: GradeService,
    protected serieService: SerieService,
    protected materiaService: MateriaService,
    protected escolaService: EscolaService,
    protected activatedRoute: ActivatedRoute,
    private fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ grade }) => {
      this.updateForm(grade);

      this.serieService.query().subscribe((res: HttpResponse<ISerie[]>) => (this.series = res.body || []));

      this.materiaService.query().subscribe((res: HttpResponse<IMateria[]>) => (this.materias = res.body || []));

      this.escolaService.query().subscribe((res: HttpResponse<IEscola[]>) => (this.escolas = res.body || []));
    });
  }

  updateForm(grade: IGrade): void {
    this.editForm.patchValue({
      id: grade.id,
      anoLetivo: grade.anoLetivo,
      serieGrade: grade.serieGrade,
      materiaGrade: grade.materiaGrade,
      escolaGrade: grade.escolaGrade,
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const grade = this.createFromForm();
    if (grade.id !== undefined) {
      this.subscribeToSaveResponse(this.gradeService.update(grade));
    } else {
      this.subscribeToSaveResponse(this.gradeService.create(grade));
    }
  }

  private createFromForm(): IGrade {
    return {
      ...new Grade(),
      id: this.editForm.get(['id'])!.value,
      anoLetivo: this.editForm.get(['anoLetivo'])!.value,
      serieGrade: this.editForm.get(['serieGrade'])!.value,
      materiaGrade: this.editForm.get(['materiaGrade'])!.value,
      escolaGrade: this.editForm.get(['escolaGrade'])!.value,
    };
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IGrade>>): void {
    result.subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.isSaving = false;
    this.previousState();
  }

  protected onSaveError(): void {
    this.isSaving = false;
  }

  trackById(index: number, item: SelectableEntity): any {
    return item.id;
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
            <h2 id="jhi-grade-heading" jhiTranslate="escolaOnlineApp.grade.home.createOrEditLabel">Create or edit a Grade</h2>

            <div>
                <jhi-alert-error></jhi-alert-error>

                <div class="form-group" [hidden]="!editForm.get('id')!.value">
                    <label for="id" jhiTranslate="global.field.id">ID</label>
                    <input type="text" class="form-control" id="id" name="id" formControlName="id" readonly />
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.grade.anoLetivo" for="field_anoLetivo">Ano Letivo</label>
                    <input type="number" class="form-control" name="anoLetivo" id="field_anoLetivo"
                           formControlName="anoLetivo"/>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.grade.serieGrade" for="field_serieGrade">Serie Grade</label>
                    <select class="form-control" id="field_serieGrade" name="serieGrade" formControlName="serieGrade">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="serieOption.id === editForm.get('serieGrade')!.value?.id ? editForm.get('serieGrade')!.value : serieOption" *ngFor="let serieOption of series; trackBy: trackById">{{ serieOption.id }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.grade.materiaGrade" for="field_materiaGrade">Materia Grade</label>
                    <select class="form-control" id="field_materiaGrade" name="materiaGrade" formControlName="materiaGrade">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="materiaOption.id === editForm.get('materiaGrade')!.value?.id ? editForm.get('materiaGrade')!.value : materiaOption" *ngFor="let materiaOption of materias; trackBy: trackById">{{ materiaOption.id }}</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-control-label" jhiTranslate="escolaOnlineApp.grade.escolaGrade" for="field_escolaGrade">Escola Grade</label>
                    <select class="form-control" id="field_escolaGrade" name="escolaGrade" formControlName="escolaGrade">
                        <option [ngValue]="null"></option>
                        <option [ngValue]="escolaOption.id === editForm.get('escolaGrade')!.value?.id ? editForm.get('escolaGrade')!.value : escolaOption" *ngFor="let escolaOption of escolas; trackBy: trackById">{{ escolaOption.id }}</option>
                    </select>
                </div>
            </div>

            <div>
                <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
                    <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
                </button>

                <button type="submit" id="save-entity" [disabled]="editForm.invalid || isSaving" class="btn btn-primary">
                    <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
                </button>
            </div>
        </form>
    </div>
</div>

// src/main/webapp/app/entities/grade/grade-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { ISerie } from 'app/shared/model/serie.model';
import { getEntities as getSeries } from 'app/entities/serie/serie.reducer';
import { IMateria } from 'app/shared/model/materia.model';
import { getEntities as getMaterias } from 'app/entities/materia/materia.reducer';
import { IEscola } from 'app/shared/model/escola.model';
import { getEntities as getEscolas } from 'app/entities/escola/escola.reducer';
import { getEntity, updateEntity, createEntity, reset } from './grade.reducer';
import { IGrade } from 'app/shared/model/grade.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IGradeUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const GradeUpdate = (props: IGradeUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { gradeEntity, series, materias, escolas, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/grade' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getSeries();
    props.getMaterias();
    props.getEscolas();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...gradeEntity,
        ...values,
        serieGrade: series.find(it => it.id.toString() === values.serieGradeId.toString()),
        materiaGrade: materias.find(it => it.id.toString() === values.materiaGradeId.toString()),
        escolaGrade: escolas.find(it => it.id.toString() === values.escolaGradeId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.grade.home.createOrEditLabel" data-cy="GradeCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.grade.home.createOrEditLabel">Create or edit a Grade</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : gradeEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="grade-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="grade-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="anoLetivoLabel" for="grade-anoLetivo">
                  <Translate contentKey="escolaOnlineApp.grade.anoLetivo">Ano Letivo</Translate>
                </Label>
                <AvField id="grade-anoLetivo" data-cy="anoLetivo" type="string" className="form-control" name="anoLetivo" />
              </AvGroup>
              <AvGroup>
                <Label for="grade-serieGrade">
                  <Translate contentKey="escolaOnlineApp.grade.serieGrade">Serie Grade</Translate>
                </Label>
                <AvInput id="grade-serieGrade" data-cy="serieGrade" type="select" className="form-control" name="serieGradeId">
                  <option value="" key="0" />
                  {series
                    ? series.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="grade-materiaGrade">
                  <Translate contentKey="escolaOnlineApp.grade.materiaGrade">Materia Grade</Translate>
                </Label>
                <AvInput id="grade-materiaGrade" data-cy="materiaGrade" type="select" className="form-control" name="materiaGradeId">
                  <option value="" key="0" />
                  {materias
                    ? materias.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="grade-escolaGrade">
                  <Translate contentKey="escolaOnlineApp.grade.escolaGrade">Escola Grade</Translate>
                </Label>
                <AvInput id="grade-escolaGrade" data-cy="escolaGrade" type="select" className="form-control" name="escolaGradeId">
                  <option value="" key="0" />
                  {escolas
                    ? escolas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/grade" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  series: storeState.serie.entities,
  materias: storeState.materia.entities,
  escolas: storeState.escola.entities,
  gradeEntity: storeState.grade.entity,
  loading: storeState.grade.loading,
  updating: storeState.grade.updating,
  updateSuccess: storeState.grade.updateSuccess,
});

const mapDispatchToProps = {
  getSeries,
  getMaterias,
  getEscolas,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(GradeUpdate);
