// src/main/webapp/app/entities/diretor/diretor-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, TextFormat } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './diretor.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface IDiretorDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const DiretorDetail = (props: IDiretorDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { diretorEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="diretorDetailsHeading">
          <Translate contentKey="escolaOnlineApp.diretor.detail.title">Diretor</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{diretorEntity.id}</dd>
          <dt>
            <span id="anoLetivo">
              <Translate contentKey="escolaOnlineApp.diretor.anoLetivo">Ano Letivo</Translate>
            </span>
          </dt>
          <dd>{diretorEntity.anoLetivo}</dd>
          <dt>
            <span id="dataInicio">
              <Translate contentKey="escolaOnlineApp.diretor.dataInicio">Data Inicio</Translate>
            </span>
          </dt>
          <dd>
            {diretorEntity.dataInicio ? <TextFormat value={diretorEntity.dataInicio} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}
          </dd>
          <dt>
            <span id="dataFim">
              <Translate contentKey="escolaOnlineApp.diretor.dataFim">Data Fim</Translate>
            </span>
          </dt>
          <dd>{diretorEntity.dataFim ? <TextFormat value={diretorEntity.dataFim} type="date" format={APP_LOCAL_DATE_FORMAT} /> : null}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.diretor.pessoaDiretor">Pessoa Diretor</Translate>
          </dt>
          <dd>{diretorEntity.pessoaDiretor ? diretorEntity.pessoaDiretor.id : ''}</dd>
          <dt>
            <Translate contentKey="escolaOnlineApp.diretor.unidadeDiretor">Unidade Diretor</Translate>
          </dt>
          <dd>{diretorEntity.unidadeDiretor ? diretorEntity.unidadeDiretor.id : ''}</dd>
        </dl>
        <Button tag={Link} to="/diretor" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/diretor/${diretorEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ diretor }: IRootState) => ({
  diretorEntity: diretor.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(DiretorDetail);

// src/main/webapp/app/entities/diretor/diretor-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { IDiretor } from 'app/shared/model/diretor.model';

@Component({
  selector: 'jhi-diretor-detail',
  templateUrl: './diretor-detail.component.html',
})
export class DiretorDetailComponent implements OnInit {
  diretor: IDiretor | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ diretor }) => (this.diretor = diretor));
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
    <div class="col-8">
        <div *ngIf="diretor">
            <h2><span jhiTranslate="escolaOnlineApp.diretor.detail.title">Diretor</span> {{ diretor.id }}</h2>

            <hr>

            <jhi-alert-error></jhi-alert-error>

            <dl class="row-md jh-entity-details">
                <dt><span jhiTranslate="escolaOnlineApp.diretor.anoLetivo">Ano Letivo</span></dt>
                <dd>
                    <span>{{ diretor.anoLetivo }}</span>
                </dd>
                <dt><span jhiTranslate="escolaOnlineApp.diretor.dataInicio">Data Inicio</span></dt>
                <dd>
                    <span>{{ diretor.dataInicio }}</span>
                </dd>
                <dt><span jhiTranslate="escolaOnlineApp.diretor.dataFim">Data Fim</span></dt>
                <dd>
                    <span>{{ diretor.dataFim }}</span>
                </dd>
                <dt><span jhiTranslate="escolaOnlineApp.diretor.pessoaDiretor">Pessoa Diretor</span></dt>
                <dd>
                    <div *ngIf="diretor.pessoaDiretor">
                        <a [routerLink]="['/pessoa', diretor.pessoaDiretor?.id, 'view']">{{ diretor.pessoaDiretor?.nome }}</a>
                    </div>
                </dd>
                <dt><span jhiTranslate="escolaOnlineApp.diretor.unidadeDiretor">Unidade Diretor</span></dt>
                <dd>
                    <div *ngIf="diretor.unidadeDiretor">
                        <a [routerLink]="['/unidade', diretor.unidadeDiretor?.id, 'view']">{{ diretor.unidadeDiretor?.nome }}</a>
                    </div>
                </dd>
            </dl>

            <button type="submit"
                    (click)="previousState()"
                    class="btn btn-info">
                <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
            </button>

            <button type="button"
                    [routerLink]="['/diretor', diretor.id, 'edit']"
                    class="btn btn-primary">
                <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
            </button>
        </div>
    </div>
</div>
