// src/main/webapp/app/entities/diretor/list/diretor.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';

import { IDiretor } from '../diretor.model';
import { DiretorService } from '../service/diretor.service';
import { DiretorDeleteDialogComponent } from '../delete/diretor-delete-dialog.component';

@Component({
  selector: 'jhi-diretor',
  templateUrl: './diretor.component.html',
})
export class DiretorComponent implements OnInit {
  diretors?: IDiretor[];
  isLoading = false;

  constructor(protected diretorService: DiretorService, protected modalService: NgbModal) {}

  loadAll(): void {
    this.isLoading = true;

    this.diretorService.query().subscribe(
      (res: HttpResponse<IDiretor[]>) => {
        this.isLoading = false;
        this.diretors = res.body ?? [];
      },
      () => {
        this.isLoading = false;
      }
    );
  }

  ngOnInit(): void {
    this.loadAll();
  }

  trackId(index: number, item: IDiretor): number {
    return item.id!;
  }

  delete(diretor: IDiretor): void {
    const modalRef = this.modalService.open(DiretorDeleteDialogComponent, { size: 'lg', backdrop: 'static' });
    modalRef.componentInstance.diretor = diretor;
    // unsubscribe not needed because closed completes on modal close
    modalRef.closed.subscribe(reason => {
      if (reason === 'deleted') {
        this.loadAll();
      }
    });
  }
}

<div>
  <h2 id="page-heading" data-cy="DiretorHeading">
    <span jhiTranslate="escolaOnlineApp.diretor.home.title">Diretors</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-info mr-2" (click)="loadAll()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.diretor.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-diretor"
        [routerLink]="['/diretor/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="escolaOnlineApp.diretor.home.createLabel"> Create a new Diretor </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="diretors?.length === 0">
    <span jhiTranslate="escolaOnlineApp.diretor.home.notFound">No diretors found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="diretors && diretors.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr>
          <th scope="col"><span jhiTranslate="global.field.id">ID</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.diretor.anoLetivo">Ano Letivo</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.diretor.dataInicio">Data Inicio</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.diretor.dataFim">Data Fim</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.diretor.pessoaDiretor">Pessoa Diretor</span></th>
          <th scope="col"><span jhiTranslate="escolaOnlineApp.diretor.unidadeDiretor">Unidade Diretor</span></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let diretor of diretors; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/diretor', diretor.id, 'view']">{{ diretor.id }}</a>
          </td>
          <td>{{ diretor.anoLetivo }}</td>
          <td>{{ diretor.dataInicio | formatMediumDate }}</td>
          <td>{{ diretor.dataFim | formatMediumDate }}</td>
          <td>
            <div *ngIf="diretor.pessoaDiretor">
              <a [routerLink]="['/pessoa', diretor.pessoaDiretor?.id, 'view']">{{ diretor.pessoaDiretor?.id }}</a>
            </div>
          </td>
          <td>
            <div *ngIf="diretor.unidadeDiretor">
              <a [routerLink]="['/unidade', diretor.unidadeDiretor?.id, 'view']">{{ diretor.unidadeDiretor?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/diretor', diretor.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/diretor', diretor.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(diretor)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

// src/main/webapp/app/entities/diretor/diretor.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Col, Row, Table } from 'reactstrap';
import { Translate, TextFormat, getSortState, IPaginationBaseState, JhiPagination, JhiItemCount } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntities } from './diretor.reducer';
import { IDiretor } from 'app/shared/model/diretor.model';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';
import { ITEMS_PER_PAGE } from 'app/shared/util/pagination.constants';
import { overridePaginationStateWithQueryParams } from 'app/shared/util/entity-utils';

export interface IDiretorProps extends StateProps, DispatchProps, RouteComponentProps<{ url: string }> {}

export const Diretor = (props: IDiretorProps) => {
  const [paginationState, setPaginationState] = useState(
    overridePaginationStateWithQueryParams(getSortState(props.location, ITEMS_PER_PAGE, 'id'), props.location.search)
  );

  const getAllEntities = () => {
    props.getEntities(paginationState.activePage - 1, paginationState.itemsPerPage, `${paginationState.sort},${paginationState.order}`);
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`;
    if (props.location.search !== endURL) {
      props.history.push(`${props.location.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [paginationState.activePage, paginationState.order, paginationState.sort]);

  useEffect(() => {
    const params = new URLSearchParams(props.location.search);
    const page = params.get('page');
    const sort = params.get('sort');
    if (page && sort) {
      const sortSplit = sort.split(',');
      setPaginationState({
        ...paginationState,
        activePage: +page,
        sort: sortSplit[0],
        order: sortSplit[1],
      });
    }
  }, [props.location.search]);

  const sort = p => () => {
    setPaginationState({
      ...paginationState,
      order: paginationState.order === 'asc' ? 'desc' : 'asc',
      sort: p,
    });
  };

  const handlePagination = currentPage =>
    setPaginationState({
      ...paginationState,
      activePage: currentPage,
    });

  const handleSyncList = () => {
    sortEntities();
  };

  const { diretorList, match, loading, totalItems } = props;
  return (
    <div>
      <h2 id="diretor-heading" data-cy="DiretorHeading">
        <Translate contentKey="escolaOnlineApp.diretor.home.title">Diretors</Translate>
        <div className="d-flex justify-content-end">
          <Button className="mr-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="escolaOnlineApp.diretor.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to={`${match.url}/new`} className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="escolaOnlineApp.diretor.home.createLabel">Create new Diretor</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {diretorList && diretorList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="escolaOnlineApp.diretor.id">ID</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('anoLetivo')}>
                  <Translate contentKey="escolaOnlineApp.diretor.anoLetivo">Ano Letivo</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataInicio')}>
                  <Translate contentKey="escolaOnlineApp.diretor.dataInicio">Data Inicio</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th className="hand" onClick={sort('dataFim')}>
                  <Translate contentKey="escolaOnlineApp.diretor.dataFim">Data Fim</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.diretor.pessoaDiretor">Pessoa Diretor</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th>
                  <Translate contentKey="escolaOnlineApp.diretor.unidadeDiretor">Unidade Diretor</Translate> <FontAwesomeIcon icon="sort" />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {diretorList.map((diretor, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`${match.url}/${diretor.id}`} color="link" size="sm">
                      {diretor.id}
                    </Button>
                  </td>
                  <td>{diretor.id}</td>
                  <td>{diretor.anoLetivo}</td>
                  <td>
                    {diretor.dataInicio ? <TextFormat type="date" value={diretor.dataInicio} format={APP_LOCAL_DATE_FORMAT} /> : null}
                  </td>
                  <td>{diretor.dataFim ? <TextFormat type="date" value={diretor.dataFim} format={APP_LOCAL_DATE_FORMAT} /> : null}</td>
                  <td>{diretor.pessoaDiretor ? <Link to={`pessoa/${diretor.pessoaDiretor.id}`}>{diretor.pessoaDiretor.id}</Link> : ''}</td>
                  <td>
                    {diretor.unidadeDiretor ? <Link to={`unidade/${diretor.unidadeDiretor.id}`}>{diretor.unidadeDiretor.id}</Link> : ''}
                  </td>
                  <td className="text-right">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`${match.url}/${diretor.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${diretor.id}/edit?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`${match.url}/${diretor.id}/delete?page=${paginationState.activePage}&sort=${paginationState.sort},${paginationState.order}`}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="escolaOnlineApp.diretor.home.notFound">No Diretors found</Translate>
            </div>
          )
        )}
      </div>
      {props.totalItems ? (
        <div className={diretorList && diretorList.length > 0 ? '' : 'd-none'}>
          <Row className="justify-content-center">
            <JhiItemCount page={paginationState.activePage} total={totalItems} itemsPerPage={paginationState.itemsPerPage} i18nEnabled />
          </Row>
          <Row className="justify-content-center">
            <JhiPagination
              activePage={paginationState.activePage}
              onSelect={handlePagination}
              maxButtons={5}
              itemsPerPage={paginationState.itemsPerPage}
              totalItems={props.totalItems}
            />
          </Row>
        </div>
      ) : (
        ''
      )}
    </div>
  );
};

const mapStateToProps = ({ diretor }: IRootState) => ({
  diretorList: diretor.entities,
  loading: diretor.loading,
  totalItems: diretor.totalItems,
});

const mapDispatchToProps = {
  getEntities,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(Diretor);
