// src/main/webapp/app/entities/diretor/update/diretor-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IDiretor, Diretor } from '../diretor.model';
import { DiretorService } from '../service/diretor.service';
import { IPessoa } from 'app/entities/pessoa/pessoa.model';
import { PessoaService } from 'app/entities/pessoa/service/pessoa.service';
import { IUnidade } from 'app/entities/unidade/unidade.model';
import { UnidadeService } from 'app/entities/unidade/service/unidade.service';

@Component({
  selector: 'jhi-diretor-update',
  templateUrl: './diretor-update.component.html',
})
export class DiretorUpdateComponent implements OnInit {
  isSaving = false;

  pessoasSharedCollection: IPessoa[] = [];
  unidadesSharedCollection: IUnidade[] = [];

  editForm = this.fb.group({
    id: [],
    anoLetivo: [],
    dataInicio: [],
    dataFim: [],
    pessoaDiretor: [],
    unidadeDiretor: [],
  });

  constructor(
    protected diretorService: DiretorService,
    protected pessoaService: PessoaService,
    protected unidadeService: UnidadeService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ diretor }) => {
      this.updateForm(diretor);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const diretor = this.createFromForm();
    if (diretor.id !== undefined) {
      this.subscribeToSaveResponse(this.diretorService.update(diretor));
    } else {
      this.subscribeToSaveResponse(this.diretorService.create(diretor));
    }
  }

  trackPessoaById(index: number, item: IPessoa): number {
    return item.id!;
  }

  trackUnidadeById(index: number, item: IUnidade): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IDiretor>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(diretor: IDiretor): void {
    this.editForm.patchValue({
      id: diretor.id,
      anoLetivo: diretor.anoLetivo,
      dataInicio: diretor.dataInicio,
      dataFim: diretor.dataFim,
      pessoaDiretor: diretor.pessoaDiretor,
      unidadeDiretor: diretor.unidadeDiretor,
    });

    this.pessoasSharedCollection = this.pessoaService.addPessoaToCollectionIfMissing(this.pessoasSharedCollection, diretor.pessoaDiretor);
    this.unidadesSharedCollection = this.unidadeService.addUnidadeToCollectionIfMissing(
      this.unidadesSharedCollection,
      diretor.unidadeDiretor
    );
  }

  protected loadRelationshipsOptions(): void {
    this.pessoaService
      .query()
      .pipe(map((res: HttpResponse<IPessoa[]>) => res.body ?? []))
      .pipe(
        map((pessoas: IPessoa[]) => this.pessoaService.addPessoaToCollectionIfMissing(pessoas, this.editForm.get('pessoaDiretor')!.value))
      )
      .subscribe((pessoas: IPessoa[]) => (this.pessoasSharedCollection = pessoas));

    this.unidadeService
      .query()
      .pipe(map((res: HttpResponse<IUnidade[]>) => res.body ?? []))
      .pipe(
        map((unidades: IUnidade[]) =>
          this.unidadeService.addUnidadeToCollectionIfMissing(unidades, this.editForm.get('unidadeDiretor')!.value)
        )
      )
      .subscribe((unidades: IUnidade[]) => (this.unidadesSharedCollection = unidades));
  }

  protected createFromForm(): IDiretor {
    return {
      ...new Diretor(),
      id: this.editForm.get(['id'])!.value,
      anoLetivo: this.editForm.get(['anoLetivo'])!.value,
      dataInicio: this.editForm.get(['dataInicio'])!.value,
      dataFim: this.editForm.get(['dataFim'])!.value,
      pessoaDiretor: this.editForm.get(['pessoaDiretor'])!.value,
      unidadeDiretor: this.editForm.get(['unidadeDiretor'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-diretor-heading" data-cy="DiretorCreateUpdateHeading" jhiTranslate="escolaOnlineApp.diretor.home.createOrEditLabel">
        Create or edit a Diretor
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.diretor.anoLetivo" for="field_anoLetivo">Ano Letivo</label>
          <input type="number" class="form-control" name="anoLetivo" id="field_anoLetivo" data-cy="anoLetivo" formControlName="anoLetivo" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.diretor.dataInicio" for="field_dataInicio">Data Inicio</label>
          <div class="input-group">
            <input
              id="field_dataInicio"
              data-cy="dataInicio"
              type="text"
              class="form-control"
              name="dataInicio"
              ngbDatepicker
              #dataInicioDp="ngbDatepicker"
              formControlName="dataInicio"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataInicioDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.diretor.dataFim" for="field_dataFim">Data Fim</label>
          <div class="input-group">
            <input
              id="field_dataFim"
              data-cy="dataFim"
              type="text"
              class="form-control"
              name="dataFim"
              ngbDatepicker
              #dataFimDp="ngbDatepicker"
              formControlName="dataFim"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataFimDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.diretor.pessoaDiretor" for="field_pessoaDiretor"
            >Pessoa Diretor</label
          >
          <select
            class="form-control"
            id="field_pessoaDiretor"
            data-cy="pessoaDiretor"
            name="pessoaDiretor"
            formControlName="pessoaDiretor"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="pessoaOption.id === editForm.get('pessoaDiretor')!.value?.id ? editForm.get('pessoaDiretor')!.value : pessoaOption"
              *ngFor="let pessoaOption of pessoasSharedCollection; trackBy: trackPessoaById"
            >
              {{ pessoaOption.id }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.diretor.unidadeDiretor" for="field_unidadeDiretor"
            >Unidade Diretor</label
          >
          <select
            class="form-control"
            id="field_unidadeDiretor"
            data-cy="unidadeDiretor"
            name="unidadeDiretor"
            formControlName="unidadeDiretor"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                unidadeOption.id === editForm.get('unidadeDiretor')!.value?.id ? editForm.get('unidadeDiretor')!.value : unidadeOption
              "
              *ngFor="let unidadeOption of unidadesSharedCollection; trackBy: trackUnidadeById"
            >
              {{ unidadeOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/diretor/diretor-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IPessoa } from 'app/shared/model/pessoa.model';
import { getEntities as getPessoas } from 'app/entities/pessoa/pessoa.reducer';
import { IUnidade } from 'app/shared/model/unidade.model';
import { getEntities as getUnidades } from 'app/entities/unidade/unidade.reducer';
import { getEntity, updateEntity, createEntity, reset } from './diretor.reducer';
import { IDiretor } from 'app/shared/model/diretor.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IDiretorUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const DiretorUpdate = (props: IDiretorUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { diretorEntity, pessoas, unidades, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/diretor' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getPessoas();
    props.getUnidades();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...diretorEntity,
        ...values,
        pessoaDiretor: pessoas.find(it => it.id.toString() === values.pessoaDiretorId.toString()),
        unidadeDiretor: unidades.find(it => it.id.toString() === values.unidadeDiretorId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.diretor.home.createOrEditLabel" data-cy="DiretorCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.diretor.home.createOrEditLabel">Create or edit a Diretor</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : diretorEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="diretor-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="diretor-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="anoLetivoLabel" for="diretor-anoLetivo">
                  <Translate contentKey="escolaOnlineApp.diretor.anoLetivo">Ano Letivo</Translate>
                </Label>
                <AvField id="diretor-anoLetivo" data-cy="anoLetivo" type="string" className="form-control" name="anoLetivo" />
              </AvGroup>
              <AvGroup>
                <Label id="dataInicioLabel" for="diretor-dataInicio">
                  <Translate contentKey="escolaOnlineApp.diretor.dataInicio">Data Inicio</Translate>
                </Label>
                <AvField id="diretor-dataInicio" data-cy="dataInicio" type="date" className="form-control" name="dataInicio" />
              </AvGroup>
              <AvGroup>
                <Label id="dataFimLabel" for="diretor-dataFim">
                  <Translate contentKey="escolaOnlineApp.diretor.dataFim">Data Fim</Translate>
                </Label>
                <AvField id="diretor-dataFim" data-cy="dataFim" type="date" className="form-control" name="dataFim" />
              </AvGroup>
              <AvGroup>
                <Label for="diretor-pessoaDiretor">
                  <Translate contentKey="escolaOnlineApp.diretor.pessoaDiretor">Pessoa Diretor</Translate>
                </Label>
                <AvInput id="diretor-pessoaDiretor" data-cy="pessoaDiretor" type="select" className="form-control" name="pessoaDiretorId">
                  <option value="" key="0" />
                  {pessoas
                    ? pessoas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="diretor-unidadeDiretor">
                  <Translate contentKey="escolaOnlineApp.diretor.unidadeDiretor">Unidade Diretor</Translate>
                </Label>
                <AvInput
                  id="diretor-unidadeDiretor"
                  data-cy="unidadeDiretor"
                  type="select"
                  className="form-control"
                  name="unidadeDiretorId"
                >
                  <option value="" key="0" />
                  {unidades
                    ? unidades.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/diretor" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  pessoas: storeState.pessoa.entities,
  unidades: storeState.unidade.entities,
  diretorEntity: storeState.diretor.entity,
  loading: storeState.diretor.loading,
  updating: storeState.diretor.updating,
  updateSuccess: storeState.diretor.updateSuccess,
});

const mapDispatchToProps = {
  getPessoas,
  getUnidades,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(DiretorUpdate);
