// src/main/webapp/app/entities/serie/serie-detail.tsx
import React, { useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { IRootState } from 'app/shared/reducers';
import { getEntity } from './serie.reducer';
import { APP_DATE_FORMAT, APP_LOCAL_DATE_FORMAT } from 'app/config/constants';

export interface ISerieDetailProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const SerieDetail = (props: ISerieDetailProps) => {
  useEffect(() => {
    props.getEntity(props.match.params.id);
  }, []);

  const { serieEntity } = props;
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="serieDetailsHeading">
          <Translate contentKey="escolaOnlineApp.serie.detail.title">Serie</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{serieEntity.id}</dd>
          <dt>
            <span id="nome">
              <Translate contentKey="escolaOnlineApp.serie.nome">Nome</Translate>
            </span>
          </dt>
          <dd>{serieEntity.nome}</dd>
        </dl>
        <Button tag={Link} to="/serie" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/serie/${serieEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

const mapStateToProps = ({ serie }: IRootState) => ({
  serieEntity: serie.entity,
});

const mapDispatchToProps = { getEntity };

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(SerieDetail);

// src/main/webapp/app/entities/serie/detail/serie-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { ISerie } from '../serie.model';

@Component({
  selector: 'jhi-serie-detail',
  templateUrl: './serie-detail.component.html',
})
export class SerieDetailComponent implements OnInit {
  serie: ISerie | null = null;

  constructor(protected activatedRoute: ActivatedRoute) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ serie }) => {
      this.serie = serie;
    });
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <div *ngIf="serie">
      <h2 data-cy="serieDetailsHeading"><span jhiTranslate="escolaOnlineApp.serie.detail.title">Serie</span></h2>

      <hr />

      <jhi-alert-error></jhi-alert-error>

      <jhi-alert></jhi-alert>

      <dl class="row-md jh-entity-details">
        <dt><span jhiTranslate="global.field.id">ID</span></dt>
        <dd>
          <span>{{ serie.id }}</span>
        </dd>
        <dt><span jhiTranslate="escolaOnlineApp.serie.nome">Nome</span></dt>
        <dd>
          <span>{{ serie.nome }}</span>
        </dd>
      </dl>

      <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
        <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
      </button>

      <button type="button" [routerLink]="['/serie', serie.id, 'edit']" class="btn btn-primary">
        <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
      </button>
    </div>
  </div>
</div>
