// src/main/webapp/app/entities/professor/professor-update.tsx
import React, { useState, useEffect } from 'react';
import { connect } from 'react-redux';
import { Link, RouteComponentProps } from 'react-router-dom';
import { Button, Row, Col, Label } from 'reactstrap';
import { AvFeedback, AvForm, AvGroup, AvInput, AvField } from 'availity-reactstrap-validation';
import { Translate, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { IRootState } from 'app/shared/reducers';

import { IPessoa } from 'app/shared/model/pessoa.model';
import { getEntities as getPessoas } from 'app/entities/pessoa/pessoa.reducer';
import { IUnidade } from 'app/shared/model/unidade.model';
import { getEntities as getUnidades } from 'app/entities/unidade/unidade.reducer';
import { getEntity, updateEntity, createEntity, reset } from './professor.reducer';
import { IProfessor } from 'app/shared/model/professor.model';
import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { mapIdList } from 'app/shared/util/entity-utils';

export interface IProfessorUpdateProps extends StateProps, DispatchProps, RouteComponentProps<{ id: string }> {}

export const ProfessorUpdate = (props: IProfessorUpdateProps) => {
  const [isNew] = useState(!props.match.params || !props.match.params.id);

  const { professorEntity, pessoas, unidades, loading, updating } = props;

  const handleClose = () => {
    props.history.push('/professor' + props.location.search);
  };

  useEffect(() => {
    if (isNew) {
      props.reset();
    } else {
      props.getEntity(props.match.params.id);
    }

    props.getPessoas();
    props.getUnidades();
  }, []);

  useEffect(() => {
    if (props.updateSuccess) {
      handleClose();
    }
  }, [props.updateSuccess]);

  const saveEntity = (event, errors, values) => {
    if (errors.length === 0) {
      const entity = {
        ...professorEntity,
        ...values,
        pessoaProfessor: pessoas.find(it => it.id.toString() === values.pessoaProfessorId.toString()),
        unidadeProfessor: unidades.find(it => it.id.toString() === values.unidadeProfessorId.toString()),
      };

      if (isNew) {
        props.createEntity(entity);
      } else {
        props.updateEntity(entity);
      }
    }
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="escolaOnlineApp.professor.home.createOrEditLabel" data-cy="ProfessorCreateUpdateHeading">
            <Translate contentKey="escolaOnlineApp.professor.home.createOrEditLabel">Create or edit a Professor</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <AvForm model={isNew ? {} : professorEntity} onSubmit={saveEntity}>
              {!isNew ? (
                <AvGroup>
                  <Label for="professor-id">
                    <Translate contentKey="global.field.id">ID</Translate>
                  </Label>
                  <AvInput id="professor-id" type="text" className="form-control" name="id" required readOnly />
                </AvGroup>
              ) : null}
              <AvGroup>
                <Label id="anoLetivoLabel" for="professor-anoLetivo">
                  <Translate contentKey="escolaOnlineApp.professor.anoLetivo">Ano Letivo</Translate>
                </Label>
                <AvField id="professor-anoLetivo" data-cy="anoLetivo" type="string" className="form-control" name="anoLetivo" />
              </AvGroup>
              <AvGroup>
                <Label id="dataInicioLabel" for="professor-dataInicio">
                  <Translate contentKey="escolaOnlineApp.professor.dataInicio">Data Inicio</Translate>
                </Label>
                <AvField id="professor-dataInicio" data-cy="dataInicio" type="date" className="form-control" name="dataInicio" />
              </AvGroup>
              <AvGroup>
                <Label id="dataFimLabel" for="professor-dataFim">
                  <Translate contentKey="escolaOnlineApp.professor.dataFim">Data Fim</Translate>
                </Label>
                <AvField id="professor-dataFim" data-cy="dataFim" type="date" className="form-control" name="dataFim" />
              </AvGroup>
              <AvGroup>
                <Label for="professor-pessoaProfessor">
                  <Translate contentKey="escolaOnlineApp.professor.pessoaProfessor">Pessoa Professor</Translate>
                </Label>
                <AvInput
                  id="professor-pessoaProfessor"
                  data-cy="pessoaProfessor"
                  type="select"
                  className="form-control"
                  name="pessoaProfessorId"
                >
                  <option value="" key="0" />
                  {pessoas
                    ? pessoas.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <AvGroup>
                <Label for="professor-unidadeProfessor">
                  <Translate contentKey="escolaOnlineApp.professor.unidadeProfessor">Unidade Professor</Translate>
                </Label>
                <AvInput
                  id="professor-unidadeProfessor"
                  data-cy="unidadeProfessor"
                  type="select"
                  className="form-control"
                  name="unidadeProfessorId"
                >
                  <option value="" key="0" />
                  {unidades
                    ? unidades.map(otherEntity => (
                        <option value={otherEntity.id} key={otherEntity.id}>
                          {otherEntity.id}
                        </option>
                      ))
                    : null}
                </AvInput>
              </AvGroup>
              <Button tag={Link} id="cancel-save" to="/professor" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </AvForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

const mapStateToProps = (storeState: IRootState) => ({
  pessoas: storeState.pessoa.entities,
  unidades: storeState.unidade.entities,
  professorEntity: storeState.professor.entity,
  loading: storeState.professor.loading,
  updating: storeState.professor.updating,
  updateSuccess: storeState.professor.updateSuccess,
});

const mapDispatchToProps = {
  getPessoas,
  getUnidades,
  getEntity,
  updateEntity,
  createEntity,
  reset,
};

type StateProps = ReturnType<typeof mapStateToProps>;
type DispatchProps = typeof mapDispatchToProps;

export default connect(mapStateToProps, mapDispatchToProps)(ProfessorUpdate);

// src/main/webapp/app/entities/professor/update/professor-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IProfessor, Professor } from '../professor.model';
import { ProfessorService } from '../service/professor.service';
import { IPessoa } from 'app/entities/pessoa/pessoa.model';
import { PessoaService } from 'app/entities/pessoa/service/pessoa.service';
import { IUnidade } from 'app/entities/unidade/unidade.model';
import { UnidadeService } from 'app/entities/unidade/service/unidade.service';

@Component({
  selector: 'jhi-professor-update',
  templateUrl: './professor-update.component.html',
})
export class ProfessorUpdateComponent implements OnInit {
  isSaving = false;

  pessoasSharedCollection: IPessoa[] = [];
  unidadesSharedCollection: IUnidade[] = [];

  editForm = this.fb.group({
    id: [],
    anoLetivo: [],
    dataInicio: [],
    dataFim: [],
    pessoaProfessor: [],
    unidadeProfessor: [],
  });

  constructor(
    protected professorService: ProfessorService,
    protected pessoaService: PessoaService,
    protected unidadeService: UnidadeService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ professor }) => {
      this.updateForm(professor);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const professor = this.createFromForm();
    if (professor.id !== undefined) {
      this.subscribeToSaveResponse(this.professorService.update(professor));
    } else {
      this.subscribeToSaveResponse(this.professorService.create(professor));
    }
  }

  trackPessoaById(index: number, item: IPessoa): number {
    return item.id!;
  }

  trackUnidadeById(index: number, item: IUnidade): number {
    return item.id!;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IProfessor>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(professor: IProfessor): void {
    this.editForm.patchValue({
      id: professor.id,
      anoLetivo: professor.anoLetivo,
      dataInicio: professor.dataInicio,
      dataFim: professor.dataFim,
      pessoaProfessor: professor.pessoaProfessor,
      unidadeProfessor: professor.unidadeProfessor,
    });

    this.pessoasSharedCollection = this.pessoaService.addPessoaToCollectionIfMissing(
      this.pessoasSharedCollection,
      professor.pessoaProfessor
    );
    this.unidadesSharedCollection = this.unidadeService.addUnidadeToCollectionIfMissing(
      this.unidadesSharedCollection,
      professor.unidadeProfessor
    );
  }

  protected loadRelationshipsOptions(): void {
    this.pessoaService
      .query()
      .pipe(map((res: HttpResponse<IPessoa[]>) => res.body ?? []))
      .pipe(
        map((pessoas: IPessoa[]) => this.pessoaService.addPessoaToCollectionIfMissing(pessoas, this.editForm.get('pessoaProfessor')!.value))
      )
      .subscribe((pessoas: IPessoa[]) => (this.pessoasSharedCollection = pessoas));

    this.unidadeService
      .query()
      .pipe(map((res: HttpResponse<IUnidade[]>) => res.body ?? []))
      .pipe(
        map((unidades: IUnidade[]) =>
          this.unidadeService.addUnidadeToCollectionIfMissing(unidades, this.editForm.get('unidadeProfessor')!.value)
        )
      )
      .subscribe((unidades: IUnidade[]) => (this.unidadesSharedCollection = unidades));
  }

  protected createFromForm(): IProfessor {
    return {
      ...new Professor(),
      id: this.editForm.get(['id'])!.value,
      anoLetivo: this.editForm.get(['anoLetivo'])!.value,
      dataInicio: this.editForm.get(['dataInicio'])!.value,
      dataFim: this.editForm.get(['dataFim'])!.value,
      pessoaProfessor: this.editForm.get(['pessoaProfessor'])!.value,
      unidadeProfessor: this.editForm.get(['unidadeProfessor'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-professor-heading" data-cy="ProfessorCreateUpdateHeading" jhiTranslate="escolaOnlineApp.professor.home.createOrEditLabel">
        Create or edit a Professor
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.professor.anoLetivo" for="field_anoLetivo">Ano Letivo</label>
          <input type="number" class="form-control" name="anoLetivo" id="field_anoLetivo" data-cy="anoLetivo" formControlName="anoLetivo" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.professor.dataInicio" for="field_dataInicio">Data Inicio</label>
          <div class="input-group">
            <input
              id="field_dataInicio"
              data-cy="dataInicio"
              type="text"
              class="form-control"
              name="dataInicio"
              ngbDatepicker
              #dataInicioDp="ngbDatepicker"
              formControlName="dataInicio"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataInicioDp.toggle()">
                <fa-icon icon="calendar-alt"></fa-icon>
              </button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.professor.dataFim" for="field_dataFim">Data Fim</label>
          <div class="input-group">
            <input
              id="field_dataFim"
              data-cy="dataFim"
              type="text"
              class="form-control"
              name="dataFim"
              ngbDatepicker
              #dataFimDp="ngbDatepicker"
              formControlName="dataFim"
            />
            <span class="input-group-append">
              <button type="button" class="btn btn-secondary" (click)="dataFimDp.toggle()"><fa-icon icon="calendar-alt"></fa-icon></button>
            </span>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.professor.pessoaProfessor" for="field_pessoaProfessor"
            >Pessoa Professor</label
          >
          <select
            class="form-control"
            id="field_pessoaProfessor"
            data-cy="pessoaProfessor"
            name="pessoaProfessor"
            formControlName="pessoaProfessor"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                pessoaOption.id === editForm.get('pessoaProfessor')!.value?.id ? editForm.get('pessoaProfessor')!.value : pessoaOption
              "
              *ngFor="let pessoaOption of pessoasSharedCollection; trackBy: trackPessoaById"
            >
              {{ pessoaOption.id }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="escolaOnlineApp.professor.unidadeProfessor" for="field_unidadeProfessor"
            >Unidade Professor</label
          >
          <select
            class="form-control"
            id="field_unidadeProfessor"
            data-cy="unidadeProfessor"
            name="unidadeProfessor"
            formControlName="unidadeProfessor"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                unidadeOption.id === editForm.get('unidadeProfessor')!.value?.id ? editForm.get('unidadeProfessor')!.value : unidadeOption
              "
              *ngFor="let unidadeOption of unidadesSharedCollection; trackBy: trackUnidadeById"
            >
              {{ unidadeOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
